/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj;


import com.github.curiousoddman.curious_images.dbobj.tables.Album;
import com.github.curiousoddman.curious_images.dbobj.tables.AlbumPhoto;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroup;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroupMember;
import com.github.curiousoddman.curious_images.dbobj.tables.Face;
import com.github.curiousoddman.curious_images.dbobj.tables.FlywaySchemaHistory;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo;
import com.github.curiousoddman.curious_images.dbobj.tables.PhotoHash;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_ALBUM_PHOTO_ALBUM = Internal.createIndex(DSL.name("IDX_ALBUM_PHOTO_ALBUM"), AlbumPhoto.ALBUM_PHOTO, new OrderField[] { AlbumPhoto.ALBUM_PHOTO.ALBUM_ID }, false);
    public static final Index IDX_ALBUM_PHOTO_PHOTO = Internal.createIndex(DSL.name("IDX_ALBUM_PHOTO_PHOTO"), AlbumPhoto.ALBUM_PHOTO, new OrderField[] { AlbumPhoto.ALBUM_PHOTO.PHOTO_ID }, false);
    public static final Index IDX_ALBUM_TYPE = Internal.createIndex(DSL.name("IDX_ALBUM_TYPE"), Album.ALBUM, new OrderField[] { Album.ALBUM.TYPE }, false);
    public static final Index IDX_DUPLICATE_GROUP_JOB = Internal.createIndex(DSL.name("IDX_DUPLICATE_GROUP_JOB"), DuplicateGroup.DUPLICATE_GROUP, new OrderField[] { DuplicateGroup.DUPLICATE_GROUP.DUPLICATE_JOB_ID }, false);
    public static final Index IDX_DUPLICATE_GROUP_MEMBER_GROUP = Internal.createIndex(DSL.name("IDX_DUPLICATE_GROUP_MEMBER_GROUP"), DuplicateGroupMember.DUPLICATE_GROUP_MEMBER, new OrderField[] { DuplicateGroupMember.DUPLICATE_GROUP_MEMBER.DUPLICATE_GROUP_ID }, false);
    public static final Index IDX_DUPLICATE_GROUP_MEMBER_PHOTO = Internal.createIndex(DSL.name("IDX_DUPLICATE_GROUP_MEMBER_PHOTO"), DuplicateGroupMember.DUPLICATE_GROUP_MEMBER, new OrderField[] { DuplicateGroupMember.DUPLICATE_GROUP_MEMBER.PHOTO_ID }, false);
    public static final Index IDX_FACE_PERSON = Internal.createIndex(DSL.name("IDX_FACE_PERSON"), Face.FACE, new OrderField[] { Face.FACE.PERSON_ID }, false);
    public static final Index IDX_FACE_PHOTO = Internal.createIndex(DSL.name("IDX_FACE_PHOTO"), Face.FACE, new OrderField[] { Face.FACE.PHOTO_ID }, false);
    public static final Index IDX_PHOTO_CAPTURE_DATE = Internal.createIndex(DSL.name("IDX_PHOTO_CAPTURE_DATE"), Photo.PHOTO, new OrderField[] { Photo.PHOTO.CAPTURE_DATE }, false);
    public static final Index IDX_PHOTO_FOLDER = Internal.createIndex(DSL.name("IDX_PHOTO_FOLDER"), Photo.PHOTO, new OrderField[] { Photo.PHOTO.FOLDER_ID }, false);
    public static final Index IDX_PHOTO_HASH_PIXEL_HASH = Internal.createIndex(DSL.name("IDX_PHOTO_HASH_PIXEL_HASH"), PhotoHash.PHOTO_HASH, new OrderField[] { PhotoHash.PHOTO_HASH.PIXEL_HASH }, false);
}
