/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj;


import com.github.curiousoddman.curious_images.dbobj.tables.FlywaySchemaHistory;
import com.github.curiousoddman.curious_images.dbobj.tables.PendingAction;
import com.github.curiousoddman.curious_images.dbobj.tables.UserPreferences;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.PENDING_ACTION</code>.
     */
    public final PendingAction PENDING_ACTION = PendingAction.PENDING_ACTION;

    /**
     * The table <code>public.USER_PREFERENCES</code>.
     */
    public final UserPreferences USER_PREFERENCES = UserPreferences.USER_PREFERENCES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            PendingAction.PENDING_ACTION,
            UserPreferences.USER_PREFERENCES
        );
    }
}
