/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj;


import com.github.curiousoddman.curious_images.dbobj.tables.Album;
import com.github.curiousoddman.curious_images.dbobj.tables.AlbumPhoto;
import com.github.curiousoddman.curious_images.dbobj.tables.ClipEmbedding;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroup;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroupMember;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateJob;
import com.github.curiousoddman.curious_images.dbobj.tables.Face;
import com.github.curiousoddman.curious_images.dbobj.tables.FaceEmbedding;
import com.github.curiousoddman.curious_images.dbobj.tables.FlywaySchemaHistory;
import com.github.curiousoddman.curious_images.dbobj.tables.Folder;
import com.github.curiousoddman.curious_images.dbobj.tables.ImportRoot;
import com.github.curiousoddman.curious_images.dbobj.tables.PendingAction;
import com.github.curiousoddman.curious_images.dbobj.tables.Person;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo;
import com.github.curiousoddman.curious_images.dbobj.tables.PhotoHash;
import com.github.curiousoddman.curious_images.dbobj.tables.Thumbnail;
import com.github.curiousoddman.curious_images.dbobj.tables.UserPreferences;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.ALBUM</code>.
     */
    public final Album ALBUM = Album.ALBUM;

    /**
     * The table <code>public.ALBUM_PHOTO</code>.
     */
    public final AlbumPhoto ALBUM_PHOTO = AlbumPhoto.ALBUM_PHOTO;

    /**
     * The table <code>public.CLIP_EMBEDDING</code>.
     */
    public final ClipEmbedding CLIP_EMBEDDING = ClipEmbedding.CLIP_EMBEDDING;

    /**
     * The table <code>public.DUPLICATE_GROUP</code>.
     */
    public final DuplicateGroup DUPLICATE_GROUP = DuplicateGroup.DUPLICATE_GROUP;

    /**
     * The table <code>public.DUPLICATE_GROUP_MEMBER</code>.
     */
    public final DuplicateGroupMember DUPLICATE_GROUP_MEMBER = DuplicateGroupMember.DUPLICATE_GROUP_MEMBER;

    /**
     * The table <code>public.DUPLICATE_JOB</code>.
     */
    public final DuplicateJob DUPLICATE_JOB = DuplicateJob.DUPLICATE_JOB;

    /**
     * The table <code>public.FACE</code>.
     */
    public final Face FACE = Face.FACE;

    /**
     * The table <code>public.FACE_EMBEDDING</code>.
     */
    public final FaceEmbedding FACE_EMBEDDING = FaceEmbedding.FACE_EMBEDDING;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.FOLDER</code>.
     */
    public final Folder FOLDER = Folder.FOLDER;

    /**
     * The table <code>public.IMPORT_ROOT</code>.
     */
    public final ImportRoot IMPORT_ROOT = ImportRoot.IMPORT_ROOT;

    /**
     * The table <code>public.PENDING_ACTION</code>.
     */
    public final PendingAction PENDING_ACTION = PendingAction.PENDING_ACTION;

    /**
     * The table <code>public.PERSON</code>.
     */
    public final Person PERSON = Person.PERSON;

    /**
     * The table <code>public.PHOTO</code>.
     */
    public final Photo PHOTO = Photo.PHOTO;

    /**
     * The table <code>public.PHOTO_HASH</code>.
     */
    public final PhotoHash PHOTO_HASH = PhotoHash.PHOTO_HASH;

    /**
     * The table <code>public.THUMBNAIL</code>.
     */
    public final Thumbnail THUMBNAIL = Thumbnail.THUMBNAIL;

    /**
     * The table <code>public.USER_PREFERENCES</code>.
     */
    public final UserPreferences USER_PREFERENCES = UserPreferences.USER_PREFERENCES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Album.ALBUM,
            AlbumPhoto.ALBUM_PHOTO,
            ClipEmbedding.CLIP_EMBEDDING,
            DuplicateGroup.DUPLICATE_GROUP,
            DuplicateGroupMember.DUPLICATE_GROUP_MEMBER,
            DuplicateJob.DUPLICATE_JOB,
            Face.FACE,
            FaceEmbedding.FACE_EMBEDDING,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Folder.FOLDER,
            ImportRoot.IMPORT_ROOT,
            PendingAction.PENDING_ACTION,
            Person.PERSON,
            Photo.PHOTO,
            PhotoHash.PHOTO_HASH,
            Thumbnail.THUMBNAIL,
            UserPreferences.USER_PREFERENCES
        );
    }
}
