/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj;


import com.github.curiousoddman.curious_images.dbobj.tables.FlywaySchemaHistory;
import com.github.curiousoddman.curious_images.dbobj.tables.Folder;
import com.github.curiousoddman.curious_images.dbobj.tables.ImportRoot;
import com.github.curiousoddman.curious_images.dbobj.tables.PendingAction;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo;
import com.github.curiousoddman.curious_images.dbobj.tables.Thumbnail;
import com.github.curiousoddman.curious_images.dbobj.tables.UserPreferences;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.FOLDER</code>.
     */
    public static final Folder FOLDER = Folder.FOLDER;

    /**
     * The table <code>public.IMPORT_ROOT</code>.
     */
    public static final ImportRoot IMPORT_ROOT = ImportRoot.IMPORT_ROOT;

    /**
     * The table <code>public.PENDING_ACTION</code>.
     */
    public static final PendingAction PENDING_ACTION = PendingAction.PENDING_ACTION;

    /**
     * The table <code>public.PHOTO</code>.
     */
    public static final Photo PHOTO = Photo.PHOTO;

    /**
     * The table <code>public.THUMBNAIL</code>.
     */
    public static final Thumbnail THUMBNAIL = Thumbnail.THUMBNAIL;

    /**
     * The table <code>public.USER_PREFERENCES</code>.
     */
    public static final UserPreferences USER_PREFERENCES = UserPreferences.USER_PREFERENCES;
}
