/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj;


import com.github.curiousoddman.curious_images.dbobj.tables.Album;
import com.github.curiousoddman.curious_images.dbobj.tables.AlbumMedia;
import com.github.curiousoddman.curious_images.dbobj.tables.ClipEmbedding;
import com.github.curiousoddman.curious_images.dbobj.tables.Cluster;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroup;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroupMember;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateJob;
import com.github.curiousoddman.curious_images.dbobj.tables.Face;
import com.github.curiousoddman.curious_images.dbobj.tables.FaceEmbedding;
import com.github.curiousoddman.curious_images.dbobj.tables.FlywaySchemaHistory;
import com.github.curiousoddman.curious_images.dbobj.tables.Folder;
import com.github.curiousoddman.curious_images.dbobj.tables.ImportRoot;
import com.github.curiousoddman.curious_images.dbobj.tables.Media;
import com.github.curiousoddman.curious_images.dbobj.tables.MediaHash;
import com.github.curiousoddman.curious_images.dbobj.tables.MediaPhoto;
import com.github.curiousoddman.curious_images.dbobj.tables.MediaTag;
import com.github.curiousoddman.curious_images.dbobj.tables.MediaVideo;
import com.github.curiousoddman.curious_images.dbobj.tables.PendingAction;
import com.github.curiousoddman.curious_images.dbobj.tables.Person;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo;
import com.github.curiousoddman.curious_images.dbobj.tables.PhotoPreview;
import com.github.curiousoddman.curious_images.dbobj.tables.TagEmbedding;
import com.github.curiousoddman.curious_images.dbobj.tables.Thumbnail;
import com.github.curiousoddman.curious_images.dbobj.tables.UserPreferences;
import com.github.curiousoddman.curious_images.dbobj.tables.Video;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.ALBUM</code>.
     */
    public static final Album ALBUM = Album.ALBUM;

    /**
     * The table <code>public.ALBUM_MEDIA</code>.
     */
    public static final AlbumMedia ALBUM_MEDIA = AlbumMedia.ALBUM_MEDIA;

    /**
     * The table <code>public.CLIP_EMBEDDING</code>.
     */
    public static final ClipEmbedding CLIP_EMBEDDING = ClipEmbedding.CLIP_EMBEDDING;

    /**
     * The table <code>public.CLUSTER</code>.
     */
    public static final Cluster CLUSTER = Cluster.CLUSTER;

    /**
     * The table <code>public.DUPLICATE_GROUP</code>.
     */
    public static final DuplicateGroup DUPLICATE_GROUP = DuplicateGroup.DUPLICATE_GROUP;

    /**
     * The table <code>public.DUPLICATE_GROUP_MEMBER</code>.
     */
    public static final DuplicateGroupMember DUPLICATE_GROUP_MEMBER = DuplicateGroupMember.DUPLICATE_GROUP_MEMBER;

    /**
     * The table <code>public.DUPLICATE_JOB</code>.
     */
    public static final DuplicateJob DUPLICATE_JOB = DuplicateJob.DUPLICATE_JOB;

    /**
     * The table <code>public.FACE</code>.
     */
    public static final Face FACE = Face.FACE;

    /**
     * The table <code>public.FACE_EMBEDDING</code>.
     */
    public static final FaceEmbedding FACE_EMBEDDING = FaceEmbedding.FACE_EMBEDDING;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.FOLDER</code>.
     */
    public static final Folder FOLDER = Folder.FOLDER;

    /**
     * The table <code>public.IMPORT_ROOT</code>.
     */
    public static final ImportRoot IMPORT_ROOT = ImportRoot.IMPORT_ROOT;

    /**
     * The table <code>public.MEDIA</code>.
     */
    public static final Media MEDIA = Media.MEDIA;

    /**
     * The table <code>public.MEDIA_HASH</code>.
     */
    public static final MediaHash MEDIA_HASH = MediaHash.MEDIA_HASH;

    /**
     * The table <code>public.MEDIA_PHOTO</code>.
     */
    public static final MediaPhoto MEDIA_PHOTO = MediaPhoto.MEDIA_PHOTO;

    /**
     * The table <code>public.MEDIA_TAG</code>.
     */
    public static final MediaTag MEDIA_TAG = MediaTag.MEDIA_TAG;

    /**
     * The table <code>public.MEDIA_VIDEO</code>.
     */
    public static final MediaVideo MEDIA_VIDEO = MediaVideo.MEDIA_VIDEO;

    /**
     * The table <code>public.PENDING_ACTION</code>.
     */
    public static final PendingAction PENDING_ACTION = PendingAction.PENDING_ACTION;

    /**
     * The table <code>public.PERSON</code>.
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * The table <code>public.PHOTO</code>.
     */
    public static final Photo PHOTO = Photo.PHOTO;

    /**
     * The table <code>public.PHOTO_PREVIEW</code>.
     */
    public static final PhotoPreview PHOTO_PREVIEW = PhotoPreview.PHOTO_PREVIEW;

    /**
     * The table <code>public.TAG_EMBEDDING</code>.
     */
    public static final TagEmbedding TAG_EMBEDDING = TagEmbedding.TAG_EMBEDDING;

    /**
     * The table <code>public.THUMBNAIL</code>.
     */
    public static final Thumbnail THUMBNAIL = Thumbnail.THUMBNAIL;

    /**
     * The table <code>public.USER_PREFERENCES</code>.
     */
    public static final UserPreferences USER_PREFERENCES = UserPreferences.USER_PREFERENCES;

    /**
     * The table <code>public.VIDEO</code>.
     */
    public static final Video VIDEO = Video.VIDEO;
}
