USER_DATA_ROOT: ~/cimages

spring:
  main:
    web-application-type: servlet
  application:
    name: curious-images
  datasource:
    url: jdbc:h2:file:${USER_DATA_ROOT}/cimages-${ENV};DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  sql.init.mode: always
  jpa.defer-datasource-initialization: false
  title: cImages
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED}

app:
  thumbnail-cache:
    dir: ${USER_DATA_ROOT}/dev/thumb-cache-${ENV}
  duplicate-detection:
    thread-count: 4
  ai:
    model-dir: ${USER_DATA_ROOT}/models
    index-root: ${USER_DATA_ROOT}/index-${ENV}

logging.level:
  org.jooq.Constants: off
  com:
    github:
      curiousoddman:
        curious_images:
          ui:
            controller:
              element: debug
          model:
            playlist: debug
