ENV: dev
#DATABASE_FILE: cimages-prod-copy
H2_CONSOLE_ENABLED: true
logging:
  level:
    com:
      github:
        curiousoddman:
          curious_images:
            ui:
              controller:
                custom:
                  com.github.curiousoddman.curious_images.ui.controller.custom.GridCellController: info
                  RightPanelController: debug
