/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.AiProcessingStatus;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AiProcessingStatusRecord extends UpdatableRecordImpl<AiProcessingStatusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.AI_PROCESSING_STATUS.PHOTO_ID</code>.
     */
    public void setPhotoId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.AI_PROCESSING_STATUS.PHOTO_ID</code>.
     */
    public Long getPhotoId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.AI_PROCESSING_STATUS.FACE_DETECT_DONE</code>.
     */
    public void setFaceDetectDone(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.AI_PROCESSING_STATUS.FACE_DETECT_DONE</code>.
     */
    public Boolean getFaceDetectDone() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.AI_PROCESSING_STATUS.FACE_EMBED_DONE</code>.
     */
    public void setFaceEmbedDone(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.AI_PROCESSING_STATUS.FACE_EMBED_DONE</code>.
     */
    public Boolean getFaceEmbedDone() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.AI_PROCESSING_STATUS.CLIP_EMBED_DONE</code>.
     */
    public void setClipEmbedDone(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.AI_PROCESSING_STATUS.CLIP_EMBED_DONE</code>.
     */
    public Boolean getClipEmbedDone() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.AI_PROCESSING_STATUS.LUCENE_INDEX_DONE</code>.
     */
    public void setLuceneIndexDone(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.AI_PROCESSING_STATUS.LUCENE_INDEX_DONE</code>.
     */
    public Boolean getLuceneIndexDone() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.AI_PROCESSING_STATUS.LAST_ERROR</code>.
     */
    public void setLastError(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.AI_PROCESSING_STATUS.LAST_ERROR</code>.
     */
    public String getLastError() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.AI_PROCESSING_STATUS.RETRY_COUNT</code>.
     */
    public void setRetryCount(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.AI_PROCESSING_STATUS.RETRY_COUNT</code>.
     */
    public Short getRetryCount() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.AI_PROCESSING_STATUS.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.AI_PROCESSING_STATUS.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AiProcessingStatusRecord
     */
    public AiProcessingStatusRecord() {
        super(AiProcessingStatus.AI_PROCESSING_STATUS);
    }

    /**
     * Create a detached, initialised AiProcessingStatusRecord
     */
    public AiProcessingStatusRecord(Long photoId, Boolean faceDetectDone, Boolean faceEmbedDone, Boolean clipEmbedDone, Boolean luceneIndexDone, String lastError, Short retryCount, LocalDateTime updatedAt) {
        super(AiProcessingStatus.AI_PROCESSING_STATUS);

        setPhotoId(photoId);
        setFaceDetectDone(faceDetectDone);
        setFaceEmbedDone(faceEmbedDone);
        setClipEmbedDone(clipEmbedDone);
        setLuceneIndexDone(luceneIndexDone);
        setLastError(lastError);
        setRetryCount(retryCount);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
