/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.Album;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AlbumRecord extends UpdatableRecordImpl<AlbumRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ALBUM.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ALBUM.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ALBUM.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ALBUM.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ALBUM.TYPE</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ALBUM.TYPE</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ALBUM.COVER_PHOTO_ID</code>.
     */
    public void setCoverPhotoId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ALBUM.COVER_PHOTO_ID</code>.
     */
    public Long getCoverPhotoId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.ALBUM.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ALBUM.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.ALBUM.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ALBUM.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.ALBUM.META_JSON</code>.
     */
    public void setMetaJson(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ALBUM.META_JSON</code>.
     */
    public String getMetaJson() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlbumRecord
     */
    public AlbumRecord() {
        super(Album.ALBUM);
    }

    /**
     * Create a detached, initialised AlbumRecord
     */
    public AlbumRecord(Long id, String name, String type, Long coverPhotoId, LocalDateTime createdAt, LocalDateTime updatedAt, String metaJson) {
        super(Album.ALBUM);

        setId(id);
        setName(name);
        setType(type);
        setCoverPhotoId(coverPhotoId);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setMetaJson(metaJson);
        resetChangedOnNotNull();
    }
}
