/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.AlbumMedia;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AlbumMediaRecord extends UpdatableRecordImpl<AlbumMediaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ALBUM_MEDIA.ALBUM_ID</code>.
     */
    public void setAlbumId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ALBUM_MEDIA.ALBUM_ID</code>.
     */
    public Long getAlbumId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.ALBUM_MEDIA.MEDIA_ID</code>.
     */
    public void setMediaId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ALBUM_MEDIA.MEDIA_ID</code>.
     */
    public Long getMediaId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.ALBUM_MEDIA.SORT_ORDER</code>.
     */
    public void setSortOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ALBUM_MEDIA.SORT_ORDER</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.ALBUM_MEDIA.ADDED_AT</code>.
     */
    public void setAddedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ALBUM_MEDIA.ADDED_AT</code>.
     */
    public LocalDateTime getAddedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlbumMediaRecord
     */
    public AlbumMediaRecord() {
        super(AlbumMedia.ALBUM_MEDIA);
    }

    /**
     * Create a detached, initialised AlbumMediaRecord
     */
    public AlbumMediaRecord(Long albumId, Long mediaId, Integer sortOrder, LocalDateTime addedAt) {
        super(AlbumMedia.ALBUM_MEDIA);

        setAlbumId(albumId);
        setMediaId(mediaId);
        setSortOrder(sortOrder);
        setAddedAt(addedAt);
        resetChangedOnNotNull();
    }
}
