/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.Cluster;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClusterRecord extends UpdatableRecordImpl<ClusterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.CLUSTER.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.CLUSTER.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.CLUSTER.PERSON_ID</code>.
     */
    public void setPersonId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.CLUSTER.PERSON_ID</code>.
     */
    public Long getPersonId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.CLUSTER.CENTROID_EMBEDDING</code>.
     */
    public void setCentroidEmbedding(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.CLUSTER.CENTROID_EMBEDDING</code>.
     */
    public byte[] getCentroidEmbedding() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>public.CLUSTER.MEMBER_COUNT</code>.
     */
    public void setMemberCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.CLUSTER.MEMBER_COUNT</code>.
     */
    public Integer getMemberCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.CLUSTER.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.CLUSTER.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.CLUSTER.UPDATED_AT</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.CLUSTER.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClusterRecord
     */
    public ClusterRecord() {
        super(Cluster.CLUSTER);
    }

    /**
     * Create a detached, initialised ClusterRecord
     */
    public ClusterRecord(Long id, Long personId, byte[] centroidEmbedding, Integer memberCount, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Cluster.CLUSTER);

        setId(id);
        setPersonId(personId);
        setCentroidEmbedding(centroidEmbedding);
        setMemberCount(memberCount);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
