/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroup;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.19.28",
                "schema version:none"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class DuplicateGroupRecord extends UpdatableRecordImpl<DuplicateGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.DUPLICATE_GROUP.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.DUPLICATE_GROUP.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.DUPLICATE_GROUP.DUPLICATE_JOB_ID</code>.
     */
    public void setDuplicateJobId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.DUPLICATE_GROUP.DUPLICATE_JOB_ID</code>.
     */
    public Long getDuplicateJobId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.DUPLICATE_GROUP.EXTENSION</code>.
     */
    public void setExtension(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.DUPLICATE_GROUP.EXTENSION</code>.
     */
    public String getExtension() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.DUPLICATE_GROUP.PIXEL_HASH</code>.
     */
    public void setPixelHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.DUPLICATE_GROUP.PIXEL_HASH</code>.
     */
    public String getPixelHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.DUPLICATE_GROUP.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.DUPLICATE_GROUP.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DuplicateGroupRecord
     */
    public DuplicateGroupRecord() {
        super(DuplicateGroup.DUPLICATE_GROUP);
    }

    /**
     * Create a detached, initialised DuplicateGroupRecord
     */
    public DuplicateGroupRecord(Long id, Long duplicateJobId, String extension, String pixelHash, LocalDateTime createdAt) {
        super(DuplicateGroup.DUPLICATE_GROUP);

        setId(id);
        setDuplicateJobId(duplicateJobId);
        setExtension(extension);
        setPixelHash(pixelHash);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
