/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroupMember;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DuplicateGroupMemberRecord extends UpdatableRecordImpl<DuplicateGroupMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.DUPLICATE_GROUP_MEMBER.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.DUPLICATE_GROUP_MEMBER.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.DUPLICATE_GROUP_MEMBER.DUPLICATE_GROUP_ID</code>.
     */
    public void setDuplicateGroupId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.DUPLICATE_GROUP_MEMBER.DUPLICATE_GROUP_ID</code>.
     */
    public Long getDuplicateGroupId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.DUPLICATE_GROUP_MEMBER.MEDIA_ID</code>.
     */
    public void setMediaId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.DUPLICATE_GROUP_MEMBER.MEDIA_ID</code>.
     */
    public Long getMediaId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DuplicateGroupMemberRecord
     */
    public DuplicateGroupMemberRecord() {
        super(DuplicateGroupMember.DUPLICATE_GROUP_MEMBER);
    }

    /**
     * Create a detached, initialised DuplicateGroupMemberRecord
     */
    public DuplicateGroupMemberRecord(Long id, Long duplicateGroupId, Long mediaId) {
        super(DuplicateGroupMember.DUPLICATE_GROUP_MEMBER);

        setId(id);
        setDuplicateGroupId(duplicateGroupId);
        setMediaId(mediaId);
        resetChangedOnNotNull();
    }
}
