/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.Face;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FaceRecord extends UpdatableRecordImpl<FaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.FACE.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.FACE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.FACE.PHOTO_ID</code>.
     */
    public void setPhotoId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.FACE.PHOTO_ID</code>.
     */
    public Long getPhotoId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.FACE.BBOX_X</code>.
     */
    public void setBboxX(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.FACE.BBOX_X</code>.
     */
    public Double getBboxX() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.FACE.BBOX_Y</code>.
     */
    public void setBboxY(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.FACE.BBOX_Y</code>.
     */
    public Double getBboxY() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.FACE.BBOX_W</code>.
     */
    public void setBboxW(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.FACE.BBOX_W</code>.
     */
    public Double getBboxW() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.FACE.BBOX_H</code>.
     */
    public void setBboxH(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.FACE.BBOX_H</code>.
     */
    public Double getBboxH() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.FACE.CONFIDENCE</code>.
     */
    public void setConfidence(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.FACE.CONFIDENCE</code>.
     */
    public Double getConfidence() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.FACE.LANDMARK_LEFT_EYE_X</code>.
     */
    public void setLandmarkLeftEyeX(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.FACE.LANDMARK_LEFT_EYE_X</code>.
     */
    public Double getLandmarkLeftEyeX() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.FACE.LANDMARK_LEFT_EYE_Y</code>.
     */
    public void setLandmarkLeftEyeY(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.FACE.LANDMARK_LEFT_EYE_Y</code>.
     */
    public Double getLandmarkLeftEyeY() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>public.FACE.LANDMARK_RIGHT_EYE_X</code>.
     */
    public void setLandmarkRightEyeX(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.FACE.LANDMARK_RIGHT_EYE_X</code>.
     */
    public Double getLandmarkRightEyeX() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.FACE.LANDMARK_RIGHT_EYE_Y</code>.
     */
    public void setLandmarkRightEyeY(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.FACE.LANDMARK_RIGHT_EYE_Y</code>.
     */
    public Double getLandmarkRightEyeY() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>public.FACE.LANDMARK_NOSE_X</code>.
     */
    public void setLandmarkNoseX(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.FACE.LANDMARK_NOSE_X</code>.
     */
    public Double getLandmarkNoseX() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>public.FACE.LANDMARK_NOSE_Y</code>.
     */
    public void setLandmarkNoseY(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.FACE.LANDMARK_NOSE_Y</code>.
     */
    public Double getLandmarkNoseY() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>public.FACE.LANDMARK_LEFT_MOUTH_X</code>.
     */
    public void setLandmarkLeftMouthX(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.FACE.LANDMARK_LEFT_MOUTH_X</code>.
     */
    public Double getLandmarkLeftMouthX() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>public.FACE.LANDMARK_LEFT_MOUTH_Y</code>.
     */
    public void setLandmarkLeftMouthY(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.FACE.LANDMARK_LEFT_MOUTH_Y</code>.
     */
    public Double getLandmarkLeftMouthY() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>public.FACE.LANDMARK_RIGHT_MOUTH_X</code>.
     */
    public void setLandmarkRightMouthX(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.FACE.LANDMARK_RIGHT_MOUTH_X</code>.
     */
    public Double getLandmarkRightMouthX() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>public.FACE.LANDMARK_RIGHT_MOUTH_Y</code>.
     */
    public void setLandmarkRightMouthY(Double value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.FACE.LANDMARK_RIGHT_MOUTH_Y</code>.
     */
    public Double getLandmarkRightMouthY() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>public.FACE.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.FACE.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>public.FACE.THUMBNAIL_ABSOLUTE_PATH</code>.
     */
    public void setThumbnailAbsolutePath(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.FACE.THUMBNAIL_ABSOLUTE_PATH</code>.
     */
    public String getThumbnailAbsolutePath() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.FACE.ASSIGNMENT_LOCKED</code>.
     */
    public void setAssignmentLocked(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.FACE.ASSIGNMENT_LOCKED</code>.
     */
    public Boolean getAssignmentLocked() {
        return (Boolean) get(19);
    }

    /**
     * Setter for <code>public.FACE.EXCLUDED</code>.
     */
    public void setExcluded(Boolean value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.FACE.EXCLUDED</code>.
     */
    public Boolean getExcluded() {
        return (Boolean) get(20);
    }

    /**
     * Setter for <code>public.FACE.CLUSTER_ID</code>.
     */
    public void setClusterId(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.FACE.CLUSTER_ID</code>.
     */
    public Long getClusterId() {
        return (Long) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FaceRecord
     */
    public FaceRecord() {
        super(Face.FACE);
    }

    /**
     * Create a detached, initialised FaceRecord
     */
    public FaceRecord(Long id, Long photoId, Double bboxX, Double bboxY, Double bboxW, Double bboxH, Double confidence, Double landmarkLeftEyeX, Double landmarkLeftEyeY, Double landmarkRightEyeX, Double landmarkRightEyeY, Double landmarkNoseX, Double landmarkNoseY, Double landmarkLeftMouthX, Double landmarkLeftMouthY, Double landmarkRightMouthX, Double landmarkRightMouthY, LocalDateTime createdAt, String thumbnailAbsolutePath, Boolean assignmentLocked, Boolean excluded, Long clusterId) {
        super(Face.FACE);

        setId(id);
        setPhotoId(photoId);
        setBboxX(bboxX);
        setBboxY(bboxY);
        setBboxW(bboxW);
        setBboxH(bboxH);
        setConfidence(confidence);
        setLandmarkLeftEyeX(landmarkLeftEyeX);
        setLandmarkLeftEyeY(landmarkLeftEyeY);
        setLandmarkRightEyeX(landmarkRightEyeX);
        setLandmarkRightEyeY(landmarkRightEyeY);
        setLandmarkNoseX(landmarkNoseX);
        setLandmarkNoseY(landmarkNoseY);
        setLandmarkLeftMouthX(landmarkLeftMouthX);
        setLandmarkLeftMouthY(landmarkLeftMouthY);
        setLandmarkRightMouthX(landmarkRightMouthX);
        setLandmarkRightMouthY(landmarkRightMouthY);
        setCreatedAt(createdAt);
        setThumbnailAbsolutePath(thumbnailAbsolutePath);
        setAssignmentLocked(assignmentLocked);
        setExcluded(excluded);
        setClusterId(clusterId);
        resetChangedOnNotNull();
    }
}
