/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.FaceEmbedding;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FaceEmbeddingRecord extends UpdatableRecordImpl<FaceEmbeddingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.FACE_EMBEDDING.FACE_ID</code>.
     */
    public void setFaceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.FACE_EMBEDDING.FACE_ID</code>.
     */
    public Long getFaceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.FACE_EMBEDDING.EMBEDDING</code>.
     */
    public void setEmbedding(byte[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.FACE_EMBEDDING.EMBEDDING</code>.
     */
    public byte[] getEmbedding() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>public.FACE_EMBEDDING.MODEL_VER</code>.
     */
    public void setModelVer(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.FACE_EMBEDDING.MODEL_VER</code>.
     */
    public String getModelVer() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FaceEmbeddingRecord
     */
    public FaceEmbeddingRecord() {
        super(FaceEmbedding.FACE_EMBEDDING);
    }

    /**
     * Create a detached, initialised FaceEmbeddingRecord
     */
    public FaceEmbeddingRecord(Long faceId, byte[] embedding, String modelVer) {
        super(FaceEmbedding.FACE_EMBEDDING);

        setFaceId(faceId);
        setEmbedding(embedding);
        setModelVer(modelVer);
        resetChangedOnNotNull();
    }
}
