/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.Face;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FaceRecord extends UpdatableRecordImpl<FaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.FACE.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.FACE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.FACE.PHOTO_ID</code>.
     */
    public void setPhotoId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.FACE.PHOTO_ID</code>.
     */
    public Long getPhotoId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.FACE.PERSON_ID</code>.
     */
    public void setPersonId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.FACE.PERSON_ID</code>.
     */
    public Long getPersonId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.FACE.BBOX_X</code>.
     */
    public void setBboxX(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.FACE.BBOX_X</code>.
     */
    public Double getBboxX() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.FACE.BBOX_Y</code>.
     */
    public void setBboxY(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.FACE.BBOX_Y</code>.
     */
    public Double getBboxY() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.FACE.BBOX_W</code>.
     */
    public void setBboxW(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.FACE.BBOX_W</code>.
     */
    public Double getBboxW() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.FACE.BBOX_H</code>.
     */
    public void setBboxH(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.FACE.BBOX_H</code>.
     */
    public Double getBboxH() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>public.FACE.CONFIDENCE</code>.
     */
    public void setConfidence(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.FACE.CONFIDENCE</code>.
     */
    public Double getConfidence() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>public.FACE.LANDMARK_JSON</code>.
     */
    public void setLandmarkJson(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.FACE.LANDMARK_JSON</code>.
     */
    public String getLandmarkJson() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.FACE.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.FACE.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FaceRecord
     */
    public FaceRecord() {
        super(Face.FACE);
    }

    /**
     * Create a detached, initialised FaceRecord
     */
    public FaceRecord(Long id, Long photoId, Long personId, Double bboxX, Double bboxY, Double bboxW, Double bboxH, Double confidence, String landmarkJson, LocalDateTime createdAt) {
        super(Face.FACE);

        setId(id);
        setPhotoId(photoId);
        setPersonId(personId);
        setBboxX(bboxX);
        setBboxY(bboxY);
        setBboxW(bboxW);
        setBboxH(bboxH);
        setConfidence(confidence);
        setLandmarkJson(landmarkJson);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
