/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.Folder;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FolderRecord extends UpdatableRecordImpl<FolderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.FOLDER.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.FOLDER.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.FOLDER.IMPORT_ROOT_ID</code>.
     */
    public void setImportRootId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.FOLDER.IMPORT_ROOT_ID</code>.
     */
    public Long getImportRootId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.FOLDER.PARENT_FOLDER_ID</code>.
     */
    public void setParentFolderId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.FOLDER.PARENT_FOLDER_ID</code>.
     */
    public Long getParentFolderId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.FOLDER.RELATIVE_PATH</code>.
     */
    public void setRelativePath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.FOLDER.RELATIVE_PATH</code>.
     */
    public String getRelativePath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.FOLDER.NAME</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.FOLDER.NAME</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FolderRecord
     */
    public FolderRecord() {
        super(Folder.FOLDER);
    }

    /**
     * Create a detached, initialised FolderRecord
     */
    public FolderRecord(Long id, Long importRootId, Long parentFolderId, String relativePath, String name) {
        super(Folder.FOLDER);

        setId(id);
        setImportRootId(importRootId);
        setParentFolderId(parentFolderId);
        setRelativePath(relativePath);
        setName(name);
        resetChangedOnNotNull();
    }
}
