/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.ImportRoot;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.19.28",
                "schema version:none"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ImportRootRecord extends UpdatableRecordImpl<ImportRootRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.IMPORT_ROOT.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.IMPORT_ROOT.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.IMPORT_ROOT.PATH</code>.
     */
    public void setPath(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.IMPORT_ROOT.PATH</code>.
     */
    public String getPath() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.IMPORT_ROOT.CREATED_AT</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.IMPORT_ROOT.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.IMPORT_ROOT.LAST_SCANNED_AT</code>.
     */
    public void setLastScannedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.IMPORT_ROOT.LAST_SCANNED_AT</code>.
     */
    public LocalDateTime getLastScannedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImportRootRecord
     */
    public ImportRootRecord() {
        super(ImportRoot.IMPORT_ROOT);
    }

    /**
     * Create a detached, initialised ImportRootRecord
     */
    public ImportRootRecord(Long id, String path, LocalDateTime createdAt, LocalDateTime lastScannedAt) {
        super(ImportRoot.IMPORT_ROOT);

        setId(id);
        setPath(path);
        setCreatedAt(createdAt);
        setLastScannedAt(lastScannedAt);
        resetChangedOnNotNull();
    }
}
