/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.MediaHash;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaHashRecord extends UpdatableRecordImpl<MediaHashRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.MEDIA_HASH.MEDIA_ID</code>.
     */
    public void setMediaId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.MEDIA_HASH.MEDIA_ID</code>.
     */
    public Long getMediaId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.MEDIA_HASH.HASH_TYPE</code>.
     */
    public void setHashType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.MEDIA_HASH.HASH_TYPE</code>.
     */
    public String getHashType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.MEDIA_HASH.CONTENT_HASH</code>.
     */
    public void setContentHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.MEDIA_HASH.CONTENT_HASH</code>.
     */
    public String getContentHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.MEDIA_HASH.HASHED_FILE_SIZE</code>.
     */
    public void setHashedFileSize(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.MEDIA_HASH.HASHED_FILE_SIZE</code>.
     */
    public Long getHashedFileSize() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.MEDIA_HASH.HASHED_AT</code>.
     */
    public void setHashedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.MEDIA_HASH.HASHED_AT</code>.
     */
    public LocalDateTime getHashedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaHashRecord
     */
    public MediaHashRecord() {
        super(MediaHash.MEDIA_HASH);
    }

    /**
     * Create a detached, initialised MediaHashRecord
     */
    public MediaHashRecord(Long mediaId, String hashType, String contentHash, Long hashedFileSize, LocalDateTime hashedAt) {
        super(MediaHash.MEDIA_HASH);

        setMediaId(mediaId);
        setHashType(hashType);
        setContentHash(contentHash);
        setHashedFileSize(hashedFileSize);
        setHashedAt(hashedAt);
        resetChangedOnNotNull();
    }
}
