/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.Media;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaRecord extends UpdatableRecordImpl<MediaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.MEDIA.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.MEDIA.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.MEDIA.MEDIA_TYPE</code>.
     */
    public void setMediaType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.MEDIA.MEDIA_TYPE</code>.
     */
    public String getMediaType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.MEDIA.FOLDER_ID</code>.
     */
    public void setFolderId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.MEDIA.FOLDER_ID</code>.
     */
    public Long getFolderId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.MEDIA.ABSOLUTE_PATH</code>.
     */
    public void setAbsolutePath(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.MEDIA.ABSOLUTE_PATH</code>.
     */
    public String getAbsolutePath() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.MEDIA.FILENAME</code>.
     */
    public void setFilename(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.MEDIA.FILENAME</code>.
     */
    public String getFilename() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.MEDIA.EXTENSION</code>.
     */
    public void setExtension(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.MEDIA.EXTENSION</code>.
     */
    public String getExtension() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.MEDIA.FILE_SIZE</code>.
     */
    public void setFileSize(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.MEDIA.FILE_SIZE</code>.
     */
    public Long getFileSize() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.MEDIA.WIDTH</code>.
     */
    public void setWidth(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.MEDIA.WIDTH</code>.
     */
    public Integer getWidth() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.MEDIA.HEIGHT</code>.
     */
    public void setHeight(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.MEDIA.HEIGHT</code>.
     */
    public Integer getHeight() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.MEDIA.CAPTURE_DATE</code>.
     */
    public void setCaptureDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.MEDIA.CAPTURE_DATE</code>.
     */
    public LocalDateTime getCaptureDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.MEDIA.CAPTURE_DATE_SOURCE</code>.
     */
    public void setCaptureDateSource(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.MEDIA.CAPTURE_DATE_SOURCE</code>.
     */
    public String getCaptureDateSource() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.MEDIA.IMPORTED_AT</code>.
     */
    public void setImportedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.MEDIA.IMPORTED_AT</code>.
     */
    public LocalDateTime getImportedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.MEDIA.LAST_SEEN_AT</code>.
     */
    public void setLastSeenAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.MEDIA.LAST_SEEN_AT</code>.
     */
    public LocalDateTime getLastSeenAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.MEDIA.CAMERA_MAKE</code>.
     */
    public void setCameraMake(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.MEDIA.CAMERA_MAKE</code>.
     */
    public String getCameraMake() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.MEDIA.CAMERA_MODEL</code>.
     */
    public void setCameraModel(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.MEDIA.CAMERA_MODEL</code>.
     */
    public String getCameraModel() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.MEDIA.GPS_LAT</code>.
     */
    public void setGpsLat(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.MEDIA.GPS_LAT</code>.
     */
    public Double getGpsLat() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>public.MEDIA.GPS_LON</code>.
     */
    public void setGpsLon(Double value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.MEDIA.GPS_LON</code>.
     */
    public Double getGpsLon() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>public.MEDIA.GPS_ALTITUDE</code>.
     */
    public void setGpsAltitude(Double value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.MEDIA.GPS_ALTITUDE</code>.
     */
    public Double getGpsAltitude() {
        return (Double) get(17);
    }

    /**
     * Setter for <code>public.MEDIA.AI_FACE_DETECT_DONE</code>.
     */
    public void setAiFaceDetectDone(Boolean value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.MEDIA.AI_FACE_DETECT_DONE</code>.
     */
    public Boolean getAiFaceDetectDone() {
        return (Boolean) get(18);
    }

    /**
     * Setter for <code>public.MEDIA.AI_FACE_EMBED_DONE</code>.
     */
    public void setAiFaceEmbedDone(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.MEDIA.AI_FACE_EMBED_DONE</code>.
     */
    public Boolean getAiFaceEmbedDone() {
        return (Boolean) get(19);
    }

    /**
     * Setter for <code>public.MEDIA.AI_CLIP_EMBED_DONE</code>.
     */
    public void setAiClipEmbedDone(Boolean value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.MEDIA.AI_CLIP_EMBED_DONE</code>.
     */
    public Boolean getAiClipEmbedDone() {
        return (Boolean) get(20);
    }

    /**
     * Setter for <code>public.MEDIA.AI_TAG_DONE</code>.
     */
    public void setAiTagDone(Boolean value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.MEDIA.AI_TAG_DONE</code>.
     */
    public Boolean getAiTagDone() {
        return (Boolean) get(21);
    }

    /**
     * Setter for <code>public.MEDIA.AI_LUCENE_INDEX_DONE</code>.
     */
    public void setAiLuceneIndexDone(Boolean value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.MEDIA.AI_LUCENE_INDEX_DONE</code>.
     */
    public Boolean getAiLuceneIndexDone() {
        return (Boolean) get(22);
    }

    /**
     * Setter for <code>public.MEDIA.AI_LAST_ERROR</code>.
     */
    public void setAiLastError(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.MEDIA.AI_LAST_ERROR</code>.
     */
    public String getAiLastError() {
        return (String) get(23);
    }

    /**
     * Setter for <code>public.MEDIA.AI_RETRY_COUNT</code>.
     */
    public void setAiRetryCount(Short value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.MEDIA.AI_RETRY_COUNT</code>.
     */
    public Short getAiRetryCount() {
        return (Short) get(24);
    }

    /**
     * Setter for <code>public.MEDIA.AI_UPDATED_AT</code>.
     */
    public void setAiUpdatedAt(LocalDateTime value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.MEDIA.AI_UPDATED_AT</code>.
     */
    public LocalDateTime getAiUpdatedAt() {
        return (LocalDateTime) get(25);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaRecord
     */
    public MediaRecord() {
        super(Media.MEDIA);
    }

    /**
     * Create a detached, initialised MediaRecord
     */
    public MediaRecord(Long id, String mediaType, Long folderId, String absolutePath, String filename, String extension, Long fileSize, Integer width, Integer height, LocalDateTime captureDate, String captureDateSource, LocalDateTime importedAt, LocalDateTime lastSeenAt, String cameraMake, String cameraModel, Double gpsLat, Double gpsLon, Double gpsAltitude, Boolean aiFaceDetectDone, Boolean aiFaceEmbedDone, Boolean aiClipEmbedDone, Boolean aiTagDone, Boolean aiLuceneIndexDone, String aiLastError, Short aiRetryCount, LocalDateTime aiUpdatedAt) {
        super(Media.MEDIA);

        setId(id);
        setMediaType(mediaType);
        setFolderId(folderId);
        setAbsolutePath(absolutePath);
        setFilename(filename);
        setExtension(extension);
        setFileSize(fileSize);
        setWidth(width);
        setHeight(height);
        setCaptureDate(captureDate);
        setCaptureDateSource(captureDateSource);
        setImportedAt(importedAt);
        setLastSeenAt(lastSeenAt);
        setCameraMake(cameraMake);
        setCameraModel(cameraModel);
        setGpsLat(gpsLat);
        setGpsLon(gpsLon);
        setGpsAltitude(gpsAltitude);
        setAiFaceDetectDone(aiFaceDetectDone);
        setAiFaceEmbedDone(aiFaceEmbedDone);
        setAiClipEmbedDone(aiClipEmbedDone);
        setAiTagDone(aiTagDone);
        setAiLuceneIndexDone(aiLuceneIndexDone);
        setAiLastError(aiLastError);
        setAiRetryCount(aiRetryCount);
        setAiUpdatedAt(aiUpdatedAt);
        resetChangedOnNotNull();
    }
}
