/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.MediaTag;

import javax.annotation.processing.Generated;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaTagRecord extends UpdatableRecordImpl<MediaTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.MEDIA_TAG.TAG_ID</code>.
     */
    public void setTagId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.MEDIA_TAG.TAG_ID</code>.
     */
    public Long getTagId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.MEDIA_TAG.MEDIA_ID</code>.
     */
    public void setMediaId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.MEDIA_TAG.MEDIA_ID</code>.
     */
    public Long getMediaId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.MEDIA_TAG.TAG_SOURCE</code>.
     */
    public void setTagSource(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.MEDIA_TAG.TAG_SOURCE</code>.
     */
    public String getTagSource() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.MEDIA_TAG.CONFIDENCE</code>.
     */
    public void setConfidence(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.MEDIA_TAG.CONFIDENCE</code>.
     */
    public Double getConfidence() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediaTagRecord
     */
    public MediaTagRecord() {
        super(MediaTag.MEDIA_TAG);
    }

    /**
     * Create a detached, initialised MediaTagRecord
     */
    public MediaTagRecord(Long tagId, Long mediaId, String tagSource, Double confidence) {
        super(MediaTag.MEDIA_TAG);

        setTagId(tagId);
        setMediaId(mediaId);
        setTagSource(tagSource);
        setConfidence(confidence);
        resetChangedOnNotNull();
    }
}
