/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.Photo;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PhotoRecord extends UpdatableRecordImpl<PhotoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.PHOTO.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.PHOTO.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.PHOTO.FOLDER_ID</code>.
     */
    public void setFolderId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.PHOTO.FOLDER_ID</code>.
     */
    public Long getFolderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.PHOTO.ABSOLUTE_PATH</code>.
     */
    public void setAbsolutePath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.PHOTO.ABSOLUTE_PATH</code>.
     */
    public String getAbsolutePath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.PHOTO.FILENAME</code>.
     */
    public void setFilename(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.PHOTO.FILENAME</code>.
     */
    public String getFilename() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.PHOTO.EXTENSION</code>.
     */
    public void setExtension(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.PHOTO.EXTENSION</code>.
     */
    public String getExtension() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.PHOTO.FILE_SIZE</code>.
     */
    public void setFileSize(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.PHOTO.FILE_SIZE</code>.
     */
    public Long getFileSize() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.PHOTO.IMAGE_WIDTH</code>.
     */
    public void setImageWidth(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.PHOTO.IMAGE_WIDTH</code>.
     */
    public Integer getImageWidth() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.PHOTO.IMAGE_HEIGHT</code>.
     */
    public void setImageHeight(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.PHOTO.IMAGE_HEIGHT</code>.
     */
    public Integer getImageHeight() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.PHOTO.CAPTURE_DATE</code>.
     */
    public void setCaptureDate(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.PHOTO.CAPTURE_DATE</code>.
     */
    public LocalDateTime getCaptureDate() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.PHOTO.CAPTURE_DATE_SOURCE</code>.
     */
    public void setCaptureDateSource(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.PHOTO.CAPTURE_DATE_SOURCE</code>.
     */
    public String getCaptureDateSource() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.PHOTO.IMPORTED_AT</code>.
     */
    public void setImportedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.PHOTO.IMPORTED_AT</code>.
     */
    public LocalDateTime getImportedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.PHOTO.LAST_SEEN_AT</code>.
     */
    public void setLastSeenAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.PHOTO.LAST_SEEN_AT</code>.
     */
    public LocalDateTime getLastSeenAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.PHOTO.ORIENTATION</code>.
     */
    public void setOrientation(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.PHOTO.ORIENTATION</code>.
     */
    public Integer getOrientation() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.PHOTO.CAMERA_MAKE</code>.
     */
    public void setCameraMake(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.PHOTO.CAMERA_MAKE</code>.
     */
    public String getCameraMake() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.PHOTO.CAMERA_MODEL</code>.
     */
    public void setCameraModel(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.PHOTO.CAMERA_MODEL</code>.
     */
    public String getCameraModel() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.PHOTO.LENS_MODEL</code>.
     */
    public void setLensModel(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.PHOTO.LENS_MODEL</code>.
     */
    public String getLensModel() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.PHOTO.EXIF_EXTRA</code>.
     */
    public void setExifExtra(JSON value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.PHOTO.EXIF_EXTRA</code>.
     */
    public JSON getExifExtra() {
        return (JSON) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhotoRecord
     */
    public PhotoRecord() {
        super(Photo.PHOTO);
    }

    /**
     * Create a detached, initialised PhotoRecord
     */
    public PhotoRecord(Long id, Long folderId, String absolutePath, String filename, String extension, Long fileSize, Integer imageWidth, Integer imageHeight, LocalDateTime captureDate, String captureDateSource, LocalDateTime importedAt, LocalDateTime lastSeenAt, Integer orientation, String cameraMake, String cameraModel, String lensModel, JSON exifExtra) {
        super(Photo.PHOTO);

        setId(id);
        setFolderId(folderId);
        setAbsolutePath(absolutePath);
        setFilename(filename);
        setExtension(extension);
        setFileSize(fileSize);
        setImageWidth(imageWidth);
        setImageHeight(imageHeight);
        setCaptureDate(captureDate);
        setCaptureDateSource(captureDateSource);
        setImportedAt(importedAt);
        setLastSeenAt(lastSeenAt);
        setOrientation(orientation);
        setCameraMake(cameraMake);
        setCameraModel(cameraModel);
        setLensModel(lensModel);
        setExifExtra(exifExtra);
        resetChangedOnNotNull();
    }
}
