/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.Photo;

import javax.annotation.processing.Generated;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PhotoRecord extends UpdatableRecordImpl<PhotoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.PHOTO.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.PHOTO.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.PHOTO.ORIENTATION</code>.
     */
    public void setOrientation(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.PHOTO.ORIENTATION</code>.
     */
    public Integer getOrientation() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.PHOTO.LENS_MODEL</code>.
     */
    public void setLensModel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.PHOTO.LENS_MODEL</code>.
     */
    public String getLensModel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.PHOTO.EXIF_EXTRA</code>.
     */
    public void setExifExtra(JSON value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.PHOTO.EXIF_EXTRA</code>.
     */
    public JSON getExifExtra() {
        return (JSON) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhotoRecord
     */
    public PhotoRecord() {
        super(Photo.PHOTO);
    }

    /**
     * Create a detached, initialised PhotoRecord
     */
    public PhotoRecord(Long id, Integer orientation, String lensModel, JSON exifExtra) {
        super(Photo.PHOTO);

        setId(id);
        setOrientation(orientation);
        setLensModel(lensModel);
        setExifExtra(exifExtra);
        resetChangedOnNotNull();
    }
}
