/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.PhotoPreview;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PhotoPreviewRecord extends UpdatableRecordImpl<PhotoPreviewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.PHOTO_PREVIEW.PHOTO_ID</code>.
     */
    public void setPhotoId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.PHOTO_PREVIEW.PHOTO_ID</code>.
     */
    public Long getPhotoId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.PHOTO_PREVIEW.BYTES</code>.
     */
    public void setBytes(byte[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.PHOTO_PREVIEW.BYTES</code>.
     */
    public byte[] getBytes() {
        return (byte[]) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhotoPreviewRecord
     */
    public PhotoPreviewRecord() {
        super(PhotoPreview.PHOTO_PREVIEW);
    }

    /**
     * Create a detached, initialised PhotoPreviewRecord
     */
    public PhotoPreviewRecord(Long photoId, byte[] bytes) {
        super(PhotoPreview.PHOTO_PREVIEW);

        setPhotoId(photoId);
        setBytes(bytes);
        resetChangedOnNotNull();
    }
}
