/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.PhotoHash;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PhotoHashRecord extends UpdatableRecordImpl<PhotoHashRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.PHOTO_HASH.PHOTO_ID</code>.
     */
    public void setPhotoId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.PHOTO_HASH.PHOTO_ID</code>.
     */
    public Long getPhotoId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.PHOTO_HASH.PIXEL_HASH</code>.
     */
    public void setPixelHash(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.PHOTO_HASH.PIXEL_HASH</code>.
     */
    public String getPixelHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.PHOTO_HASH.HASHED_FILE_SIZE</code>.
     */
    public void setHashedFileSize(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.PHOTO_HASH.HASHED_FILE_SIZE</code>.
     */
    public Long getHashedFileSize() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.PHOTO_HASH.HASHED_AT</code>.
     */
    public void setHashedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.PHOTO_HASH.HASHED_AT</code>.
     */
    public LocalDateTime getHashedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhotoHashRecord
     */
    public PhotoHashRecord() {
        super(PhotoHash.PHOTO_HASH);
    }

    /**
     * Create a detached, initialised PhotoHashRecord
     */
    public PhotoHashRecord(Long photoId, String pixelHash, Long hashedFileSize, LocalDateTime hashedAt) {
        super(PhotoHash.PHOTO_HASH);

        setPhotoId(photoId);
        setPixelHash(pixelHash);
        setHashedFileSize(hashedFileSize);
        setHashedAt(hashedAt);
        resetChangedOnNotNull();
    }
}
