/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.TagEmbedding;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TagEmbeddingRecord extends UpdatableRecordImpl<TagEmbeddingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.TAG_EMBEDDING.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.TAG_EMBEDDING.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.TAG_EMBEDDING.CATEGORY</code>.
     */
    public void setCategory(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.TAG_EMBEDDING.CATEGORY</code>.
     */
    public String getCategory() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.TAG_EMBEDDING.TAG</code>.
     */
    public void setTag(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.TAG_EMBEDDING.TAG</code>.
     */
    public String getTag() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.TAG_EMBEDDING.EMBEDDING</code>.
     */
    public void setEmbedding(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.TAG_EMBEDDING.EMBEDDING</code>.
     */
    public byte[] getEmbedding() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>public.TAG_EMBEDDING.MODEL_VER</code>.
     */
    public void setModelVer(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.TAG_EMBEDDING.MODEL_VER</code>.
     */
    public String getModelVer() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagEmbeddingRecord
     */
    public TagEmbeddingRecord() {
        super(TagEmbedding.TAG_EMBEDDING);
    }

    /**
     * Create a detached, initialised TagEmbeddingRecord
     */
    public TagEmbeddingRecord(Long id, String category, String tag, byte[] embedding, String modelVer) {
        super(TagEmbedding.TAG_EMBEDDING);

        setId(id);
        setCategory(category);
        setTag(tag);
        setEmbedding(embedding);
        setModelVer(modelVer);
        resetChangedOnNotNull();
    }
}
