/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.UserPreferences;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.19.28",
                "schema version:none"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class UserPreferencesRecord extends UpdatableRecordImpl<UserPreferencesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.USER_PREFERENCES.PREF_KEY</code>.
     */
    public void setPrefKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.USER_PREFERENCES.PREF_KEY</code>.
     */
    public String getPrefKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.USER_PREFERENCES.PREF_VALUE</code>.
     */
    public void setPrefValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.USER_PREFERENCES.PREF_VALUE</code>.
     */
    public String getPrefValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPreferencesRecord
     */
    public UserPreferencesRecord() {
        super(UserPreferences.USER_PREFERENCES);
    }

    /**
     * Create a detached, initialised UserPreferencesRecord
     */
    public UserPreferencesRecord(String prefKey, String prefValue) {
        super(UserPreferences.USER_PREFERENCES);

        setPrefKey(prefKey);
        setPrefValue(prefValue);
        resetChangedOnNotNull();
    }
}
