/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables.records;


import com.github.curiousoddman.curious_images.dbobj.tables.Video;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VideoRecord extends UpdatableRecordImpl<VideoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.VIDEO.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.VIDEO.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.VIDEO.DURATION_MS</code>.
     */
    public void setDurationMs(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.VIDEO.DURATION_MS</code>.
     */
    public Long getDurationMs() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.VIDEO.CODEC</code>.
     */
    public void setCodec(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.VIDEO.CODEC</code>.
     */
    public String getCodec() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.VIDEO.FRAME_RATE</code>.
     */
    public void setFrameRate(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.VIDEO.FRAME_RATE</code>.
     */
    public Double getFrameRate() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.VIDEO.ROTATION</code>.
     */
    public void setRotation(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.VIDEO.ROTATION</code>.
     */
    public Integer getRotation() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VideoRecord
     */
    public VideoRecord() {
        super(Video.VIDEO);
    }

    /**
     * Create a detached, initialised VideoRecord
     */
    public VideoRecord(Long id, Long durationMs, String codec, Double frameRate, Integer rotation) {
        super(Video.VIDEO);

        setId(id);
        setDurationMs(durationMs);
        setCodec(codec);
        setFrameRate(frameRate);
        setRotation(rotation);
        resetChangedOnNotNull();
    }
}
