/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.AlbumPhoto.AlbumPhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo.PhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.AlbumRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Album extends TableImpl<AlbumRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ALBUM</code>
     */
    public static final Album ALBUM = new Album();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlbumRecord> getRecordType() {
        return AlbumRecord.class;
    }

    /**
     * The column <code>public.ALBUM.ID</code>.
     */
    public final TableField<AlbumRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.ALBUM.NAME</code>.
     */
    public final TableField<AlbumRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>public.ALBUM.TYPE</code>.
     */
    public final TableField<AlbumRecord, String> TYPE = createField(DSL.name("TYPE"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.ALBUM.COVER_PHOTO_ID</code>.
     */
    public final TableField<AlbumRecord, Long> COVER_PHOTO_ID = createField(DSL.name("COVER_PHOTO_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.ALBUM.CREATED_AT</code>.
     */
    public final TableField<AlbumRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.ALBUM.UPDATED_AT</code>.
     */
    public final TableField<AlbumRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.ALBUM.META_JSON</code>.
     */
    public final TableField<AlbumRecord, String> META_JSON = createField(DSL.name("META_JSON"), SQLDataType.VARCHAR, this, "");

    private Album(Name alias, Table<AlbumRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Album(Name alias, Table<AlbumRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ALBUM</code> table reference
     */
    public Album(String alias) {
        this(DSL.name(alias), ALBUM);
    }

    /**
     * Create an aliased <code>public.ALBUM</code> table reference
     */
    public Album(Name alias) {
        this(alias, ALBUM);
    }

    /**
     * Create a <code>public.ALBUM</code> table reference
     */
    public Album() {
        this(DSL.name("ALBUM"), null);
    }

    public <O extends Record> Album(Table<O> path, ForeignKey<O, AlbumRecord> childPath, InverseForeignKey<O, AlbumRecord> parentPath) {
        super(path, childPath, parentPath, ALBUM);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class AlbumPath extends Album implements Path<AlbumRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AlbumPath(Table<O> path, ForeignKey<O, AlbumRecord> childPath, InverseForeignKey<O, AlbumRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AlbumPath(Name alias, Table<AlbumRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AlbumPath as(String alias) {
            return new AlbumPath(DSL.name(alias), this);
        }

        @Override
        public AlbumPath as(Name alias) {
            return new AlbumPath(alias, this);
        }

        @Override
        public AlbumPath as(Table<?> alias) {
            return new AlbumPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ALBUM_TYPE);
    }

    @Override
    public Identity<AlbumRecord, Long> getIdentity() {
        return (Identity<AlbumRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AlbumRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3;
    }

    @Override
    public List<ForeignKey<AlbumRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_3B);
    }

    private transient PhotoPath _photo;

    /**
     * Get the implicit join path to the <code>public.PHOTO</code> table.
     */
    public PhotoPath photo() {
        if (_photo == null)
            _photo = new PhotoPath(this, Keys.CONSTRAINT_3B, null);

        return _photo;
    }

    private transient AlbumPhotoPath _albumPhoto;

    /**
     * Get the implicit to-many join path to the <code>public.ALBUM_PHOTO</code>
     * table
     */
    public AlbumPhotoPath albumPhoto() {
        if (_albumPhoto == null)
            _albumPhoto = new AlbumPhotoPath(this, null, Keys.CONSTRAINT_9B.getInverseKey());

        return _albumPhoto;
    }

    @Override
    public Album as(String alias) {
        return new Album(DSL.name(alias), this);
    }

    @Override
    public Album as(Name alias) {
        return new Album(alias, this);
    }

    @Override
    public Album as(Table<?> alias) {
        return new Album(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Album rename(String name) {
        return new Album(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Album rename(Name name) {
        return new Album(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Album rename(Table<?> name) {
        return new Album(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album where(Condition condition) {
        return new Album(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Album where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Album where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Album where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Album where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Album whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
