/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Album.AlbumPath;
import com.github.curiousoddman.curious_images.dbobj.tables.Media.MediaPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.AlbumMediaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AlbumMedia extends TableImpl<AlbumMediaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ALBUM_MEDIA</code>
     */
    public static final AlbumMedia ALBUM_MEDIA = new AlbumMedia();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlbumMediaRecord> getRecordType() {
        return AlbumMediaRecord.class;
    }

    /**
     * The column <code>public.ALBUM_MEDIA.ALBUM_ID</code>.
     */
    public final TableField<AlbumMediaRecord, Long> ALBUM_ID = createField(DSL.name("ALBUM_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ALBUM_MEDIA.MEDIA_ID</code>.
     */
    public final TableField<AlbumMediaRecord, Long> MEDIA_ID = createField(DSL.name("MEDIA_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ALBUM_MEDIA.SORT_ORDER</code>.
     */
    public final TableField<AlbumMediaRecord, Integer> SORT_ORDER = createField(DSL.name("SORT_ORDER"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.ALBUM_MEDIA.ADDED_AT</code>.
     */
    public final TableField<AlbumMediaRecord, LocalDateTime> ADDED_AT = createField(DSL.name("ADDED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private AlbumMedia(Name alias, Table<AlbumMediaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AlbumMedia(Name alias, Table<AlbumMediaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ALBUM_MEDIA</code> table reference
     */
    public AlbumMedia(String alias) {
        this(DSL.name(alias), ALBUM_MEDIA);
    }

    /**
     * Create an aliased <code>public.ALBUM_MEDIA</code> table reference
     */
    public AlbumMedia(Name alias) {
        this(alias, ALBUM_MEDIA);
    }

    /**
     * Create a <code>public.ALBUM_MEDIA</code> table reference
     */
    public AlbumMedia() {
        this(DSL.name("ALBUM_MEDIA"), null);
    }

    public <O extends Record> AlbumMedia(Table<O> path, ForeignKey<O, AlbumMediaRecord> childPath, InverseForeignKey<O, AlbumMediaRecord> parentPath) {
        super(path, childPath, parentPath, ALBUM_MEDIA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class AlbumMediaPath extends AlbumMedia implements Path<AlbumMediaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AlbumMediaPath(Table<O> path, ForeignKey<O, AlbumMediaRecord> childPath, InverseForeignKey<O, AlbumMediaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AlbumMediaPath(Name alias, Table<AlbumMediaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AlbumMediaPath as(String alias) {
            return new AlbumMediaPath(DSL.name(alias), this);
        }

        @Override
        public AlbumMediaPath as(Name alias) {
            return new AlbumMediaPath(alias, this);
        }

        @Override
        public AlbumMediaPath as(Table<?> alias) {
            return new AlbumMediaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ALBUM_MEDIA_ALBUM, Indexes.IDX_ALBUM_MEDIA_MEDIA);
    }

    @Override
    public UniqueKey<AlbumMediaRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9B01;
    }

    @Override
    public List<ForeignKey<AlbumMediaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_9B, Keys.CONSTRAINT_9B0);
    }

    private transient AlbumPath _album;

    /**
     * Get the implicit join path to the <code>public.ALBUM</code> table.
     */
    public AlbumPath album() {
        if (_album == null)
            _album = new AlbumPath(this, Keys.CONSTRAINT_9B, null);

        return _album;
    }

    private transient MediaPath _media;

    /**
     * Get the implicit join path to the <code>public.MEDIA</code> table.
     */
    public MediaPath media() {
        if (_media == null)
            _media = new MediaPath(this, Keys.CONSTRAINT_9B0, null);

        return _media;
    }

    @Override
    public AlbumMedia as(String alias) {
        return new AlbumMedia(DSL.name(alias), this);
    }

    @Override
    public AlbumMedia as(Name alias) {
        return new AlbumMedia(alias, this);
    }

    @Override
    public AlbumMedia as(Table<?> alias) {
        return new AlbumMedia(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumMedia rename(String name) {
        return new AlbumMedia(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumMedia rename(Name name) {
        return new AlbumMedia(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumMedia rename(Table<?> name) {
        return new AlbumMedia(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumMedia where(Condition condition) {
        return new AlbumMedia(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumMedia where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumMedia where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumMedia where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumMedia where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumMedia where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumMedia where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumMedia where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumMedia whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumMedia whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
