/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Album.AlbumPath;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo.PhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.AlbumPhotoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AlbumPhoto extends TableImpl<AlbumPhotoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ALBUM_PHOTO</code>
     */
    public static final AlbumPhoto ALBUM_PHOTO = new AlbumPhoto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlbumPhotoRecord> getRecordType() {
        return AlbumPhotoRecord.class;
    }

    /**
     * The column <code>public.ALBUM_PHOTO.ALBUM_ID</code>.
     */
    public final TableField<AlbumPhotoRecord, Long> ALBUM_ID = createField(DSL.name("ALBUM_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ALBUM_PHOTO.PHOTO_ID</code>.
     */
    public final TableField<AlbumPhotoRecord, Long> PHOTO_ID = createField(DSL.name("PHOTO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.ALBUM_PHOTO.SORT_ORDER</code>.
     */
    public final TableField<AlbumPhotoRecord, Integer> SORT_ORDER = createField(DSL.name("SORT_ORDER"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.ALBUM_PHOTO.ADDED_AT</code>.
     */
    public final TableField<AlbumPhotoRecord, LocalDateTime> ADDED_AT = createField(DSL.name("ADDED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private AlbumPhoto(Name alias, Table<AlbumPhotoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AlbumPhoto(Name alias, Table<AlbumPhotoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.ALBUM_PHOTO</code> table reference
     */
    public AlbumPhoto(String alias) {
        this(DSL.name(alias), ALBUM_PHOTO);
    }

    /**
     * Create an aliased <code>public.ALBUM_PHOTO</code> table reference
     */
    public AlbumPhoto(Name alias) {
        this(alias, ALBUM_PHOTO);
    }

    /**
     * Create a <code>public.ALBUM_PHOTO</code> table reference
     */
    public AlbumPhoto() {
        this(DSL.name("ALBUM_PHOTO"), null);
    }

    public <O extends Record> AlbumPhoto(Table<O> path, ForeignKey<O, AlbumPhotoRecord> childPath, InverseForeignKey<O, AlbumPhotoRecord> parentPath) {
        super(path, childPath, parentPath, ALBUM_PHOTO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class AlbumPhotoPath extends AlbumPhoto implements Path<AlbumPhotoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AlbumPhotoPath(Table<O> path, ForeignKey<O, AlbumPhotoRecord> childPath, InverseForeignKey<O, AlbumPhotoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AlbumPhotoPath(Name alias, Table<AlbumPhotoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AlbumPhotoPath as(String alias) {
            return new AlbumPhotoPath(DSL.name(alias), this);
        }

        @Override
        public AlbumPhotoPath as(Name alias) {
            return new AlbumPhotoPath(alias, this);
        }

        @Override
        public AlbumPhotoPath as(Table<?> alias) {
            return new AlbumPhotoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ALBUM_PHOTO_ALBUM, Indexes.IDX_ALBUM_PHOTO_PHOTO);
    }

    @Override
    public UniqueKey<AlbumPhotoRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9B2C;
    }

    @Override
    public List<ForeignKey<AlbumPhotoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_9B, Keys.CONSTRAINT_9B2);
    }

    private transient AlbumPath _album;

    /**
     * Get the implicit join path to the <code>public.ALBUM</code> table.
     */
    public AlbumPath album() {
        if (_album == null)
            _album = new AlbumPath(this, Keys.CONSTRAINT_9B, null);

        return _album;
    }

    private transient PhotoPath _photo;

    /**
     * Get the implicit join path to the <code>public.PHOTO</code> table.
     */
    public PhotoPath photo() {
        if (_photo == null)
            _photo = new PhotoPath(this, Keys.CONSTRAINT_9B2, null);

        return _photo;
    }

    @Override
    public AlbumPhoto as(String alias) {
        return new AlbumPhoto(DSL.name(alias), this);
    }

    @Override
    public AlbumPhoto as(Name alias) {
        return new AlbumPhoto(alias, this);
    }

    @Override
    public AlbumPhoto as(Table<?> alias) {
        return new AlbumPhoto(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumPhoto rename(String name) {
        return new AlbumPhoto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumPhoto rename(Name name) {
        return new AlbumPhoto(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AlbumPhoto rename(Table<?> name) {
        return new AlbumPhoto(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumPhoto where(Condition condition) {
        return new AlbumPhoto(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumPhoto where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumPhoto where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumPhoto where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumPhoto where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumPhoto where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumPhoto where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AlbumPhoto where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumPhoto whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AlbumPhoto whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
