/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo.PhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.ClipEmbeddingRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClipEmbedding extends TableImpl<ClipEmbeddingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.CLIP_EMBEDDING</code>
     */
    public static final ClipEmbedding CLIP_EMBEDDING = new ClipEmbedding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClipEmbeddingRecord> getRecordType() {
        return ClipEmbeddingRecord.class;
    }

    /**
     * The column <code>public.CLIP_EMBEDDING.PHOTO_ID</code>.
     */
    public final TableField<ClipEmbeddingRecord, Long> PHOTO_ID = createField(DSL.name("PHOTO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.CLIP_EMBEDDING.EMBEDDING</code>.
     */
    public final TableField<ClipEmbeddingRecord, byte[]> EMBEDDING = createField(DSL.name("EMBEDDING"), SQLDataType.BINARY(2048).nullable(false), this, "");

    /**
     * The column <code>public.CLIP_EMBEDDING.MODEL_VER</code>.
     */
    public final TableField<ClipEmbeddingRecord, String> MODEL_VER = createField(DSL.name("MODEL_VER"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    private ClipEmbedding(Name alias, Table<ClipEmbeddingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClipEmbedding(Name alias, Table<ClipEmbeddingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.CLIP_EMBEDDING</code> table reference
     */
    public ClipEmbedding(String alias) {
        this(DSL.name(alias), CLIP_EMBEDDING);
    }

    /**
     * Create an aliased <code>public.CLIP_EMBEDDING</code> table reference
     */
    public ClipEmbedding(Name alias) {
        this(alias, CLIP_EMBEDDING);
    }

    /**
     * Create a <code>public.CLIP_EMBEDDING</code> table reference
     */
    public ClipEmbedding() {
        this(DSL.name("CLIP_EMBEDDING"), null);
    }

    public <O extends Record> ClipEmbedding(Table<O> path, ForeignKey<O, ClipEmbeddingRecord> childPath, InverseForeignKey<O, ClipEmbeddingRecord> parentPath) {
        super(path, childPath, parentPath, CLIP_EMBEDDING);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class ClipEmbeddingPath extends ClipEmbedding implements Path<ClipEmbeddingRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClipEmbeddingPath(Table<O> path, ForeignKey<O, ClipEmbeddingRecord> childPath, InverseForeignKey<O, ClipEmbeddingRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClipEmbeddingPath(Name alias, Table<ClipEmbeddingRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClipEmbeddingPath as(String alias) {
            return new ClipEmbeddingPath(DSL.name(alias), this);
        }

        @Override
        public ClipEmbeddingPath as(Name alias) {
            return new ClipEmbeddingPath(alias, this);
        }

        @Override
        public ClipEmbeddingPath as(Table<?> alias) {
            return new ClipEmbeddingPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ClipEmbeddingRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9E;
    }

    @Override
    public List<ForeignKey<ClipEmbeddingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_9E7);
    }

    private transient PhotoPath _photo;

    /**
     * Get the implicit join path to the <code>public.PHOTO</code> table.
     */
    public PhotoPath photo() {
        if (_photo == null)
            _photo = new PhotoPath(this, Keys.CONSTRAINT_9E7, null);

        return _photo;
    }

    @Override
    public ClipEmbedding as(String alias) {
        return new ClipEmbedding(DSL.name(alias), this);
    }

    @Override
    public ClipEmbedding as(Name alias) {
        return new ClipEmbedding(alias, this);
    }

    @Override
    public ClipEmbedding as(Table<?> alias) {
        return new ClipEmbedding(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClipEmbedding rename(String name) {
        return new ClipEmbedding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClipEmbedding rename(Name name) {
        return new ClipEmbedding(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClipEmbedding rename(Table<?> name) {
        return new ClipEmbedding(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClipEmbedding where(Condition condition) {
        return new ClipEmbedding(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClipEmbedding where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClipEmbedding where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClipEmbedding where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClipEmbedding where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClipEmbedding where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClipEmbedding where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClipEmbedding where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClipEmbedding whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClipEmbedding whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
