/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Face.FacePath;
import com.github.curiousoddman.curious_images.dbobj.tables.Person.PersonPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.ClusterRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cluster extends TableImpl<ClusterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.CLUSTER</code>
     */
    public static final Cluster CLUSTER = new Cluster();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClusterRecord> getRecordType() {
        return ClusterRecord.class;
    }

    /**
     * The column <code>public.CLUSTER.ID</code>.
     */
    public final TableField<ClusterRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.CLUSTER.PERSON_ID</code>.
     */
    public final TableField<ClusterRecord, Long> PERSON_ID = createField(DSL.name("PERSON_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.CLUSTER.CENTROID_EMBEDDING</code>.
     */
    public final TableField<ClusterRecord, byte[]> CENTROID_EMBEDDING = createField(DSL.name("CENTROID_EMBEDDING"), SQLDataType.VARBINARY.nullable(false), this, "");

    /**
     * The column <code>public.CLUSTER.MEMBER_COUNT</code>.
     */
    public final TableField<ClusterRecord, Integer> MEMBER_COUNT = createField(DSL.name("MEMBER_COUNT"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.CLUSTER.CREATED_AT</code>.
     */
    public final TableField<ClusterRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.CLUSTER.UPDATED_AT</code>.
     */
    public final TableField<ClusterRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private Cluster(Name alias, Table<ClusterRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Cluster(Name alias, Table<ClusterRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.CLUSTER</code> table reference
     */
    public Cluster(String alias) {
        this(DSL.name(alias), CLUSTER);
    }

    /**
     * Create an aliased <code>public.CLUSTER</code> table reference
     */
    public Cluster(Name alias) {
        this(alias, CLUSTER);
    }

    /**
     * Create a <code>public.CLUSTER</code> table reference
     */
    public Cluster() {
        this(DSL.name("CLUSTER"), null);
    }

    public <O extends Record> Cluster(Table<O> path, ForeignKey<O, ClusterRecord> childPath, InverseForeignKey<O, ClusterRecord> parentPath) {
        super(path, childPath, parentPath, CLUSTER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class ClusterPath extends Cluster implements Path<ClusterRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClusterPath(Table<O> path, ForeignKey<O, ClusterRecord> childPath, InverseForeignKey<O, ClusterRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClusterPath(Name alias, Table<ClusterRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClusterPath as(String alias) {
            return new ClusterPath(DSL.name(alias), this);
        }

        @Override
        public ClusterPath as(Name alias) {
            return new ClusterPath(alias, this);
        }

        @Override
        public ClusterPath as(Table<?> alias) {
            return new ClusterPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CLUSTER_PERSON_ID);
    }

    @Override
    public Identity<ClusterRecord, Long> getIdentity() {
        return (Identity<ClusterRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ClusterRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_5;
    }

    @Override
    public List<ForeignKey<ClusterRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_5E);
    }

    private transient PersonPath _person;

    /**
     * Get the implicit join path to the <code>public.PERSON</code> table.
     */
    public PersonPath person() {
        if (_person == null)
            _person = new PersonPath(this, Keys.CONSTRAINT_5E, null);

        return _person;
    }

    private transient FacePath _face;

    /**
     * Get the implicit to-many join path to the <code>public.FACE</code> table
     */
    public FacePath face() {
        if (_face == null)
            _face = new FacePath(this, null, Keys.CONSTRAINT_20C.getInverseKey());

        return _face;
    }

    @Override
    public Cluster as(String alias) {
        return new Cluster(DSL.name(alias), this);
    }

    @Override
    public Cluster as(Name alias) {
        return new Cluster(alias, this);
    }

    @Override
    public Cluster as(Table<?> alias) {
        return new Cluster(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cluster rename(String name) {
        return new Cluster(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cluster rename(Name name) {
        return new Cluster(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cluster rename(Table<?> name) {
        return new Cluster(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cluster where(Condition condition) {
        return new Cluster(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cluster where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cluster where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cluster where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cluster where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cluster where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cluster where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cluster where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cluster whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cluster whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
