/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroup.DuplicateGroupPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.DuplicateJobRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DuplicateJob extends TableImpl<DuplicateJobRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.DUPLICATE_JOB</code>
     */
    public static final DuplicateJob DUPLICATE_JOB = new DuplicateJob();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DuplicateJobRecord> getRecordType() {
        return DuplicateJobRecord.class;
    }

    /**
     * The column <code>public.DUPLICATE_JOB.ID</code>.
     */
    public final TableField<DuplicateJobRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.DUPLICATE_JOB.STATUS</code>.
     */
    public final TableField<DuplicateJobRecord, String> STATUS = createField(DSL.name("STATUS"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.DUPLICATE_JOB.STARTED_AT</code>.
     */
    public final TableField<DuplicateJobRecord, LocalDateTime> STARTED_AT = createField(DSL.name("STARTED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.DUPLICATE_JOB.ENDED_AT</code>.
     */
    public final TableField<DuplicateJobRecord, LocalDateTime> ENDED_AT = createField(DSL.name("ENDED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.DUPLICATE_JOB.TOTAL_COUNT</code>.
     */
    public final TableField<DuplicateJobRecord, Integer> TOTAL_COUNT = createField(DSL.name("TOTAL_COUNT"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.DUPLICATE_JOB.PROCESSED_COUNT</code>.
     */
    public final TableField<DuplicateJobRecord, Integer> PROCESSED_COUNT = createField(DSL.name("PROCESSED_COUNT"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.DUPLICATE_JOB.GROUP_COUNT</code>.
     */
    public final TableField<DuplicateJobRecord, Integer> GROUP_COUNT = createField(DSL.name("GROUP_COUNT"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.DUPLICATE_JOB.ERROR_MESSAGE</code>.
     */
    public final TableField<DuplicateJobRecord, String> ERROR_MESSAGE = createField(DSL.name("ERROR_MESSAGE"), SQLDataType.VARCHAR(2048), this, "");

    private DuplicateJob(Name alias, Table<DuplicateJobRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DuplicateJob(Name alias, Table<DuplicateJobRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.DUPLICATE_JOB</code> table reference
     */
    public DuplicateJob(String alias) {
        this(DSL.name(alias), DUPLICATE_JOB);
    }

    /**
     * Create an aliased <code>public.DUPLICATE_JOB</code> table reference
     */
    public DuplicateJob(Name alias) {
        this(alias, DUPLICATE_JOB);
    }

    /**
     * Create a <code>public.DUPLICATE_JOB</code> table reference
     */
    public DuplicateJob() {
        this(DSL.name("DUPLICATE_JOB"), null);
    }

    public <O extends Record> DuplicateJob(Table<O> path, ForeignKey<O, DuplicateJobRecord> childPath, InverseForeignKey<O, DuplicateJobRecord> parentPath) {
        super(path, childPath, parentPath, DUPLICATE_JOB);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class DuplicateJobPath extends DuplicateJob implements Path<DuplicateJobRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DuplicateJobPath(Table<O> path, ForeignKey<O, DuplicateJobRecord> childPath, InverseForeignKey<O, DuplicateJobRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DuplicateJobPath(Name alias, Table<DuplicateJobRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DuplicateJobPath as(String alias) {
            return new DuplicateJobPath(DSL.name(alias), this);
        }

        @Override
        public DuplicateJobPath as(Name alias) {
            return new DuplicateJobPath(alias, this);
        }

        @Override
        public DuplicateJobPath as(Table<?> alias) {
            return new DuplicateJobPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DuplicateJobRecord, Long> getIdentity() {
        return (Identity<DuplicateJobRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DuplicateJobRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_6;
    }

    private transient DuplicateGroupPath _duplicateGroup;

    /**
     * Get the implicit to-many join path to the
     * <code>public.DUPLICATE_GROUP</code> table
     */
    public DuplicateGroupPath duplicateGroup() {
        if (_duplicateGroup == null)
            _duplicateGroup = new DuplicateGroupPath(this, null, Keys.CONSTRAINT_B6.getInverseKey());

        return _duplicateGroup;
    }

    @Override
    public DuplicateJob as(String alias) {
        return new DuplicateJob(DSL.name(alias), this);
    }

    @Override
    public DuplicateJob as(Name alias) {
        return new DuplicateJob(alias, this);
    }

    @Override
    public DuplicateJob as(Table<?> alias) {
        return new DuplicateJob(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DuplicateJob rename(String name) {
        return new DuplicateJob(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DuplicateJob rename(Name name) {
        return new DuplicateJob(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DuplicateJob rename(Table<?> name) {
        return new DuplicateJob(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateJob where(Condition condition) {
        return new DuplicateJob(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateJob where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateJob where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateJob where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DuplicateJob where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DuplicateJob where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DuplicateJob where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DuplicateJob where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateJob whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateJob whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
