/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroupMember.DuplicateGroupMemberPath;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateJob.DuplicateJobPath;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo.PhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.DuplicateGroupRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DuplicateGroup extends TableImpl<DuplicateGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.DUPLICATE_GROUP</code>
     */
    public static final DuplicateGroup DUPLICATE_GROUP = new DuplicateGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DuplicateGroupRecord> getRecordType() {
        return DuplicateGroupRecord.class;
    }

    /**
     * The column <code>public.DUPLICATE_GROUP.ID</code>.
     */
    public final TableField<DuplicateGroupRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.DUPLICATE_GROUP.DUPLICATE_JOB_ID</code>.
     */
    public final TableField<DuplicateGroupRecord, Long> DUPLICATE_JOB_ID = createField(DSL.name("DUPLICATE_JOB_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.DUPLICATE_GROUP.EXTENSION</code>.
     */
    public final TableField<DuplicateGroupRecord, String> EXTENSION = createField(DSL.name("EXTENSION"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.DUPLICATE_GROUP.PIXEL_HASH</code>.
     */
    public final TableField<DuplicateGroupRecord, String> PIXEL_HASH = createField(DSL.name("PIXEL_HASH"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.DUPLICATE_GROUP.CREATED_AT</code>.
     */
    public final TableField<DuplicateGroupRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private DuplicateGroup(Name alias, Table<DuplicateGroupRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DuplicateGroup(Name alias, Table<DuplicateGroupRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.DUPLICATE_GROUP</code> table reference
     */
    public DuplicateGroup(String alias) {
        this(DSL.name(alias), DUPLICATE_GROUP);
    }

    /**
     * Create an aliased <code>public.DUPLICATE_GROUP</code> table reference
     */
    public DuplicateGroup(Name alias) {
        this(alias, DUPLICATE_GROUP);
    }

    /**
     * Create a <code>public.DUPLICATE_GROUP</code> table reference
     */
    public DuplicateGroup() {
        this(DSL.name("DUPLICATE_GROUP"), null);
    }

    public <O extends Record> DuplicateGroup(Table<O> path, ForeignKey<O, DuplicateGroupRecord> childPath, InverseForeignKey<O, DuplicateGroupRecord> parentPath) {
        super(path, childPath, parentPath, DUPLICATE_GROUP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class DuplicateGroupPath extends DuplicateGroup implements Path<DuplicateGroupRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DuplicateGroupPath(Table<O> path, ForeignKey<O, DuplicateGroupRecord> childPath, InverseForeignKey<O, DuplicateGroupRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DuplicateGroupPath(Name alias, Table<DuplicateGroupRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DuplicateGroupPath as(String alias) {
            return new DuplicateGroupPath(DSL.name(alias), this);
        }

        @Override
        public DuplicateGroupPath as(Name alias) {
            return new DuplicateGroupPath(alias, this);
        }

        @Override
        public DuplicateGroupPath as(Table<?> alias) {
            return new DuplicateGroupPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_DUPLICATE_GROUP_JOB);
    }

    @Override
    public Identity<DuplicateGroupRecord, Long> getIdentity() {
        return (Identity<DuplicateGroupRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DuplicateGroupRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_B;
    }

    @Override
    public List<UniqueKey<DuplicateGroupRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_B68);
    }

    @Override
    public List<ForeignKey<DuplicateGroupRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_B6);
    }

    private transient DuplicateJobPath _duplicateJob;

    /**
     * Get the implicit join path to the <code>public.DUPLICATE_JOB</code>
     * table.
     */
    public DuplicateJobPath duplicateJob() {
        if (_duplicateJob == null)
            _duplicateJob = new DuplicateJobPath(this, Keys.CONSTRAINT_B6, null);

        return _duplicateJob;
    }

    private transient DuplicateGroupMemberPath _duplicateGroupMember;

    /**
     * Get the implicit to-many join path to the
     * <code>public.DUPLICATE_GROUP_MEMBER</code> table
     */
    public DuplicateGroupMemberPath duplicateGroupMember() {
        if (_duplicateGroupMember == null)
            _duplicateGroupMember = new DuplicateGroupMemberPath(this, null, Keys.CONSTRAINT_BB0.getInverseKey());

        return _duplicateGroupMember;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.PHOTO</code>
     * table
     */
    public PhotoPath photo() {
        return duplicateGroupMember().photo();
    }

    @Override
    public DuplicateGroup as(String alias) {
        return new DuplicateGroup(DSL.name(alias), this);
    }

    @Override
    public DuplicateGroup as(Name alias) {
        return new DuplicateGroup(alias, this);
    }

    @Override
    public DuplicateGroup as(Table<?> alias) {
        return new DuplicateGroup(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DuplicateGroup rename(String name) {
        return new DuplicateGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DuplicateGroup rename(Name name) {
        return new DuplicateGroup(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DuplicateGroup rename(Table<?> name) {
        return new DuplicateGroup(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateGroup where(Condition condition) {
        return new DuplicateGroup(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateGroup where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateGroup where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateGroup where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DuplicateGroup where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DuplicateGroup where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DuplicateGroup where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DuplicateGroup where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateGroup whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DuplicateGroup whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
