/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Face.FacePath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.FaceEmbeddingRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FaceEmbedding extends TableImpl<FaceEmbeddingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.FACE_EMBEDDING</code>
     */
    public static final FaceEmbedding FACE_EMBEDDING = new FaceEmbedding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FaceEmbeddingRecord> getRecordType() {
        return FaceEmbeddingRecord.class;
    }

    /**
     * The column <code>public.FACE_EMBEDDING.FACE_ID</code>.
     */
    public final TableField<FaceEmbeddingRecord, Long> FACE_ID = createField(DSL.name("FACE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.FACE_EMBEDDING.EMBEDDING</code>.
     */
    public final TableField<FaceEmbeddingRecord, byte[]> EMBEDDING = createField(DSL.name("EMBEDDING"), SQLDataType.BINARY(2048).nullable(false), this, "");

    /**
     * The column <code>public.FACE_EMBEDDING.MODEL_VER</code>.
     */
    public final TableField<FaceEmbeddingRecord, String> MODEL_VER = createField(DSL.name("MODEL_VER"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    private FaceEmbedding(Name alias, Table<FaceEmbeddingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FaceEmbedding(Name alias, Table<FaceEmbeddingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.FACE_EMBEDDING</code> table reference
     */
    public FaceEmbedding(String alias) {
        this(DSL.name(alias), FACE_EMBEDDING);
    }

    /**
     * Create an aliased <code>public.FACE_EMBEDDING</code> table reference
     */
    public FaceEmbedding(Name alias) {
        this(alias, FACE_EMBEDDING);
    }

    /**
     * Create a <code>public.FACE_EMBEDDING</code> table reference
     */
    public FaceEmbedding() {
        this(DSL.name("FACE_EMBEDDING"), null);
    }

    public <O extends Record> FaceEmbedding(Table<O> path, ForeignKey<O, FaceEmbeddingRecord> childPath, InverseForeignKey<O, FaceEmbeddingRecord> parentPath) {
        super(path, childPath, parentPath, FACE_EMBEDDING);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class FaceEmbeddingPath extends FaceEmbedding implements Path<FaceEmbeddingRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FaceEmbeddingPath(Table<O> path, ForeignKey<O, FaceEmbeddingRecord> childPath, InverseForeignKey<O, FaceEmbeddingRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FaceEmbeddingPath(Name alias, Table<FaceEmbeddingRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FaceEmbeddingPath as(String alias) {
            return new FaceEmbeddingPath(DSL.name(alias), this);
        }

        @Override
        public FaceEmbeddingPath as(Name alias) {
            return new FaceEmbeddingPath(alias, this);
        }

        @Override
        public FaceEmbeddingPath as(Table<?> alias) {
            return new FaceEmbeddingPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FaceEmbeddingRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_70;
    }

    @Override
    public List<ForeignKey<FaceEmbeddingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_707);
    }

    private transient FacePath _face;

    /**
     * Get the implicit join path to the <code>public.FACE</code> table.
     */
    public FacePath face() {
        if (_face == null)
            _face = new FacePath(this, Keys.CONSTRAINT_707, null);

        return _face;
    }

    @Override
    public FaceEmbedding as(String alias) {
        return new FaceEmbedding(DSL.name(alias), this);
    }

    @Override
    public FaceEmbedding as(Name alias) {
        return new FaceEmbedding(alias, this);
    }

    @Override
    public FaceEmbedding as(Table<?> alias) {
        return new FaceEmbedding(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FaceEmbedding rename(String name) {
        return new FaceEmbedding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FaceEmbedding rename(Name name) {
        return new FaceEmbedding(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FaceEmbedding rename(Table<?> name) {
        return new FaceEmbedding(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FaceEmbedding where(Condition condition) {
        return new FaceEmbedding(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FaceEmbedding where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FaceEmbedding where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FaceEmbedding where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FaceEmbedding where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FaceEmbedding where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FaceEmbedding where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FaceEmbedding where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FaceEmbedding whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FaceEmbedding whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
