/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Cluster.ClusterPath;
import com.github.curiousoddman.curious_images.dbobj.tables.FaceEmbedding.FaceEmbeddingPath;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo.PhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.FaceRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Face extends TableImpl<FaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.FACE</code>
     */
    public static final Face FACE = new Face();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FaceRecord> getRecordType() {
        return FaceRecord.class;
    }

    /**
     * The column <code>public.FACE.ID</code>.
     */
    public final TableField<FaceRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.FACE.PHOTO_ID</code>.
     */
    public final TableField<FaceRecord, Long> PHOTO_ID = createField(DSL.name("PHOTO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.FACE.BBOX_X</code>.
     */
    public final TableField<FaceRecord, Double> BBOX_X = createField(DSL.name("BBOX_X"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.FACE.BBOX_Y</code>.
     */
    public final TableField<FaceRecord, Double> BBOX_Y = createField(DSL.name("BBOX_Y"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.FACE.BBOX_W</code>.
     */
    public final TableField<FaceRecord, Double> BBOX_W = createField(DSL.name("BBOX_W"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.FACE.BBOX_H</code>.
     */
    public final TableField<FaceRecord, Double> BBOX_H = createField(DSL.name("BBOX_H"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.FACE.CONFIDENCE</code>.
     */
    public final TableField<FaceRecord, Double> CONFIDENCE = createField(DSL.name("CONFIDENCE"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.FACE.LANDMARK_LEFT_EYE_X</code>.
     */
    public final TableField<FaceRecord, Double> LANDMARK_LEFT_EYE_X = createField(DSL.name("LANDMARK_LEFT_EYE_X"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.FACE.LANDMARK_LEFT_EYE_Y</code>.
     */
    public final TableField<FaceRecord, Double> LANDMARK_LEFT_EYE_Y = createField(DSL.name("LANDMARK_LEFT_EYE_Y"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.FACE.LANDMARK_RIGHT_EYE_X</code>.
     */
    public final TableField<FaceRecord, Double> LANDMARK_RIGHT_EYE_X = createField(DSL.name("LANDMARK_RIGHT_EYE_X"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.FACE.LANDMARK_RIGHT_EYE_Y</code>.
     */
    public final TableField<FaceRecord, Double> LANDMARK_RIGHT_EYE_Y = createField(DSL.name("LANDMARK_RIGHT_EYE_Y"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.FACE.LANDMARK_NOSE_X</code>.
     */
    public final TableField<FaceRecord, Double> LANDMARK_NOSE_X = createField(DSL.name("LANDMARK_NOSE_X"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.FACE.LANDMARK_NOSE_Y</code>.
     */
    public final TableField<FaceRecord, Double> LANDMARK_NOSE_Y = createField(DSL.name("LANDMARK_NOSE_Y"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.FACE.LANDMARK_LEFT_MOUTH_X</code>.
     */
    public final TableField<FaceRecord, Double> LANDMARK_LEFT_MOUTH_X = createField(DSL.name("LANDMARK_LEFT_MOUTH_X"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.FACE.LANDMARK_LEFT_MOUTH_Y</code>.
     */
    public final TableField<FaceRecord, Double> LANDMARK_LEFT_MOUTH_Y = createField(DSL.name("LANDMARK_LEFT_MOUTH_Y"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.FACE.LANDMARK_RIGHT_MOUTH_X</code>.
     */
    public final TableField<FaceRecord, Double> LANDMARK_RIGHT_MOUTH_X = createField(DSL.name("LANDMARK_RIGHT_MOUTH_X"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.FACE.LANDMARK_RIGHT_MOUTH_Y</code>.
     */
    public final TableField<FaceRecord, Double> LANDMARK_RIGHT_MOUTH_Y = createField(DSL.name("LANDMARK_RIGHT_MOUTH_Y"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.FACE.CREATED_AT</code>.
     */
    public final TableField<FaceRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.FACE.THUMBNAIL_ABSOLUTE_PATH</code>.
     */
    public final TableField<FaceRecord, String> THUMBNAIL_ABSOLUTE_PATH = createField(DSL.name("THUMBNAIL_ABSOLUTE_PATH"), SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>public.FACE.ASSIGNMENT_LOCKED</code>.
     */
    public final TableField<FaceRecord, Boolean> ASSIGNMENT_LOCKED = createField(DSL.name("ASSIGNMENT_LOCKED"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("FALSE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.FACE.EXCLUDED</code>.
     */
    public final TableField<FaceRecord, Boolean> EXCLUDED = createField(DSL.name("EXCLUDED"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("FALSE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.FACE.CLUSTER_ID</code>.
     */
    public final TableField<FaceRecord, Long> CLUSTER_ID = createField(DSL.name("CLUSTER_ID"), SQLDataType.BIGINT, this, "");

    private Face(Name alias, Table<FaceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Face(Name alias, Table<FaceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.FACE</code> table reference
     */
    public Face(String alias) {
        this(DSL.name(alias), FACE);
    }

    /**
     * Create an aliased <code>public.FACE</code> table reference
     */
    public Face(Name alias) {
        this(alias, FACE);
    }

    /**
     * Create a <code>public.FACE</code> table reference
     */
    public Face() {
        this(DSL.name("FACE"), null);
    }

    public <O extends Record> Face(Table<O> path, ForeignKey<O, FaceRecord> childPath, InverseForeignKey<O, FaceRecord> parentPath) {
        super(path, childPath, parentPath, FACE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class FacePath extends Face implements Path<FaceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FacePath(Table<O> path, ForeignKey<O, FaceRecord> childPath, InverseForeignKey<O, FaceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FacePath(Name alias, Table<FaceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FacePath as(String alias) {
            return new FacePath(DSL.name(alias), this);
        }

        @Override
        public FacePath as(Name alias) {
            return new FacePath(alias, this);
        }

        @Override
        public FacePath as(Table<?> alias) {
            return new FacePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_FACE_CLUSTER_ID, Indexes.IDX_FACE_PHOTO);
    }

    @Override
    public Identity<FaceRecord, Long> getIdentity() {
        return (Identity<FaceRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FaceRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_20;
    }

    @Override
    public List<ForeignKey<FaceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_20C, Keys.CONSTRAINT_20CE);
    }

    private transient PhotoPath _photo;

    /**
     * Get the implicit join path to the <code>public.PHOTO</code> table.
     */
    public PhotoPath photo() {
        if (_photo == null)
            _photo = new PhotoPath(this, Keys.CONSTRAINT_20C, null);

        return _photo;
    }

    private transient ClusterPath _cluster;

    /**
     * Get the implicit join path to the <code>public.CLUSTER</code> table.
     */
    public ClusterPath cluster() {
        if (_cluster == null)
            _cluster = new ClusterPath(this, Keys.CONSTRAINT_20CE, null);

        return _cluster;
    }

    private transient FaceEmbeddingPath _faceEmbedding;

    /**
     * Get the implicit to-many join path to the
     * <code>public.FACE_EMBEDDING</code> table
     */
    public FaceEmbeddingPath faceEmbedding() {
        if (_faceEmbedding == null)
            _faceEmbedding = new FaceEmbeddingPath(this, null, Keys.CONSTRAINT_707.getInverseKey());

        return _faceEmbedding;
    }

    @Override
    public Face as(String alias) {
        return new Face(DSL.name(alias), this);
    }

    @Override
    public Face as(Name alias) {
        return new Face(alias, this);
    }

    @Override
    public Face as(Table<?> alias) {
        return new Face(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Face rename(String name) {
        return new Face(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Face rename(Name name) {
        return new Face(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Face rename(Table<?> name) {
        return new Face(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Face where(Condition condition) {
        return new Face(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Face where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Face where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Face where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Face where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Face where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Face where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Face where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Face whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Face whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
