/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Folder.FolderPath;
import com.github.curiousoddman.curious_images.dbobj.tables.ImportRoot.ImportRootPath;
import com.github.curiousoddman.curious_images.dbobj.tables.Media.MediaPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.FolderRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Folder extends TableImpl<FolderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.FOLDER</code>
     */
    public static final Folder FOLDER = new Folder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FolderRecord> getRecordType() {
        return FolderRecord.class;
    }

    /**
     * The column <code>public.FOLDER.ID</code>.
     */
    public final TableField<FolderRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.FOLDER.IMPORT_ROOT_ID</code>.
     */
    public final TableField<FolderRecord, Long> IMPORT_ROOT_ID = createField(DSL.name("IMPORT_ROOT_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.FOLDER.PARENT_FOLDER_ID</code>.
     */
    public final TableField<FolderRecord, Long> PARENT_FOLDER_ID = createField(DSL.name("PARENT_FOLDER_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.FOLDER.RELATIVE_PATH</code>.
     */
    public final TableField<FolderRecord, String> RELATIVE_PATH = createField(DSL.name("RELATIVE_PATH"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.FOLDER.NAME</code>.
     */
    public final TableField<FolderRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(255), this, "");

    private Folder(Name alias, Table<FolderRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Folder(Name alias, Table<FolderRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.FOLDER</code> table reference
     */
    public Folder(String alias) {
        this(DSL.name(alias), FOLDER);
    }

    /**
     * Create an aliased <code>public.FOLDER</code> table reference
     */
    public Folder(Name alias) {
        this(alias, FOLDER);
    }

    /**
     * Create a <code>public.FOLDER</code> table reference
     */
    public Folder() {
        this(DSL.name("FOLDER"), null);
    }

    public <O extends Record> Folder(Table<O> path, ForeignKey<O, FolderRecord> childPath, InverseForeignKey<O, FolderRecord> parentPath) {
        super(path, childPath, parentPath, FOLDER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class FolderPath extends Folder implements Path<FolderRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> FolderPath(Table<O> path, ForeignKey<O, FolderRecord> childPath, InverseForeignKey<O, FolderRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private FolderPath(Name alias, Table<FolderRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public FolderPath as(String alias) {
            return new FolderPath(DSL.name(alias), this);
        }

        @Override
        public FolderPath as(Name alias) {
            return new FolderPath(alias, this);
        }

        @Override
        public FolderPath as(Table<?> alias) {
            return new FolderPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FolderRecord, Long> getIdentity() {
        return (Identity<FolderRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FolderRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_7B;
    }

    @Override
    public List<UniqueKey<FolderRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_7BF01);
    }

    @Override
    public List<ForeignKey<FolderRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_7BF, Keys.CONSTRAINT_7BF0);
    }

    private transient ImportRootPath _importRoot;

    /**
     * Get the implicit join path to the <code>public.IMPORT_ROOT</code> table.
     */
    public ImportRootPath importRoot() {
        if (_importRoot == null)
            _importRoot = new ImportRootPath(this, Keys.CONSTRAINT_7BF, null);

        return _importRoot;
    }

    private transient FolderPath _folder;

    /**
     * Get the implicit join path to the <code>public.FOLDER</code> table.
     */
    public FolderPath folder() {
        if (_folder == null)
            _folder = new FolderPath(this, Keys.CONSTRAINT_7BF0, null);

        return _folder;
    }

    private transient MediaPath _media;

    /**
     * Get the implicit to-many join path to the <code>public.MEDIA</code> table
     */
    public MediaPath media() {
        if (_media == null)
            _media = new MediaPath(this, null, Keys.CONSTRAINT_45.getInverseKey());

        return _media;
    }

    @Override
    public Folder as(String alias) {
        return new Folder(DSL.name(alias), this);
    }

    @Override
    public Folder as(Name alias) {
        return new Folder(alias, this);
    }

    @Override
    public Folder as(Table<?> alias) {
        return new Folder(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Folder rename(String name) {
        return new Folder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Folder rename(Name name) {
        return new Folder(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Folder rename(Table<?> name) {
        return new Folder(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Folder where(Condition condition) {
        return new Folder(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Folder where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Folder where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Folder where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Folder where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Folder where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Folder where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Folder where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Folder whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Folder whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
