/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Folder.FolderPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.ImportRootRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.19.28",
                "schema version:none"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ImportRoot extends TableImpl<ImportRootRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.IMPORT_ROOT</code>
     */
    public static final ImportRoot IMPORT_ROOT = new ImportRoot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ImportRootRecord> getRecordType() {
        return ImportRootRecord.class;
    }

    /**
     * The column <code>public.IMPORT_ROOT.ID</code>.
     */
    public final TableField<ImportRootRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.IMPORT_ROOT.PATH</code>.
     */
    public final TableField<ImportRootRecord, String> PATH = createField(DSL.name("PATH"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.IMPORT_ROOT.CREATED_AT</code>.
     */
    public final TableField<ImportRootRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.IMPORT_ROOT.LAST_SCANNED_AT</code>.
     */
    public final TableField<ImportRootRecord, LocalDateTime> LAST_SCANNED_AT = createField(DSL.name("LAST_SCANNED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private ImportRoot(Name alias, Table<ImportRootRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ImportRoot(Name alias, Table<ImportRootRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.IMPORT_ROOT</code> table reference
     */
    public ImportRoot(String alias) {
        this(DSL.name(alias), IMPORT_ROOT);
    }

    /**
     * Create an aliased <code>public.IMPORT_ROOT</code> table reference
     */
    public ImportRoot(Name alias) {
        this(alias, IMPORT_ROOT);
    }

    /**
     * Create a <code>public.IMPORT_ROOT</code> table reference
     */
    public ImportRoot() {
        this(DSL.name("IMPORT_ROOT"), null);
    }

    public <O extends Record> ImportRoot(Table<O> path, ForeignKey<O, ImportRootRecord> childPath, InverseForeignKey<O, ImportRootRecord> parentPath) {
        super(path, childPath, parentPath, IMPORT_ROOT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
            value = {
                    "https://www.jooq.org",
                    "jOOQ version:3.19.28",
                    "schema version:none"
            },
            comments = "This class is generated by jOOQ"
    )
    public static class ImportRootPath extends ImportRoot implements Path<ImportRootRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> ImportRootPath(Table<O> path, ForeignKey<O, ImportRootRecord> childPath, InverseForeignKey<O, ImportRootRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private ImportRootPath(Name alias, Table<ImportRootRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ImportRootPath as(String alias) {
            return new ImportRootPath(DSL.name(alias), this);
        }

        @Override
        public ImportRootPath as(Name alias) {
            return new ImportRootPath(alias, this);
        }

        @Override
        public ImportRootPath as(Table<?> alias) {
            return new ImportRootPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ImportRootRecord, Long> getIdentity() {
        return (Identity<ImportRootRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ImportRootRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D;
    }

    @Override
    public List<UniqueKey<ImportRootRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_D9);
    }

    private transient FolderPath _folder;

    /**
     * Get the implicit to-many join path to the <code>public.FOLDER</code>
     * table
     */
    public FolderPath folder() {
        if (_folder == null)
            _folder = new FolderPath(this, null, Keys.CONSTRAINT_7BF.getInverseKey());

        return _folder;
    }

    @Override
    public ImportRoot as(String alias) {
        return new ImportRoot(DSL.name(alias), this);
    }

    @Override
    public ImportRoot as(Name alias) {
        return new ImportRoot(alias, this);
    }

    @Override
    public ImportRoot as(Table<?> alias) {
        return new ImportRoot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ImportRoot rename(String name) {
        return new ImportRoot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ImportRoot rename(Name name) {
        return new ImportRoot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ImportRoot rename(Table<?> name) {
        return new ImportRoot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportRoot where(Condition condition) {
        return new ImportRoot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportRoot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportRoot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportRoot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportRoot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportRoot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportRoot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImportRoot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportRoot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImportRoot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
