/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Media.MediaPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.MediaHashRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaHash extends TableImpl<MediaHashRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.MEDIA_HASH</code>
     */
    public static final MediaHash MEDIA_HASH = new MediaHash();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaHashRecord> getRecordType() {
        return MediaHashRecord.class;
    }

    /**
     * The column <code>public.MEDIA_HASH.MEDIA_ID</code>.
     */
    public final TableField<MediaHashRecord, Long> MEDIA_ID = createField(DSL.name("MEDIA_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.MEDIA_HASH.HASH_TYPE</code>.
     */
    public final TableField<MediaHashRecord, String> HASH_TYPE = createField(DSL.name("HASH_TYPE"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.MEDIA_HASH.CONTENT_HASH</code>.
     */
    public final TableField<MediaHashRecord, String> CONTENT_HASH = createField(DSL.name("CONTENT_HASH"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.MEDIA_HASH.HASHED_FILE_SIZE</code>.
     */
    public final TableField<MediaHashRecord, Long> HASHED_FILE_SIZE = createField(DSL.name("HASHED_FILE_SIZE"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.MEDIA_HASH.HASHED_AT</code>.
     */
    public final TableField<MediaHashRecord, LocalDateTime> HASHED_AT = createField(DSL.name("HASHED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private MediaHash(Name alias, Table<MediaHashRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaHash(Name alias, Table<MediaHashRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.MEDIA_HASH</code> table reference
     */
    public MediaHash(String alias) {
        this(DSL.name(alias), MEDIA_HASH);
    }

    /**
     * Create an aliased <code>public.MEDIA_HASH</code> table reference
     */
    public MediaHash(Name alias) {
        this(alias, MEDIA_HASH);
    }

    /**
     * Create a <code>public.MEDIA_HASH</code> table reference
     */
    public MediaHash() {
        this(DSL.name("MEDIA_HASH"), null);
    }

    public <O extends Record> MediaHash(Table<O> path, ForeignKey<O, MediaHashRecord> childPath, InverseForeignKey<O, MediaHashRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_HASH);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MediaHashPath extends MediaHash implements Path<MediaHashRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaHashPath(Table<O> path, ForeignKey<O, MediaHashRecord> childPath, InverseForeignKey<O, MediaHashRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaHashPath(Name alias, Table<MediaHashRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaHashPath as(String alias) {
            return new MediaHashPath(DSL.name(alias), this);
        }

        @Override
        public MediaHashPath as(Name alias) {
            return new MediaHashPath(alias, this);
        }

        @Override
        public MediaHashPath as(Table<?> alias) {
            return new MediaHashPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_MEDIA_HASH_CONTENT_HASH);
    }

    @Override
    public UniqueKey<MediaHashRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9;
    }

    @Override
    public List<ForeignKey<MediaHashRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_92);
    }

    private transient MediaPath _media;

    /**
     * Get the implicit join path to the <code>public.MEDIA</code> table.
     */
    public MediaPath media() {
        if (_media == null)
            _media = new MediaPath(this, Keys.CONSTRAINT_92, null);

        return _media;
    }

    @Override
    public MediaHash as(String alias) {
        return new MediaHash(DSL.name(alias), this);
    }

    @Override
    public MediaHash as(Name alias) {
        return new MediaHash(alias, this);
    }

    @Override
    public MediaHash as(Table<?> alias) {
        return new MediaHash(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaHash rename(String name) {
        return new MediaHash(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaHash rename(Name name) {
        return new MediaHash(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaHash rename(Table<?> name) {
        return new MediaHash(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaHash where(Condition condition) {
        return new MediaHash(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaHash where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaHash where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaHash where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaHash where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaHash where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaHash where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaHash where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaHash whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaHash whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
