/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.records.MediaVideoRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaVideo extends TableImpl<MediaVideoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.MEDIA_VIDEO</code>
     */
    public static final MediaVideo MEDIA_VIDEO = new MediaVideo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaVideoRecord> getRecordType() {
        return MediaVideoRecord.class;
    }

    /**
     * The column <code>public.MEDIA_VIDEO.ID</code>.
     */
    public final TableField<MediaVideoRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.DURATION_MS</code>.
     */
    public final TableField<MediaVideoRecord, Long> DURATION_MS = createField(DSL.name("DURATION_MS"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.CODEC</code>.
     */
    public final TableField<MediaVideoRecord, String> CODEC = createField(DSL.name("CODEC"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.FRAME_RATE</code>.
     */
    public final TableField<MediaVideoRecord, Double> FRAME_RATE = createField(DSL.name("FRAME_RATE"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.ROTATION</code>.
     */
    public final TableField<MediaVideoRecord, Integer> ROTATION = createField(DSL.name("ROTATION"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.MEDIA_TYPE</code>.
     */
    public final TableField<MediaVideoRecord, String> MEDIA_TYPE = createField(DSL.name("MEDIA_TYPE"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.FOLDER_ID</code>.
     */
    public final TableField<MediaVideoRecord, Long> FOLDER_ID = createField(DSL.name("FOLDER_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.ABSOLUTE_PATH</code>.
     */
    public final TableField<MediaVideoRecord, String> ABSOLUTE_PATH = createField(DSL.name("ABSOLUTE_PATH"), SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.FILENAME</code>.
     */
    public final TableField<MediaVideoRecord, String> FILENAME = createField(DSL.name("FILENAME"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.EXTENSION</code>.
     */
    public final TableField<MediaVideoRecord, String> EXTENSION = createField(DSL.name("EXTENSION"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.FILE_SIZE</code>.
     */
    public final TableField<MediaVideoRecord, Long> FILE_SIZE = createField(DSL.name("FILE_SIZE"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.WIDTH</code>.
     */
    public final TableField<MediaVideoRecord, Integer> WIDTH = createField(DSL.name("WIDTH"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.HEIGHT</code>.
     */
    public final TableField<MediaVideoRecord, Integer> HEIGHT = createField(DSL.name("HEIGHT"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.CAPTURE_DATE</code>.
     */
    public final TableField<MediaVideoRecord, LocalDateTime> CAPTURE_DATE = createField(DSL.name("CAPTURE_DATE"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.CAPTURE_DATE_SOURCE</code>.
     */
    public final TableField<MediaVideoRecord, String> CAPTURE_DATE_SOURCE = createField(DSL.name("CAPTURE_DATE_SOURCE"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.IMPORTED_AT</code>.
     */
    public final TableField<MediaVideoRecord, LocalDateTime> IMPORTED_AT = createField(DSL.name("IMPORTED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.LAST_SEEN_AT</code>.
     */
    public final TableField<MediaVideoRecord, LocalDateTime> LAST_SEEN_AT = createField(DSL.name("LAST_SEEN_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.CAMERA_MAKE</code>.
     */
    public final TableField<MediaVideoRecord, String> CAMERA_MAKE = createField(DSL.name("CAMERA_MAKE"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.CAMERA_MODEL</code>.
     */
    public final TableField<MediaVideoRecord, String> CAMERA_MODEL = createField(DSL.name("CAMERA_MODEL"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.GPS_LAT</code>.
     */
    public final TableField<MediaVideoRecord, Double> GPS_LAT = createField(DSL.name("GPS_LAT"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.GPS_LON</code>.
     */
    public final TableField<MediaVideoRecord, Double> GPS_LON = createField(DSL.name("GPS_LON"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.GPS_ALTITUDE</code>.
     */
    public final TableField<MediaVideoRecord, Double> GPS_ALTITUDE = createField(DSL.name("GPS_ALTITUDE"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.AI_FACE_DETECT_DONE</code>.
     */
    public final TableField<MediaVideoRecord, Boolean> AI_FACE_DETECT_DONE = createField(DSL.name("AI_FACE_DETECT_DONE"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.AI_FACE_EMBED_DONE</code>.
     */
    public final TableField<MediaVideoRecord, Boolean> AI_FACE_EMBED_DONE = createField(DSL.name("AI_FACE_EMBED_DONE"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.AI_CLIP_EMBED_DONE</code>.
     */
    public final TableField<MediaVideoRecord, Boolean> AI_CLIP_EMBED_DONE = createField(DSL.name("AI_CLIP_EMBED_DONE"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.AI_TAG_DONE</code>.
     */
    public final TableField<MediaVideoRecord, Boolean> AI_TAG_DONE = createField(DSL.name("AI_TAG_DONE"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.AI_LUCENE_INDEX_DONE</code>.
     */
    public final TableField<MediaVideoRecord, Boolean> AI_LUCENE_INDEX_DONE = createField(DSL.name("AI_LUCENE_INDEX_DONE"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.AI_LAST_ERROR</code>.
     */
    public final TableField<MediaVideoRecord, String> AI_LAST_ERROR = createField(DSL.name("AI_LAST_ERROR"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.AI_RETRY_COUNT</code>.
     */
    public final TableField<MediaVideoRecord, Short> AI_RETRY_COUNT = createField(DSL.name("AI_RETRY_COUNT"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.MEDIA_VIDEO.AI_UPDATED_AT</code>.
     */
    public final TableField<MediaVideoRecord, LocalDateTime> AI_UPDATED_AT = createField(DSL.name("AI_UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private MediaVideo(Name alias, Table<MediaVideoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaVideo(Name alias, Table<MediaVideoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
            create view "MEDIA_VIDEO" as SELECT
            "public"."VIDEO"."ID",
            "public"."VIDEO"."DURATION_MS",
            "public"."VIDEO"."CODEC",
            "public"."VIDEO"."FRAME_RATE",
            "public"."VIDEO"."ROTATION",
            "public"."MEDIA"."MEDIA_TYPE",
            "public"."MEDIA"."FOLDER_ID",
            "public"."MEDIA"."ABSOLUTE_PATH",
            "public"."MEDIA"."FILENAME",
            "public"."MEDIA"."EXTENSION",
            "public"."MEDIA"."FILE_SIZE",
            "public"."MEDIA"."WIDTH",
            "public"."MEDIA"."HEIGHT",
            "public"."MEDIA"."CAPTURE_DATE",
            "public"."MEDIA"."CAPTURE_DATE_SOURCE",
            "public"."MEDIA"."IMPORTED_AT",
            "public"."MEDIA"."LAST_SEEN_AT",
            "public"."MEDIA"."CAMERA_MAKE",
            "public"."MEDIA"."CAMERA_MODEL",
            "public"."MEDIA"."GPS_LAT",
            "public"."MEDIA"."GPS_LON",
            "public"."MEDIA"."GPS_ALTITUDE",
            "public"."MEDIA"."AI_FACE_DETECT_DONE",
            "public"."MEDIA"."AI_FACE_EMBED_DONE",
            "public"."MEDIA"."AI_CLIP_EMBED_DONE",
            "public"."MEDIA"."AI_TAG_DONE",
            "public"."MEDIA"."AI_LUCENE_INDEX_DONE",
            "public"."MEDIA"."AI_LAST_ERROR",
            "public"."MEDIA"."AI_RETRY_COUNT",
            "public"."MEDIA"."AI_UPDATED_AT"
        FROM "public"."VIDEO"
        INNER JOIN "public"."MEDIA"
            ON 1=1
        WHERE "public"."VIDEO"."ID" = "public"."MEDIA"."ID"
        """), where);
    }

    /**
     * Create an aliased <code>public.MEDIA_VIDEO</code> table reference
     */
    public MediaVideo(String alias) {
        this(DSL.name(alias), MEDIA_VIDEO);
    }

    /**
     * Create an aliased <code>public.MEDIA_VIDEO</code> table reference
     */
    public MediaVideo(Name alias) {
        this(alias, MEDIA_VIDEO);
    }

    /**
     * Create a <code>public.MEDIA_VIDEO</code> table reference
     */
    public MediaVideo() {
        this(DSL.name("MEDIA_VIDEO"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public MediaVideo as(String alias) {
        return new MediaVideo(DSL.name(alias), this);
    }

    @Override
    public MediaVideo as(Name alias) {
        return new MediaVideo(alias, this);
    }

    @Override
    public MediaVideo as(Table<?> alias) {
        return new MediaVideo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaVideo rename(String name) {
        return new MediaVideo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaVideo rename(Name name) {
        return new MediaVideo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaVideo rename(Table<?> name) {
        return new MediaVideo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaVideo where(Condition condition) {
        return new MediaVideo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaVideo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaVideo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaVideo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaVideo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaVideo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaVideo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaVideo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaVideo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaVideo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
