/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Media.MediaPath;
import com.github.curiousoddman.curious_images.dbobj.tables.TagEmbedding.TagEmbeddingPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.MediaTagRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaTag extends TableImpl<MediaTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.MEDIA_TAG</code>
     */
    public static final MediaTag MEDIA_TAG = new MediaTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaTagRecord> getRecordType() {
        return MediaTagRecord.class;
    }

    /**
     * The column <code>public.MEDIA_TAG.TAG_ID</code>.
     */
    public final TableField<MediaTagRecord, Long> TAG_ID = createField(DSL.name("TAG_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.MEDIA_TAG.MEDIA_ID</code>.
     */
    public final TableField<MediaTagRecord, Long> MEDIA_ID = createField(DSL.name("MEDIA_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.MEDIA_TAG.TAG_SOURCE</code>.
     */
    public final TableField<MediaTagRecord, String> TAG_SOURCE = createField(DSL.name("TAG_SOURCE"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.MEDIA_TAG.CONFIDENCE</code>.
     */
    public final TableField<MediaTagRecord, Double> CONFIDENCE = createField(DSL.name("CONFIDENCE"), SQLDataType.DOUBLE, this, "");

    private MediaTag(Name alias, Table<MediaTagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaTag(Name alias, Table<MediaTagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.MEDIA_TAG</code> table reference
     */
    public MediaTag(String alias) {
        this(DSL.name(alias), MEDIA_TAG);
    }

    /**
     * Create an aliased <code>public.MEDIA_TAG</code> table reference
     */
    public MediaTag(Name alias) {
        this(alias, MEDIA_TAG);
    }

    /**
     * Create a <code>public.MEDIA_TAG</code> table reference
     */
    public MediaTag() {
        this(DSL.name("MEDIA_TAG"), null);
    }

    public <O extends Record> MediaTag(Table<O> path, ForeignKey<O, MediaTagRecord> childPath, InverseForeignKey<O, MediaTagRecord> parentPath) {
        super(path, childPath, parentPath, MEDIA_TAG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class MediaTagPath extends MediaTag implements Path<MediaTagRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> MediaTagPath(Table<O> path, ForeignKey<O, MediaTagRecord> childPath, InverseForeignKey<O, MediaTagRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private MediaTagPath(Name alias, Table<MediaTagRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MediaTagPath as(String alias) {
            return new MediaTagPath(DSL.name(alias), this);
        }

        @Override
        public MediaTagPath as(Name alias) {
            return new MediaTagPath(alias, this);
        }

        @Override
        public MediaTagPath as(Table<?> alias) {
            return new MediaTagPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<MediaTagRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_25C0;
    }

    @Override
    public List<ForeignKey<MediaTagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_25, Keys.CONSTRAINT_25C);
    }

    private transient TagEmbeddingPath _tagEmbedding;

    /**
     * Get the implicit join path to the <code>public.TAG_EMBEDDING</code>
     * table.
     */
    public TagEmbeddingPath tagEmbedding() {
        if (_tagEmbedding == null)
            _tagEmbedding = new TagEmbeddingPath(this, Keys.CONSTRAINT_25, null);

        return _tagEmbedding;
    }

    private transient MediaPath _media;

    /**
     * Get the implicit join path to the <code>public.MEDIA</code> table.
     */
    public MediaPath media() {
        if (_media == null)
            _media = new MediaPath(this, Keys.CONSTRAINT_25C, null);

        return _media;
    }

    @Override
    public MediaTag as(String alias) {
        return new MediaTag(DSL.name(alias), this);
    }

    @Override
    public MediaTag as(Name alias) {
        return new MediaTag(alias, this);
    }

    @Override
    public MediaTag as(Table<?> alias) {
        return new MediaTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaTag rename(String name) {
        return new MediaTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaTag rename(Name name) {
        return new MediaTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaTag rename(Table<?> name) {
        return new MediaTag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTag where(Condition condition) {
        return new MediaTag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaTag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaTag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
