/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.records.MediaPhotoRecord;
import com.github.curiousoddman.curious_images.model.MediaType;

import java.time.LocalDateTime;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.EnumConverter;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MediaPhoto extends TableImpl<MediaPhotoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.MEDIA_PHOTO</code>
     */
    public static final MediaPhoto MEDIA_PHOTO = new MediaPhoto();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MediaPhotoRecord> getRecordType() {
        return MediaPhotoRecord.class;
    }

    /**
     * The column <code>public.MEDIA_PHOTO.ID</code>.
     */
    public final TableField<MediaPhotoRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.ORIENTATION</code>.
     */
    public final TableField<MediaPhotoRecord, Integer> ORIENTATION = createField(DSL.name("ORIENTATION"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.LENS_MODEL</code>.
     */
    public final TableField<MediaPhotoRecord, String> LENS_MODEL = createField(DSL.name("LENS_MODEL"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.EXIF_EXTRA</code>.
     */
    public final TableField<MediaPhotoRecord, JSON> EXIF_EXTRA = createField(DSL.name("EXIF_EXTRA"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.MEDIA_TYPE</code>.
     */
    public final TableField<MediaPhotoRecord, MediaType> MEDIA_TYPE = createField(DSL.name("MEDIA_TYPE"), SQLDataType.VARCHAR(10), this, "", new EnumConverter<String, MediaType>(String.class, MediaType.class));

    /**
     * The column <code>public.MEDIA_PHOTO.FOLDER_ID</code>.
     */
    public final TableField<MediaPhotoRecord, Long> FOLDER_ID = createField(DSL.name("FOLDER_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.ABSOLUTE_PATH</code>.
     */
    public final TableField<MediaPhotoRecord, String> ABSOLUTE_PATH = createField(DSL.name("ABSOLUTE_PATH"), SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.FILENAME</code>.
     */
    public final TableField<MediaPhotoRecord, String> FILENAME = createField(DSL.name("FILENAME"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.EXTENSION</code>.
     */
    public final TableField<MediaPhotoRecord, String> EXTENSION = createField(DSL.name("EXTENSION"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.FILE_SIZE</code>.
     */
    public final TableField<MediaPhotoRecord, Long> FILE_SIZE = createField(DSL.name("FILE_SIZE"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.WIDTH</code>.
     */
    public final TableField<MediaPhotoRecord, Integer> WIDTH = createField(DSL.name("WIDTH"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.HEIGHT</code>.
     */
    public final TableField<MediaPhotoRecord, Integer> HEIGHT = createField(DSL.name("HEIGHT"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.CAPTURE_DATE</code>.
     */
    public final TableField<MediaPhotoRecord, LocalDateTime> CAPTURE_DATE = createField(DSL.name("CAPTURE_DATE"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.CAPTURE_DATE_SOURCE</code>.
     */
    public final TableField<MediaPhotoRecord, String> CAPTURE_DATE_SOURCE = createField(DSL.name("CAPTURE_DATE_SOURCE"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.IMPORTED_AT</code>.
     */
    public final TableField<MediaPhotoRecord, LocalDateTime> IMPORTED_AT = createField(DSL.name("IMPORTED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.LAST_SEEN_AT</code>.
     */
    public final TableField<MediaPhotoRecord, LocalDateTime> LAST_SEEN_AT = createField(DSL.name("LAST_SEEN_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.CAMERA_MAKE</code>.
     */
    public final TableField<MediaPhotoRecord, String> CAMERA_MAKE = createField(DSL.name("CAMERA_MAKE"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.CAMERA_MODEL</code>.
     */
    public final TableField<MediaPhotoRecord, String> CAMERA_MODEL = createField(DSL.name("CAMERA_MODEL"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.GPS_LAT</code>.
     */
    public final TableField<MediaPhotoRecord, Double> GPS_LAT = createField(DSL.name("GPS_LAT"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.GPS_LON</code>.
     */
    public final TableField<MediaPhotoRecord, Double> GPS_LON = createField(DSL.name("GPS_LON"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.GPS_ALTITUDE</code>.
     */
    public final TableField<MediaPhotoRecord, Double> GPS_ALTITUDE = createField(DSL.name("GPS_ALTITUDE"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.AI_FACE_DETECT_DONE</code>.
     */
    public final TableField<MediaPhotoRecord, Boolean> AI_FACE_DETECT_DONE = createField(DSL.name("AI_FACE_DETECT_DONE"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.AI_FACE_EMBED_DONE</code>.
     */
    public final TableField<MediaPhotoRecord, Boolean> AI_FACE_EMBED_DONE = createField(DSL.name("AI_FACE_EMBED_DONE"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.AI_CLIP_EMBED_DONE</code>.
     */
    public final TableField<MediaPhotoRecord, Boolean> AI_CLIP_EMBED_DONE = createField(DSL.name("AI_CLIP_EMBED_DONE"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.AI_TAG_DONE</code>.
     */
    public final TableField<MediaPhotoRecord, Boolean> AI_TAG_DONE = createField(DSL.name("AI_TAG_DONE"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.AI_LUCENE_INDEX_DONE</code>.
     */
    public final TableField<MediaPhotoRecord, Boolean> AI_LUCENE_INDEX_DONE = createField(DSL.name("AI_LUCENE_INDEX_DONE"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.AI_LAST_ERROR</code>.
     */
    public final TableField<MediaPhotoRecord, String> AI_LAST_ERROR = createField(DSL.name("AI_LAST_ERROR"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.AI_RETRY_COUNT</code>.
     */
    public final TableField<MediaPhotoRecord, Short> AI_RETRY_COUNT = createField(DSL.name("AI_RETRY_COUNT"), SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.MEDIA_PHOTO.AI_UPDATED_AT</code>.
     */
    public final TableField<MediaPhotoRecord, LocalDateTime> AI_UPDATED_AT = createField(DSL.name("AI_UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private MediaPhoto(Name alias, Table<MediaPhotoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MediaPhoto(Name alias, Table<MediaPhotoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
            create view "MEDIA_PHOTO" as SELECT
            "public"."PHOTO"."ID",
            "public"."PHOTO"."ORIENTATION",
            "public"."PHOTO"."LENS_MODEL",
            "public"."PHOTO"."EXIF_EXTRA",
            "public"."MEDIA"."MEDIA_TYPE",
            "public"."MEDIA"."FOLDER_ID",
            "public"."MEDIA"."ABSOLUTE_PATH",
            "public"."MEDIA"."FILENAME",
            "public"."MEDIA"."EXTENSION",
            "public"."MEDIA"."FILE_SIZE",
            "public"."MEDIA"."WIDTH",
            "public"."MEDIA"."HEIGHT",
            "public"."MEDIA"."CAPTURE_DATE",
            "public"."MEDIA"."CAPTURE_DATE_SOURCE",
            "public"."MEDIA"."IMPORTED_AT",
            "public"."MEDIA"."LAST_SEEN_AT",
            "public"."MEDIA"."CAMERA_MAKE",
            "public"."MEDIA"."CAMERA_MODEL",
            "public"."MEDIA"."GPS_LAT",
            "public"."MEDIA"."GPS_LON",
            "public"."MEDIA"."GPS_ALTITUDE",
            "public"."MEDIA"."AI_FACE_DETECT_DONE",
            "public"."MEDIA"."AI_FACE_EMBED_DONE",
            "public"."MEDIA"."AI_CLIP_EMBED_DONE",
            "public"."MEDIA"."AI_TAG_DONE",
            "public"."MEDIA"."AI_LUCENE_INDEX_DONE",
            "public"."MEDIA"."AI_LAST_ERROR",
            "public"."MEDIA"."AI_RETRY_COUNT",
            "public"."MEDIA"."AI_UPDATED_AT"
        FROM "public"."PHOTO"
        INNER JOIN "public"."MEDIA"
            ON 1=1
        WHERE "public"."PHOTO"."ID" = "public"."MEDIA"."ID"
        """), where);
    }

    /**
     * Create an aliased <code>public.MEDIA_PHOTO</code> table reference
     */
    public MediaPhoto(String alias) {
        this(DSL.name(alias), MEDIA_PHOTO);
    }

    /**
     * Create an aliased <code>public.MEDIA_PHOTO</code> table reference
     */
    public MediaPhoto(Name alias) {
        this(alias, MEDIA_PHOTO);
    }

    /**
     * Create a <code>public.MEDIA_PHOTO</code> table reference
     */
    public MediaPhoto() {
        this(DSL.name("MEDIA_PHOTO"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public MediaPhoto as(String alias) {
        return new MediaPhoto(DSL.name(alias), this);
    }

    @Override
    public MediaPhoto as(Name alias) {
        return new MediaPhoto(alias, this);
    }

    @Override
    public MediaPhoto as(Table<?> alias) {
        return new MediaPhoto(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaPhoto rename(String name) {
        return new MediaPhoto(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaPhoto rename(Name name) {
        return new MediaPhoto(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MediaPhoto rename(Table<?> name) {
        return new MediaPhoto(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaPhoto where(Condition condition) {
        return new MediaPhoto(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaPhoto where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaPhoto where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaPhoto where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaPhoto where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaPhoto where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaPhoto where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MediaPhoto where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaPhoto whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MediaPhoto whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
