/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.records.PendingActionRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PendingAction extends TableImpl<PendingActionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.PENDING_ACTION</code>
     */
    public static final PendingAction PENDING_ACTION = new PendingAction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PendingActionRecord> getRecordType() {
        return PendingActionRecord.class;
    }

    /**
     * The column <code>public.PENDING_ACTION.ID</code>.
     */
    public final TableField<PendingActionRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.PENDING_ACTION.TYPE</code>.
     */
    public final TableField<PendingActionRecord, String> TYPE = createField(DSL.name("TYPE"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.PENDING_ACTION.PAYLOAD</code>.
     */
    public final TableField<PendingActionRecord, byte[]> PAYLOAD = createField(DSL.name("PAYLOAD"), SQLDataType.VARBINARY, this, "");

    /**
     * The column <code>public.PENDING_ACTION.STATUS</code>.
     */
    public final TableField<PendingActionRecord, String> STATUS = createField(DSL.name("STATUS"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>public.PENDING_ACTION.RETRY_COUNT</code>.
     */
    public final TableField<PendingActionRecord, Integer> RETRY_COUNT = createField(DSL.name("RETRY_COUNT"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.PENDING_ACTION.NEXT_ATTEMPT_AT</code>.
     */
    public final TableField<PendingActionRecord, LocalDateTime> NEXT_ATTEMPT_AT = createField(DSL.name("NEXT_ATTEMPT_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.PENDING_ACTION.CREATED_AT</code>.
     */
    public final TableField<PendingActionRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.PENDING_ACTION.LAST_ERROR</code>.
     */
    public final TableField<PendingActionRecord, String> LAST_ERROR = createField(DSL.name("LAST_ERROR"), SQLDataType.VARCHAR, this, "");

    private PendingAction(Name alias, Table<PendingActionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PendingAction(Name alias, Table<PendingActionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.PENDING_ACTION</code> table reference
     */
    public PendingAction(String alias) {
        this(DSL.name(alias), PENDING_ACTION);
    }

    /**
     * Create an aliased <code>public.PENDING_ACTION</code> table reference
     */
    public PendingAction(Name alias) {
        this(alias, PENDING_ACTION);
    }

    /**
     * Create a <code>public.PENDING_ACTION</code> table reference
     */
    public PendingAction() {
        this(DSL.name("PENDING_ACTION"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<PendingActionRecord, Long> getIdentity() {
        return (Identity<PendingActionRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PendingActionRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_7;
    }

    @Override
    public PendingAction as(String alias) {
        return new PendingAction(DSL.name(alias), this);
    }

    @Override
    public PendingAction as(Name alias) {
        return new PendingAction(alias, this);
    }

    @Override
    public PendingAction as(Table<?> alias) {
        return new PendingAction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingAction rename(String name) {
        return new PendingAction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingAction rename(Name name) {
        return new PendingAction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingAction rename(Table<?> name) {
        return new PendingAction(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingAction where(Condition condition) {
        return new PendingAction(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingAction where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingAction where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingAction where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingAction where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingAction where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingAction where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingAction where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingAction whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingAction whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
