/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo.PhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.PhotoHashRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.19.28",
                "schema version:none"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class PhotoHash extends TableImpl<PhotoHashRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.PHOTO_HASH</code>
     */
    public static final PhotoHash PHOTO_HASH = new PhotoHash();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PhotoHashRecord> getRecordType() {
        return PhotoHashRecord.class;
    }

    /**
     * The column <code>public.PHOTO_HASH.PHOTO_ID</code>.
     */
    public final TableField<PhotoHashRecord, Long> PHOTO_ID = createField(DSL.name("PHOTO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.PHOTO_HASH.PIXEL_HASH</code>.
     */
    public final TableField<PhotoHashRecord, String> PIXEL_HASH = createField(DSL.name("PIXEL_HASH"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.PHOTO_HASH.HASHED_FILE_SIZE</code>.
     */
    public final TableField<PhotoHashRecord, Long> HASHED_FILE_SIZE = createField(DSL.name("HASHED_FILE_SIZE"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.PHOTO_HASH.HASHED_AT</code>.
     */
    public final TableField<PhotoHashRecord, LocalDateTime> HASHED_AT = createField(DSL.name("HASHED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private PhotoHash(Name alias, Table<PhotoHashRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PhotoHash(Name alias, Table<PhotoHashRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.PHOTO_HASH</code> table reference
     */
    public PhotoHash(String alias) {
        this(DSL.name(alias), PHOTO_HASH);
    }

    /**
     * Create an aliased <code>public.PHOTO_HASH</code> table reference
     */
    public PhotoHash(Name alias) {
        this(alias, PHOTO_HASH);
    }

    /**
     * Create a <code>public.PHOTO_HASH</code> table reference
     */
    public PhotoHash() {
        this(DSL.name("PHOTO_HASH"), null);
    }

    public <O extends Record> PhotoHash(Table<O> path, ForeignKey<O, PhotoHashRecord> childPath, InverseForeignKey<O, PhotoHashRecord> parentPath) {
        super(path, childPath, parentPath, PHOTO_HASH);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
            value = {
                    "https://www.jooq.org",
                    "jOOQ version:3.19.28",
                    "schema version:none"
            },
            comments = "This class is generated by jOOQ"
    )
    public static class PhotoHashPath extends PhotoHash implements Path<PhotoHashRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> PhotoHashPath(Table<O> path, ForeignKey<O, PhotoHashRecord> childPath, InverseForeignKey<O, PhotoHashRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private PhotoHashPath(Name alias, Table<PhotoHashRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PhotoHashPath as(String alias) {
            return new PhotoHashPath(DSL.name(alias), this);
        }

        @Override
        public PhotoHashPath as(Name alias) {
            return new PhotoHashPath(alias, this);
        }

        @Override
        public PhotoHashPath as(Table<?> alias) {
            return new PhotoHashPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PHOTO_HASH_PIXEL_HASH);
    }

    @Override
    public UniqueKey<PhotoHashRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_6;
    }

    @Override
    public List<ForeignKey<PhotoHashRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_66);
    }

    private transient PhotoPath _photo;

    /**
     * Get the implicit join path to the <code>public.PHOTO</code> table.
     */
    public PhotoPath photo() {
        if (_photo == null)
            _photo = new PhotoPath(this, Keys.CONSTRAINT_66, null);

        return _photo;
    }

    @Override
    public PhotoHash as(String alias) {
        return new PhotoHash(DSL.name(alias), this);
    }

    @Override
    public PhotoHash as(Name alias) {
        return new PhotoHash(alias, this);
    }

    @Override
    public PhotoHash as(Table<?> alias) {
        return new PhotoHash(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PhotoHash rename(String name) {
        return new PhotoHash(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PhotoHash rename(Name name) {
        return new PhotoHash(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PhotoHash rename(Table<?> name) {
        return new PhotoHash(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoHash where(Condition condition) {
        return new PhotoHash(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoHash where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoHash where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoHash where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoHash where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoHash where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoHash where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoHash where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoHash whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoHash whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
