/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Indexes;
import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Album.AlbumPath;
import com.github.curiousoddman.curious_images.dbobj.tables.AlbumPhoto.AlbumPhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.ClipEmbedding.ClipEmbeddingPath;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroup.DuplicateGroupPath;
import com.github.curiousoddman.curious_images.dbobj.tables.DuplicateGroupMember.DuplicateGroupMemberPath;
import com.github.curiousoddman.curious_images.dbobj.tables.Face.FacePath;
import com.github.curiousoddman.curious_images.dbobj.tables.Folder.FolderPath;
import com.github.curiousoddman.curious_images.dbobj.tables.PhotoHash.PhotoHashPath;
import com.github.curiousoddman.curious_images.dbobj.tables.Thumbnail.ThumbnailPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.PhotoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Photo extends TableImpl<PhotoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.PHOTO</code>
     */
    public static final Photo PHOTO = new Photo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PhotoRecord> getRecordType() {
        return PhotoRecord.class;
    }

    /**
     * The column <code>public.PHOTO.ID</code>.
     */
    public final TableField<PhotoRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.PHOTO.FOLDER_ID</code>.
     */
    public final TableField<PhotoRecord, Long> FOLDER_ID = createField(DSL.name("FOLDER_ID"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.PHOTO.ABSOLUTE_PATH</code>.
     */
    public final TableField<PhotoRecord, String> ABSOLUTE_PATH = createField(DSL.name("ABSOLUTE_PATH"), SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>public.PHOTO.FILENAME</code>.
     */
    public final TableField<PhotoRecord, String> FILENAME = createField(DSL.name("FILENAME"), SQLDataType.VARCHAR(512), this, "");

    /**
     * The column <code>public.PHOTO.EXTENSION</code>.
     */
    public final TableField<PhotoRecord, String> EXTENSION = createField(DSL.name("EXTENSION"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.PHOTO.FILE_SIZE</code>.
     */
    public final TableField<PhotoRecord, Long> FILE_SIZE = createField(DSL.name("FILE_SIZE"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.PHOTO.IMAGE_WIDTH</code>.
     */
    public final TableField<PhotoRecord, Integer> IMAGE_WIDTH = createField(DSL.name("IMAGE_WIDTH"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.PHOTO.IMAGE_HEIGHT</code>.
     */
    public final TableField<PhotoRecord, Integer> IMAGE_HEIGHT = createField(DSL.name("IMAGE_HEIGHT"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.PHOTO.CAPTURE_DATE</code>.
     */
    public final TableField<PhotoRecord, LocalDateTime> CAPTURE_DATE = createField(DSL.name("CAPTURE_DATE"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.PHOTO.CAPTURE_DATE_SOURCE</code>.
     */
    public final TableField<PhotoRecord, String> CAPTURE_DATE_SOURCE = createField(DSL.name("CAPTURE_DATE_SOURCE"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.PHOTO.IMPORTED_AT</code>.
     */
    public final TableField<PhotoRecord, LocalDateTime> IMPORTED_AT = createField(DSL.name("IMPORTED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.PHOTO.LAST_SEEN_AT</code>.
     */
    public final TableField<PhotoRecord, LocalDateTime> LAST_SEEN_AT = createField(DSL.name("LAST_SEEN_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.PHOTO.ORIENTATION</code>.
     */
    public final TableField<PhotoRecord, Integer> ORIENTATION = createField(DSL.name("ORIENTATION"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.PHOTO.CAMERA_MAKE</code>.
     */
    public final TableField<PhotoRecord, String> CAMERA_MAKE = createField(DSL.name("CAMERA_MAKE"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.PHOTO.CAMERA_MODEL</code>.
     */
    public final TableField<PhotoRecord, String> CAMERA_MODEL = createField(DSL.name("CAMERA_MODEL"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.PHOTO.LENS_MODEL</code>.
     */
    public final TableField<PhotoRecord, String> LENS_MODEL = createField(DSL.name("LENS_MODEL"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>public.PHOTO.EXIF_EXTRA</code>.
     */
    public final TableField<PhotoRecord, JSON> EXIF_EXTRA = createField(DSL.name("EXIF_EXTRA"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.PHOTO.GPS_LAT</code>.
     */
    public final TableField<PhotoRecord, Double> GPS_LAT = createField(DSL.name("GPS_LAT"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.PHOTO.GPS_LON</code>.
     */
    public final TableField<PhotoRecord, Double> GPS_LON = createField(DSL.name("GPS_LON"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.PHOTO.GPS_ALTITUDE</code>.
     */
    public final TableField<PhotoRecord, Double> GPS_ALTITUDE = createField(DSL.name("GPS_ALTITUDE"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.PHOTO.AI_FACE_DETECT_DONE</code>.
     */
    public final TableField<PhotoRecord, Boolean> AI_FACE_DETECT_DONE = createField(DSL.name("AI_FACE_DETECT_DONE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("FALSE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.PHOTO.AI_FACE_EMBED_DONE</code>.
     */
    public final TableField<PhotoRecord, Boolean> AI_FACE_EMBED_DONE = createField(DSL.name("AI_FACE_EMBED_DONE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("FALSE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.PHOTO.AI_CLIP_EMBED_DONE</code>.
     */
    public final TableField<PhotoRecord, Boolean> AI_CLIP_EMBED_DONE = createField(DSL.name("AI_CLIP_EMBED_DONE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("FALSE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.PHOTO.AI_LUCENE_INDEX_DONE</code>.
     */
    public final TableField<PhotoRecord, Boolean> AI_LUCENE_INDEX_DONE = createField(DSL.name("AI_LUCENE_INDEX_DONE"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("FALSE"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.PHOTO.AI_LAST_ERROR</code>.
     */
    public final TableField<PhotoRecord, String> AI_LAST_ERROR = createField(DSL.name("AI_LAST_ERROR"), SQLDataType.VARCHAR(1024), this, "");

    /**
     * The column <code>public.PHOTO.AI_RETRY_COUNT</code>.
     */
    public final TableField<PhotoRecord, Short> AI_RETRY_COUNT = createField(DSL.name("AI_RETRY_COUNT"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.PHOTO.AI_UPDATED_AT</code>.
     */
    public final TableField<PhotoRecord, LocalDateTime> AI_UPDATED_AT = createField(DSL.name("AI_UPDATED_AT"), SQLDataType.LOCALDATETIME(6), this, "");

    private Photo(Name alias, Table<PhotoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Photo(Name alias, Table<PhotoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.PHOTO</code> table reference
     */
    public Photo(String alias) {
        this(DSL.name(alias), PHOTO);
    }

    /**
     * Create an aliased <code>public.PHOTO</code> table reference
     */
    public Photo(Name alias) {
        this(alias, PHOTO);
    }

    /**
     * Create a <code>public.PHOTO</code> table reference
     */
    public Photo() {
        this(DSL.name("PHOTO"), null);
    }

    public <O extends Record> Photo(Table<O> path, ForeignKey<O, PhotoRecord> childPath, InverseForeignKey<O, PhotoRecord> parentPath) {
        super(path, childPath, parentPath, PHOTO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class PhotoPath extends Photo implements Path<PhotoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PhotoPath(Table<O> path, ForeignKey<O, PhotoRecord> childPath, InverseForeignKey<O, PhotoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PhotoPath(Name alias, Table<PhotoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PhotoPath as(String alias) {
            return new PhotoPath(DSL.name(alias), this);
        }

        @Override
        public PhotoPath as(Name alias) {
            return new PhotoPath(alias, this);
        }

        @Override
        public PhotoPath as(Table<?> alias) {
            return new PhotoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PHOTO_CAPTURE_DATE, Indexes.IDX_PHOTO_FOLDER);
    }

    @Override
    public Identity<PhotoRecord, Long> getIdentity() {
        return (Identity<PhotoRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PhotoRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    @Override
    public List<UniqueKey<PhotoRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_489);
    }

    @Override
    public List<ForeignKey<PhotoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_48);
    }

    private transient FolderPath _folder;

    /**
     * Get the implicit join path to the <code>public.FOLDER</code> table.
     */
    public FolderPath folder() {
        if (_folder == null)
            _folder = new FolderPath(this, Keys.CONSTRAINT_48, null);

        return _folder;
    }

    private transient FacePath _face;

    /**
     * Get the implicit to-many join path to the <code>public.FACE</code> table
     */
    public FacePath face() {
        if (_face == null)
            _face = new FacePath(this, null, Keys.CONSTRAINT_20C.getInverseKey());

        return _face;
    }

    private transient AlbumPath _album;

    /**
     * Get the implicit to-many join path to the <code>public.ALBUM</code> table
     */
    public AlbumPath album() {
        if (_album == null)
            _album = new AlbumPath(this, null, Keys.CONSTRAINT_3B.getInverseKey());

        return _album;
    }

    private transient PhotoHashPath _photoHash;

    /**
     * Get the implicit to-many join path to the <code>public.PHOTO_HASH</code>
     * table
     */
    public PhotoHashPath photoHash() {
        if (_photoHash == null)
            _photoHash = new PhotoHashPath(this, null, Keys.CONSTRAINT_66.getInverseKey());

        return _photoHash;
    }

    private transient AlbumPhotoPath _albumPhoto;

    /**
     * Get the implicit to-many join path to the <code>public.ALBUM_PHOTO</code>
     * table
     */
    public AlbumPhotoPath albumPhoto() {
        if (_albumPhoto == null)
            _albumPhoto = new AlbumPhotoPath(this, null, Keys.CONSTRAINT_9B2.getInverseKey());

        return _albumPhoto;
    }

    private transient ClipEmbeddingPath _clipEmbedding;

    /**
     * Get the implicit to-many join path to the
     * <code>public.CLIP_EMBEDDING</code> table
     */
    public ClipEmbeddingPath clipEmbedding() {
        if (_clipEmbedding == null)
            _clipEmbedding = new ClipEmbeddingPath(this, null, Keys.CONSTRAINT_9E.getInverseKey());

        return _clipEmbedding;
    }

    private transient DuplicateGroupMemberPath _duplicateGroupMember;

    /**
     * Get the implicit to-many join path to the
     * <code>public.DUPLICATE_GROUP_MEMBER</code> table
     */
    public DuplicateGroupMemberPath duplicateGroupMember() {
        if (_duplicateGroupMember == null)
            _duplicateGroupMember = new DuplicateGroupMemberPath(this, null, Keys.CONSTRAINT_BB01.getInverseKey());

        return _duplicateGroupMember;
    }

    private transient ThumbnailPath _thumbnail;

    /**
     * Get the implicit to-many join path to the <code>public.THUMBNAIL</code>
     * table
     */
    public ThumbnailPath thumbnail() {
        if (_thumbnail == null)
            _thumbnail = new ThumbnailPath(this, null, Keys.CONSTRAINT_F5.getInverseKey());

        return _thumbnail;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.DUPLICATE_GROUP</code> table
     */
    public DuplicateGroupPath duplicateGroup() {
        return duplicateGroupMember().duplicateGroup();
    }

    @Override
    public Photo as(String alias) {
        return new Photo(DSL.name(alias), this);
    }

    @Override
    public Photo as(Name alias) {
        return new Photo(alias, this);
    }

    @Override
    public Photo as(Table<?> alias) {
        return new Photo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Photo rename(String name) {
        return new Photo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Photo rename(Name name) {
        return new Photo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Photo rename(Table<?> name) {
        return new Photo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo where(Condition condition) {
        return new Photo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Photo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Photo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Photo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Photo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
