/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo.PhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.PhotoPreviewRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PhotoPreview extends TableImpl<PhotoPreviewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.PHOTO_PREVIEW</code>
     */
    public static final PhotoPreview PHOTO_PREVIEW = new PhotoPreview();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PhotoPreviewRecord> getRecordType() {
        return PhotoPreviewRecord.class;
    }

    /**
     * The column <code>public.PHOTO_PREVIEW.PHOTO_ID</code>.
     */
    public final TableField<PhotoPreviewRecord, Long> PHOTO_ID = createField(DSL.name("PHOTO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.PHOTO_PREVIEW.BYTES</code>.
     */
    public final TableField<PhotoPreviewRecord, byte[]> BYTES = createField(DSL.name("BYTES"), SQLDataType.VARBINARY.nullable(false), this, "");

    private PhotoPreview(Name alias, Table<PhotoPreviewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PhotoPreview(Name alias, Table<PhotoPreviewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.PHOTO_PREVIEW</code> table reference
     */
    public PhotoPreview(String alias) {
        this(DSL.name(alias), PHOTO_PREVIEW);
    }

    /**
     * Create an aliased <code>public.PHOTO_PREVIEW</code> table reference
     */
    public PhotoPreview(Name alias) {
        this(alias, PHOTO_PREVIEW);
    }

    /**
     * Create a <code>public.PHOTO_PREVIEW</code> table reference
     */
    public PhotoPreview() {
        this(DSL.name("PHOTO_PREVIEW"), null);
    }

    public <O extends Record> PhotoPreview(Table<O> path, ForeignKey<O, PhotoPreviewRecord> childPath, InverseForeignKey<O, PhotoPreviewRecord> parentPath) {
        super(path, childPath, parentPath, PHOTO_PREVIEW);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class PhotoPreviewPath extends PhotoPreview implements Path<PhotoPreviewRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PhotoPreviewPath(Table<O> path, ForeignKey<O, PhotoPreviewRecord> childPath, InverseForeignKey<O, PhotoPreviewRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PhotoPreviewPath(Name alias, Table<PhotoPreviewRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PhotoPreviewPath as(String alias) {
            return new PhotoPreviewPath(DSL.name(alias), this);
        }

        @Override
        public PhotoPreviewPath as(Name alias) {
            return new PhotoPreviewPath(alias, this);
        }

        @Override
        public PhotoPreviewPath as(Table<?> alias) {
            return new PhotoPreviewPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PhotoPreviewRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_33;
    }

    @Override
    public List<ForeignKey<PhotoPreviewRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_331);
    }

    private transient PhotoPath _photo;

    /**
     * Get the implicit join path to the <code>public.PHOTO</code> table.
     */
    public PhotoPath photo() {
        if (_photo == null)
            _photo = new PhotoPath(this, Keys.CONSTRAINT_331, null);

        return _photo;
    }

    @Override
    public PhotoPreview as(String alias) {
        return new PhotoPreview(DSL.name(alias), this);
    }

    @Override
    public PhotoPreview as(Name alias) {
        return new PhotoPreview(alias, this);
    }

    @Override
    public PhotoPreview as(Table<?> alias) {
        return new PhotoPreview(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PhotoPreview rename(String name) {
        return new PhotoPreview(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PhotoPreview rename(Name name) {
        return new PhotoPreview(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PhotoPreview rename(Table<?> name) {
        return new PhotoPreview(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoPreview where(Condition condition) {
        return new PhotoPreview(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoPreview where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoPreview where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoPreview where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoPreview where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoPreview where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoPreview where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoPreview where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoPreview whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoPreview whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
