/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Media.MediaPath;
import com.github.curiousoddman.curious_images.dbobj.tables.PhotoPreview.PhotoPreviewPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.PhotoRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Photo extends TableImpl<PhotoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.PHOTO</code>
     */
    public static final Photo PHOTO = new Photo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PhotoRecord> getRecordType() {
        return PhotoRecord.class;
    }

    /**
     * The column <code>public.PHOTO.ID</code>.
     */
    public final TableField<PhotoRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.PHOTO.IMAGE_WIDTH</code>.
     */
    public final TableField<PhotoRecord, Integer> IMAGE_WIDTH = createField(DSL.name("IMAGE_WIDTH"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.PHOTO.IMAGE_HEIGHT</code>.
     */
    public final TableField<PhotoRecord, Integer> IMAGE_HEIGHT = createField(DSL.name("IMAGE_HEIGHT"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.PHOTO.ORIENTATION</code>.
     */
    public final TableField<PhotoRecord, Integer> ORIENTATION = createField(DSL.name("ORIENTATION"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.PHOTO.LENS_MODEL</code>.
     */
    public final TableField<PhotoRecord, String> LENS_MODEL = createField(DSL.name("LENS_MODEL"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>public.PHOTO.EXIF_EXTRA</code>.
     */
    public final TableField<PhotoRecord, JSON> EXIF_EXTRA = createField(DSL.name("EXIF_EXTRA"), SQLDataType.JSON, this, "");

    private Photo(Name alias, Table<PhotoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Photo(Name alias, Table<PhotoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.PHOTO</code> table reference
     */
    public Photo(String alias) {
        this(DSL.name(alias), PHOTO);
    }

    /**
     * Create an aliased <code>public.PHOTO</code> table reference
     */
    public Photo(Name alias) {
        this(alias, PHOTO);
    }

    /**
     * Create a <code>public.PHOTO</code> table reference
     */
    public Photo() {
        this(DSL.name("PHOTO"), null);
    }

    public <O extends Record> Photo(Table<O> path, ForeignKey<O, PhotoRecord> childPath, InverseForeignKey<O, PhotoRecord> parentPath) {
        super(path, childPath, parentPath, PHOTO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class PhotoPath extends Photo implements Path<PhotoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PhotoPath(Table<O> path, ForeignKey<O, PhotoRecord> childPath, InverseForeignKey<O, PhotoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PhotoPath(Name alias, Table<PhotoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PhotoPath as(String alias) {
            return new PhotoPath(DSL.name(alias), this);
        }

        @Override
        public PhotoPath as(Name alias) {
            return new PhotoPath(alias, this);
        }

        @Override
        public PhotoPath as(Table<?> alias) {
            return new PhotoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PhotoRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_48;
    }

    @Override
    public List<ForeignKey<PhotoRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_489);
    }

    private transient MediaPath _media;

    /**
     * Get the implicit join path to the <code>public.MEDIA</code> table.
     */
    public MediaPath media() {
        if (_media == null)
            _media = new MediaPath(this, Keys.CONSTRAINT_489, null);

        return _media;
    }

    private transient PhotoPreviewPath _photoPreview;

    /**
     * Get the implicit to-many join path to the
     * <code>public.PHOTO_PREVIEW</code> table
     */
    public PhotoPreviewPath photoPreview() {
        if (_photoPreview == null)
            _photoPreview = new PhotoPreviewPath(this, null, Keys.CONSTRAINT_331.getInverseKey());

        return _photoPreview;
    }

    @Override
    public Photo as(String alias) {
        return new Photo(DSL.name(alias), this);
    }

    @Override
    public Photo as(Name alias) {
        return new Photo(alias, this);
    }

    @Override
    public Photo as(Table<?> alias) {
        return new Photo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Photo rename(String name) {
        return new Photo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Photo rename(Name name) {
        return new Photo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Photo rename(Table<?> name) {
        return new Photo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo where(Condition condition) {
        return new Photo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Photo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Photo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Photo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Photo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Photo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
