/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Photo.PhotoPath;
import com.github.curiousoddman.curious_images.dbobj.tables.TagEmbedding.TagEmbeddingPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.PhotoTagRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PhotoTag extends TableImpl<PhotoTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.PHOTO_TAG</code>
     */
    public static final PhotoTag PHOTO_TAG = new PhotoTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PhotoTagRecord> getRecordType() {
        return PhotoTagRecord.class;
    }

    /**
     * The column <code>public.PHOTO_TAG.TAG_ID</code>.
     */
    public final TableField<PhotoTagRecord, Long> TAG_ID = createField(DSL.name("TAG_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.PHOTO_TAG.PHOTO_ID</code>.
     */
    public final TableField<PhotoTagRecord, Long> PHOTO_ID = createField(DSL.name("PHOTO_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.PHOTO_TAG.TAG_SOURCE</code>.
     */
    public final TableField<PhotoTagRecord, String> TAG_SOURCE = createField(DSL.name("TAG_SOURCE"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.PHOTO_TAG.CONFIDENCE</code>.
     */
    public final TableField<PhotoTagRecord, Double> CONFIDENCE = createField(DSL.name("CONFIDENCE"), SQLDataType.DOUBLE, this, "");

    private PhotoTag(Name alias, Table<PhotoTagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PhotoTag(Name alias, Table<PhotoTagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.PHOTO_TAG</code> table reference
     */
    public PhotoTag(String alias) {
        this(DSL.name(alias), PHOTO_TAG);
    }

    /**
     * Create an aliased <code>public.PHOTO_TAG</code> table reference
     */
    public PhotoTag(Name alias) {
        this(alias, PHOTO_TAG);
    }

    /**
     * Create a <code>public.PHOTO_TAG</code> table reference
     */
    public PhotoTag() {
        this(DSL.name("PHOTO_TAG"), null);
    }

    public <O extends Record> PhotoTag(Table<O> path, ForeignKey<O, PhotoTagRecord> childPath, InverseForeignKey<O, PhotoTagRecord> parentPath) {
        super(path, childPath, parentPath, PHOTO_TAG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class PhotoTagPath extends PhotoTag implements Path<PhotoTagRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PhotoTagPath(Table<O> path, ForeignKey<O, PhotoTagRecord> childPath, InverseForeignKey<O, PhotoTagRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PhotoTagPath(Name alias, Table<PhotoTagRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PhotoTagPath as(String alias) {
            return new PhotoTagPath(DSL.name(alias), this);
        }

        @Override
        public PhotoTagPath as(Name alias) {
            return new PhotoTagPath(alias, this);
        }

        @Override
        public PhotoTagPath as(Table<?> alias) {
            return new PhotoTagPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PhotoTagRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_73A0;
    }

    @Override
    public List<ForeignKey<PhotoTagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_73, Keys.CONSTRAINT_73A);
    }

    private transient TagEmbeddingPath _tagEmbedding;

    /**
     * Get the implicit join path to the <code>public.TAG_EMBEDDING</code>
     * table.
     */
    public TagEmbeddingPath tagEmbedding() {
        if (_tagEmbedding == null)
            _tagEmbedding = new TagEmbeddingPath(this, Keys.CONSTRAINT_73, null);

        return _tagEmbedding;
    }

    private transient PhotoPath _photo;

    /**
     * Get the implicit join path to the <code>public.PHOTO</code> table.
     */
    public PhotoPath photo() {
        if (_photo == null)
            _photo = new PhotoPath(this, Keys.CONSTRAINT_73A, null);

        return _photo;
    }

    @Override
    public PhotoTag as(String alias) {
        return new PhotoTag(DSL.name(alias), this);
    }

    @Override
    public PhotoTag as(Name alias) {
        return new PhotoTag(alias, this);
    }

    @Override
    public PhotoTag as(Table<?> alias) {
        return new PhotoTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PhotoTag rename(String name) {
        return new PhotoTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PhotoTag rename(Name name) {
        return new PhotoTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PhotoTag rename(Table<?> name) {
        return new PhotoTag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoTag where(Condition condition) {
        return new PhotoTag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoTag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoTag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoTag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoTag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoTag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoTag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PhotoTag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoTag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PhotoTag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
