/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.Media.MediaPath;
import com.github.curiousoddman.curious_images.dbobj.tables.MediaTag.MediaTagPath;
import com.github.curiousoddman.curious_images.dbobj.tables.records.TagEmbeddingRecord;

import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.28",
        "schema version:none"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TagEmbedding extends TableImpl<TagEmbeddingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.TAG_EMBEDDING</code>
     */
    public static final TagEmbedding TAG_EMBEDDING = new TagEmbedding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagEmbeddingRecord> getRecordType() {
        return TagEmbeddingRecord.class;
    }

    /**
     * The column <code>public.TAG_EMBEDDING.ID</code>.
     */
    public final TableField<TagEmbeddingRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.TAG_EMBEDDING.CATEGORY</code>.
     */
    public final TableField<TagEmbeddingRecord, String> CATEGORY = createField(DSL.name("CATEGORY"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.TAG_EMBEDDING.TAG</code>.
     */
    public final TableField<TagEmbeddingRecord, String> TAG = createField(DSL.name("TAG"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.TAG_EMBEDDING.EMBEDDING</code>.
     */
    public final TableField<TagEmbeddingRecord, byte[]> EMBEDDING = createField(DSL.name("EMBEDDING"), SQLDataType.BINARY(2048), this, "");

    /**
     * The column <code>public.TAG_EMBEDDING.MODEL_VER</code>.
     */
    public final TableField<TagEmbeddingRecord, String> MODEL_VER = createField(DSL.name("MODEL_VER"), SQLDataType.VARCHAR(32), this, "");

    private TagEmbedding(Name alias, Table<TagEmbeddingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TagEmbedding(Name alias, Table<TagEmbeddingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.TAG_EMBEDDING</code> table reference
     */
    public TagEmbedding(String alias) {
        this(DSL.name(alias), TAG_EMBEDDING);
    }

    /**
     * Create an aliased <code>public.TAG_EMBEDDING</code> table reference
     */
    public TagEmbedding(Name alias) {
        this(alias, TAG_EMBEDDING);
    }

    /**
     * Create a <code>public.TAG_EMBEDDING</code> table reference
     */
    public TagEmbedding() {
        this(DSL.name("TAG_EMBEDDING"), null);
    }

    public <O extends Record> TagEmbedding(Table<O> path, ForeignKey<O, TagEmbeddingRecord> childPath, InverseForeignKey<O, TagEmbeddingRecord> parentPath) {
        super(path, childPath, parentPath, TAG_EMBEDDING);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.19.28",
            "schema version:none"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class TagEmbeddingPath extends TagEmbedding implements Path<TagEmbeddingRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TagEmbeddingPath(Table<O> path, ForeignKey<O, TagEmbeddingRecord> childPath, InverseForeignKey<O, TagEmbeddingRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TagEmbeddingPath(Name alias, Table<TagEmbeddingRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TagEmbeddingPath as(String alias) {
            return new TagEmbeddingPath(DSL.name(alias), this);
        }

        @Override
        public TagEmbeddingPath as(Name alias) {
            return new TagEmbeddingPath(alias, this);
        }

        @Override
        public TagEmbeddingPath as(Table<?> alias) {
            return new TagEmbeddingPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TagEmbeddingRecord, Long> getIdentity() {
        return (Identity<TagEmbeddingRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TagEmbeddingRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_7BE;
    }

    private transient MediaTagPath _mediaTag;

    /**
     * Get the implicit to-many join path to the <code>public.MEDIA_TAG</code>
     * table
     */
    public MediaTagPath mediaTag() {
        if (_mediaTag == null)
            _mediaTag = new MediaTagPath(this, null, Keys.CONSTRAINT_25.getInverseKey());

        return _mediaTag;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.MEDIA</code>
     * table
     */
    public MediaPath media() {
        return mediaTag().media();
    }

    @Override
    public TagEmbedding as(String alias) {
        return new TagEmbedding(DSL.name(alias), this);
    }

    @Override
    public TagEmbedding as(Name alias) {
        return new TagEmbedding(alias, this);
    }

    @Override
    public TagEmbedding as(Table<?> alias) {
        return new TagEmbedding(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TagEmbedding rename(String name) {
        return new TagEmbedding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagEmbedding rename(Name name) {
        return new TagEmbedding(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagEmbedding rename(Table<?> name) {
        return new TagEmbedding(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagEmbedding where(Condition condition) {
        return new TagEmbedding(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagEmbedding where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagEmbedding where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagEmbedding where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TagEmbedding where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TagEmbedding where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TagEmbedding where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TagEmbedding where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagEmbedding whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagEmbedding whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
