/*
 * This file is generated by jOOQ.
 */
package com.github.curiousoddman.curious_images.dbobj.tables;


import com.github.curiousoddman.curious_images.dbobj.Keys;
import com.github.curiousoddman.curious_images.dbobj.Public;
import com.github.curiousoddman.curious_images.dbobj.tables.records.UserPreferencesRecord;

import java.util.Collection;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.19.28",
                "schema version:none"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class UserPreferences extends TableImpl<UserPreferencesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.USER_PREFERENCES</code>
     */
    public static final UserPreferences USER_PREFERENCES = new UserPreferences();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserPreferencesRecord> getRecordType() {
        return UserPreferencesRecord.class;
    }

    /**
     * The column <code>public.USER_PREFERENCES.PREF_KEY</code>.
     */
    public final TableField<UserPreferencesRecord, String> PREF_KEY = createField(DSL.name("PREF_KEY"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.USER_PREFERENCES.PREF_VALUE</code>.
     */
    public final TableField<UserPreferencesRecord, String> PREF_VALUE = createField(DSL.name("PREF_VALUE"), SQLDataType.VARCHAR(255), this, "");

    private UserPreferences(Name alias, Table<UserPreferencesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserPreferences(Name alias, Table<UserPreferencesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.USER_PREFERENCES</code> table reference
     */
    public UserPreferences(String alias) {
        this(DSL.name(alias), USER_PREFERENCES);
    }

    /**
     * Create an aliased <code>public.USER_PREFERENCES</code> table reference
     */
    public UserPreferences(Name alias) {
        this(alias, USER_PREFERENCES);
    }

    /**
     * Create a <code>public.USER_PREFERENCES</code> table reference
     */
    public UserPreferences() {
        this(DSL.name("USER_PREFERENCES"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<UserPreferencesRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_2;
    }

    @Override
    public UserPreferences as(String alias) {
        return new UserPreferences(DSL.name(alias), this);
    }

    @Override
    public UserPreferences as(Name alias) {
        return new UserPreferences(alias, this);
    }

    @Override
    public UserPreferences as(Table<?> alias) {
        return new UserPreferences(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserPreferences rename(String name) {
        return new UserPreferences(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserPreferences rename(Name name) {
        return new UserPreferences(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserPreferences rename(Table<?> name) {
        return new UserPreferences(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserPreferences where(Condition condition) {
        return new UserPreferences(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserPreferences where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserPreferences where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserPreferences where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserPreferences where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserPreferences where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserPreferences where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserPreferences where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserPreferences whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserPreferences whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
