MERGE INTO tag t
    USING (
        VALUES
            ('able'),
            ('above'),
            ('absent'),
            ('absolute'),
            ('abstract'),
            ('abundant'),
            ('academic'),
            ('acceptable'),
            ('accepted'),
            ('accessible'),
            ('accurate'),
            ('accused'),
            ('active'),
            ('actual'),
            ('acute'),
            ('added'),
            ('additional'),
            ('adequate'),
            ('adjacent'),
            ('administrative'),
            ('adorable'),
            ('advanced'),
            ('adverse'),
            ('advisory'),
            ('aesthetic'),
            ('afraid'),
            ('african'),
            ('aggregate'),
            ('aggressive'),
            ('agreeable'),
            ('agreed'),
            ('agricultural'),
            ('alert'),
            ('alive'),
            ('alleged'),
            ('allied'),
            ('alone'),
            ('alright'),
            ('alternative'),
            ('amateur'),
            ('amazing'),
            ('ambitious'),
            ('american'),
            ('amused'),
            ('ancient'),
            ('angry'),
            ('annoyed'),
            ('annual'),
            ('anonymous'),
            ('anxious'),
            ('appalling'),
            ('apparent'),
            ('applicable'),
            ('appropriate'),
            ('arab'),
            ('arbitrary'),
            ('architectural'),
            ('armed'),
            ('arrogant'),
            ('artificial'),
            ('artistic'),
            ('ashamed'),
            ('asian'),
            ('asleep'),
            ('assistant'),
            ('associated'),
            ('atomic'),
            ('attractive'),
            ('australian'),
            ('automatic'),
            ('autonomous'),
            ('available'),
            ('average'),
            ('awake'),
            ('aware'),
            ('awful'),
            ('awkward'),
            ('back'),
            ('bad'),
            ('balanced'),
            ('bare'),
            ('basic'),
            ('beautiful'),
            ('beneficial'),
            ('better'),
            ('bewildered'),
            ('big'),
            ('binding'),
            ('biological'),
            ('bitter'),
            ('bizarre'),
            ('black'),
            ('blank'),
            ('blind'),
            ('blonde'),
            ('bloody'),
            ('blue'),
            ('blushing'),
            ('boiling'),
            ('bold'),
            ('bored'),
            ('boring'),
            ('bottom'),
            ('brainy'),
            ('brave'),
            ('breakable'),
            ('breezy'),
            ('brief'),
            ('bright'),
            ('brilliant'),
            ('british'),
            ('broad'),
            ('broken'),
            ('brown'),
            ('bumpy'),
            ('burning'),
            ('busy'),
            ('calm'),
            ('canadian'),
            ('capable'),
            ('capitalist'),
            ('careful'),
            ('casual'),
            ('catholic'),
            ('causal'),
            ('cautious'),
            ('central'),
            ('certain'),
            ('changing'),
            ('characteristic'),
            ('charming'),
            ('cheap'),
            ('cheerful'),
            ('chemical'),
            ('chief'),
            ('chilly'),
            ('chinese'),
            ('chosen'),
            ('christian'),
            ('chronic'),
            ('chubby'),
            ('circular'),
            ('civic'),
            ('civil'),
            ('civilian'),
            ('classic'),
            ('classical'),
            ('clean'),
            ('clear'),
            ('clever'),
            ('clinical'),
            ('close'),
            ('closed'),
            ('cloudy'),
            ('clumsy'),
            ('coastal'),
            ('cognitive'),
            ('coherent'),
            ('cold'),
            ('collective'),
            ('colonial'),
            ('colorful'),
            ('colossal'),
            ('coloured'),
            ('colourful'),
            ('combative'),
            ('combined'),
            ('comfortable'),
            ('coming'),
            ('commercial'),
            ('common'),
            ('communist'),
            ('compact'),
            ('comparable'),
            ('comparative'),
            ('compatible'),
            ('competent'),
            ('competitive'),
            ('complete'),
            ('complex'),
            ('complicated'),
            ('comprehensive'),
            ('compulsory'),
            ('conceptual'),
            ('concerned'),
            ('concrete'),
            ('condemned'),
            ('confident'),
            ('confidential'),
            ('confused'),
            ('conscious'),
            ('conservation'),
            ('conservative'),
            ('considerable'),
            ('consistent'),
            ('constant'),
            ('constitutional'),
            ('contemporary'),
            ('content'),
            ('continental'),
            ('continued'),
            ('continuing'),
            ('continuous'),
            ('controlled'),
            ('controversial'),
            ('convenient'),
            ('conventional'),
            ('convinced'),
            ('convincing'),
            ('cooing'),
            ('cool'),
            ('cooperative'),
            ('corporate'),
            ('correct'),
            ('corresponding'),
            ('costly'),
            ('courageous'),
            ('crazy'),
            ('creative'),
            ('creepy'),
            ('criminal'),
            ('critical'),
            ('crooked'),
            ('crowded'),
            ('crucial'),
            ('crude'),
            ('cruel'),
            ('cuddly'),
            ('cultural'),
            ('curious'),
            ('curly'),
            ('current'),
            ('curved'),
            ('cute'),
            ('daily'),
            ('damaged'),
            ('damp'),
            ('dangerous'),
            ('dark'),
            ('dead'),
            ('deaf'),
            ('deafening'),
            ('dear'),
            ('decent'),
            ('decisive'),
            ('deep'),
            ('defeated'),
            ('defensive'),
            ('defiant'),
            ('definite'),
            ('deliberate'),
            ('delicate'),
            ('delicious'),
            ('delighted'),
            ('delightful'),
            ('democratic'),
            ('dependent'),
            ('depressed'),
            ('desirable'),
            ('desperate'),
            ('detailed'),
            ('determined'),
            ('developed'),
            ('developing'),
            ('devoted'),
            ('different'),
            ('difficult'),
            ('digital'),
            ('diplomatic'),
            ('direct'),
            ('dirty'),
            ('disabled'),
            ('disappointed'),
            ('disastrous'),
            ('disciplinary'),
            ('disgusted'),
            ('distant'),
            ('distinct'),
            ('distinctive'),
            ('distinguished'),
            ('disturbed'),
            ('disturbing'),
            ('diverse'),
            ('divine'),
            ('dizzy'),
            ('domestic'),
            ('dominant'),
            ('double'),
            ('doubtful'),
            ('drab'),
            ('dramatic'),
            ('dreadful'),
            ('driving'),
            ('drunk'),
            ('dry'),
            ('dual'),
            ('due'),
            ('dull'),
            ('dusty'),
            ('dutch'),
            ('dying'),
            ('dynamic'),
            ('eager'),
            ('early'),
            ('eastern'),
            ('easy'),
            ('economic'),
            ('educational'),
            ('eerie'),
            ('effective'),
            ('efficient'),
            ('elaborate'),
            ('elated'),
            ('elderly'),
            ('eldest'),
            ('electoral'),
            ('electric'),
            ('electrical'),
            ('electronic'),
            ('elegant'),
            ('eligible'),
            ('embarrassed'),
            ('embarrassing'),
            ('emotional'),
            ('empirical'),
            ('empty'),
            ('enchanting'),
            ('encouraging'),
            ('endless'),
            ('energetic'),
            ('english'),
            ('enormous'),
            ('enthusiastic'),
            ('entire'),
            ('entitled'),
            ('envious'),
            ('environmental'),
            ('equal'),
            ('equivalent'),
            ('essential'),
            ('established'),
            ('estimated'),
            ('ethical'),
            ('ethnic'),
            ('european'),
            ('eventual'),
            ('everyday'),
            ('evident'),
            ('evil'),
            ('evolutionary'),
            ('exact'),
            ('excellent'),
            ('exceptional'),
            ('excess'),
            ('excessive'),
            ('excited'),
            ('exciting'),
            ('exclusive'),
            ('existing'),
            ('exotic'),
            ('expected'),
            ('expensive'),
            ('experienced'),
            ('experimental'),
            ('explicit'),
            ('extended'),
            ('extensive'),
            ('external'),
            ('extra'),
            ('extraordinary'),
            ('extreme'),
            ('exuberant'),
            ('faint'),
            ('fair'),
            ('faithful'),
            ('familiar'),
            ('famous'),
            ('fancy'),
            ('fantastic'),
            ('far'),
            ('fascinating'),
            ('fashionable'),
            ('fast'),
            ('fat'),
            ('fatal'),
            ('favourable'),
            ('favourite'),
            ('federal'),
            ('fellow'),
            ('female'),
            ('feminist'),
            ('few'),
            ('fierce'),
            ('filthy'),
            ('final'),
            ('financial'),
            ('fine'),
            ('firm'),
            ('fiscal'),
            ('fit'),
            ('fixed'),
            ('flaky'),
            ('flat'),
            ('flexible'),
            ('fluffy'),
            ('fluttering'),
            ('flying'),
            ('following'),
            ('fond'),
            ('foolish'),
            ('foreign'),
            ('formal'),
            ('formidable'),
            ('forthcoming'),
            ('fortunate'),
            ('forward'),
            ('fragile'),
            ('frail'),
            ('frantic'),
            ('free'),
            ('french'),
            ('frequent'),
            ('fresh'),
            ('friendly'),
            ('frightened'),
            ('front'),
            ('frozen'),
            ('fucking'),
            ('full'),
            ('full-time'),
            ('fun'),
            ('functional'),
            ('fundamental'),
            ('funny'),
            ('furious'),
            ('future'),
            ('fuzzy'),
            ('gastric'),
            ('gay'),
            ('general'),
            ('generous'),
            ('genetic'),
            ('gentle'),
            ('genuine'),
            ('geographical'),
            ('german'),
            ('giant'),
            ('gigantic'),
            ('given'),
            ('glad'),
            ('glamorous'),
            ('gleaming'),
            ('global'),
            ('glorious'),
            ('golden'),
            ('good'),
            ('gorgeous'),
            ('gothic'),
            ('governing'),
            ('graceful'),
            ('gradual'),
            ('grand'),
            ('grateful'),
            ('greasy'),
            ('great'),
            ('greek'),
            ('green'),
            ('grey'),
            ('grieving'),
            ('grim'),
            ('gross'),
            ('grotesque'),
            ('growing'),
            ('grubby'),
            ('grumpy'),
            ('guilty'),
            ('handicapped'),
            ('handsome'),
            ('happy'),
            ('hard'),
            ('harsh'),
            ('head'),
            ('healthy'),
            ('heavy'),
            ('helpful'),
            ('helpless'),
            ('hidden'),
            ('high'),
            ('high-pitched'),
            ('hilarious'),
            ('hissing'),
            ('historic'),
            ('historical'),
            ('hollow'),
            ('holy'),
            ('homeless'),
            ('homely'),
            ('hon'),
            ('honest'),
            ('horizontal'),
            ('horrible'),
            ('hostile'),
            ('hot'),
            ('huge'),
            ('human'),
            ('hungry'),
            ('hurt'),
            ('hushed'),
            ('husky'),
            ('icy'),
            ('ideal'),
            ('identical'),
            ('ideological'),
            ('ill'),
            ('illegal'),
            ('imaginative'),
            ('immediate'),
            ('immense'),
            ('imperial'),
            ('implicit'),
            ('important'),
            ('impossible'),
            ('impressed'),
            ('impressive'),
            ('improved'),
            ('inadequate'),
            ('inappropriate'),
            ('inc'),
            ('inclined'),
            ('increased'),
            ('increasing'),
            ('incredible'),
            ('independent'),
            ('indian'),
            ('indirect'),
            ('individual'),
            ('industrial'),
            ('inevitable'),
            ('influential'),
            ('informal'),
            ('inherent'),
            ('initial'),
            ('injured'),
            ('inland'),
            ('inner'),
            ('innocent'),
            ('innovative'),
            ('inquisitive'),
            ('instant'),
            ('institutional'),
            ('insufficient'),
            ('intact'),
            ('integral'),
            ('integrated'),
            ('intellectual'),
            ('intelligent'),
            ('intense'),
            ('intensive'),
            ('interested'),
            ('interesting'),
            ('interim'),
            ('interior'),
            ('intermediate'),
            ('internal'),
            ('international'),
            ('intimate'),
            ('invisible'),
            ('involved'),
            ('iraqi'),
            ('irish'),
            ('irrelevant'),
            ('islamic'),
            ('isolated'),
            ('israeli'),
            ('italian'),
            ('itchy'),
            ('japanese'),
            ('jealous'),
            ('jewish'),
            ('jittery'),
            ('joint'),
            ('jolly'),
            ('joyous'),
            ('judicial'),
            ('juicy'),
            ('junior'),
            ('just'),
            ('keen'),
            ('key'),
            ('kind'),
            ('known'),
            ('korean'),
            ('labour'),
            ('large'),
            ('large-scale'),
            ('late'),
            ('latin'),
            ('lazy'),
            ('leading'),
            ('left'),
            ('legal'),
            ('legislative'),
            ('legitimate'),
            ('lengthy'),
            ('lesser'),
            ('level'),
            ('lexical'),
            ('liable'),
            ('liberal'),
            ('light'),
            ('like'),
            ('likely'),
            ('limited'),
            ('linear'),
            ('linguistic'),
            ('liquid'),
            ('literary'),
            ('little'),
            ('live'),
            ('lively'),
            ('living'),
            ('local'),
            ('logical'),
            ('lonely'),
            ('long'),
            ('long-term'),
            ('loose'),
            ('lost'),
            ('loud'),
            ('lovely'),
            ('low'),
            ('loyal'),
            ('ltd'),
            ('lucky'),
            ('mad'),
            ('magenta'),
            ('magic'),
            ('magnetic'),
            ('magnificent'),
            ('magnificent '),
            ('main'),
            ('major'),
            ('male'),
            ('mammoth'),
            ('managerial'),
            ('managing'),
            ('manual'),
            ('many'),
            ('marginal'),
            ('marine'),
            ('marked'),
            ('married'),
            ('marvellous'),
            ('marxist'),
            ('mass'),
            ('massive'),
            ('mathematical'),
            ('mature'),
            ('maximum'),
            ('mean'),
            ('meaningful'),
            ('mechanical'),
            ('medical'),
            ('medieval'),
            ('melodic'),
            ('melted'),
            ('mental'),
            ('mere'),
            ('metropolitan'),
            ('mid'),
            ('middle'),
            ('middle-class'),
            ('mighty'),
            ('mild'),
            ('military'),
            ('miniature'),
            ('minimal'),
            ('minimum'),
            ('ministerial'),
            ('minor'),
            ('miserable'),
            ('misleading'),
            ('missing'),
            ('misty'),
            ('mixed'),
            ('moaning'),
            ('mobile'),
            ('moderate'),
            ('modern'),
            ('modest'),
            ('molecular'),
            ('monetary'),
            ('monthly'),
            ('moral'),
            ('motionless'),
            ('muddy'),
            ('multiple'),
            ('mushy'),
            ('musical'),
            ('mute'),
            ('mutual'),
            ('mysterious'),
            ('naked'),
            ('narrow'),
            ('nasty'),
            ('national'),
            ('native'),
            ('natural'),
            ('naughty'),
            ('naval'),
            ('near'),
            ('nearby'),
            ('neat'),
            ('necessary'),
            ('negative'),
            ('neighbouring'),
            ('nervous'),
            ('net'),
            ('neutral'),
            ('new'),
            ('nice'),
            ('nineteenth-century'),
            ('noble'),
            ('noisy'),
            ('normal'),
            ('northern'),
            ('nosy'),
            ('notable'),
            ('novel'),
            ('nuclear'),
            ('numerous'),
            ('nursing'),
            ('nutritious'),
            ('nutty'),
            ('obedient'),
            ('objective'),
            ('obliged'),
            ('obnoxious'),
            ('obvious'),
            ('occasional'),
            ('occupational'),
            ('odd'),
            ('official'),
            ('ok'),
            ('okay'),
            ('old'),
            ('old-fashioned'),
            ('olympic'),
            ('only'),
            ('open'),
            ('operational'),
            ('opposite'),
            ('optimistic'),
            ('oral'),
            ('orange'),
            ('ordinary'),
            ('organic'),
            ('organisational'),
            ('original'),
            ('orthodox'),
            ('other'),
            ('outdoor'),
            ('outer'),
            ('outrageous'),
            ('outside'),
            ('outstanding'),
            ('overall'),
            ('overseas'),
            ('overwhelming'),
            ('painful'),
            ('pale'),
            ('palestinian'),
            ('panicky'),
            ('parallel'),
            ('parental'),
            ('parliamentary'),
            ('part-time'),
            ('partial'),
            ('particular'),
            ('passing'),
            ('passive'),
            ('past'),
            ('patient'),
            ('payable'),
            ('peaceful'),
            ('peculiar'),
            ('perfect'),
            ('permanent'),
            ('persistent'),
            ('personal'),
            ('petite'),
            ('philosophical'),
            ('physical'),
            ('pink'),
            ('plain'),
            ('planned'),
            ('plastic'),
            ('pleasant'),
            ('pleased'),
            ('poised'),
            ('polish'),
            ('polite'),
            ('political'),
            ('poor'),
            ('popular'),
            ('positive'),
            ('possible'),
            ('post-war'),
            ('potential'),
            ('powerful'),
            ('practical'),
            ('precious'),
            ('precise'),
            ('preferred'),
            ('pregnant'),
            ('preliminary'),
            ('premier'),
            ('prepared'),
            ('present'),
            ('presidential'),
            ('pretty'),
            ('previous'),
            ('prickly'),
            ('primary'),
            ('prime'),
            ('primitive'),
            ('principal'),
            ('printed'),
            ('prior'),
            ('private'),
            ('probable'),
            ('productive'),
            ('professional'),
            ('profitable'),
            ('profound'),
            ('progressive'),
            ('prominent'),
            ('promising'),
            ('proper'),
            ('proposed'),
            ('prospective'),
            ('protective'),
            ('protestant'),
            ('proud'),
            ('provincial'),
            ('psychiatric'),
            ('psychological'),
            ('public'),
            ('puny'),
            ('pure'),
            ('purple'),
            ('purring'),
            ('puzzled'),
            ('quaint'),
            ('qualified'),
            ('quick'),
            ('quickest'),
            ('quiet'),
            ('racial'),
            ('radical'),
            ('rainy'),
            ('random'),
            ('rapid'),
            ('rare'),
            ('raspy'),
            ('rational'),
            ('ratty'),
            ('raw'),
            ('ready'),
            ('real'),
            ('realistic'),
            ('rear'),
            ('reasonable'),
            ('recent'),
            ('red'),
            ('reduced'),
            ('redundant'),
            ('regional'),
            ('registered'),
            ('regular'),
            ('regulatory'),
            ('related'),
            ('relative'),
            ('relaxed'),
            ('relevant'),
            ('reliable'),
            ('relieved'),
            ('religious'),
            ('reluctant'),
            ('remaining'),
            ('remarkable'),
            ('remote'),
            ('renewed'),
            ('representative'),
            ('repulsive'),
            ('required'),
            ('resident'),
            ('residential'),
            ('resonant'),
            ('respectable'),
            ('respective'),
            ('responsible'),
            ('resulting'),
            ('retail'),
            ('retired'),
            ('revolutionary'),
            ('rich'),
            ('ridiculous'),
            ('right'),
            ('rigid'),
            ('ripe'),
            ('rising'),
            ('rival'),
            ('roasted'),
            ('robust'),
            ('rolling'),
            ('roman'),
            ('romantic'),
            ('rotten'),
            ('rough'),
            ('round'),
            ('royal'),
            ('rubber'),
            ('rude'),
            ('ruling'),
            ('running'),
            ('rural'),
            ('russian'),
            ('sacred'),
            ('sad'),
            ('safe'),
            ('salty'),
            ('satisfactory'),
            ('satisfied'),
            ('scared'),
            ('scary'),
            ('scattered'),
            ('scientific'),
            ('scornful'),
            ('scottish'),
            ('scrawny'),
            ('screeching'),
            ('secondary'),
            ('secret'),
            ('secure'),
            ('select'),
            ('selected'),
            ('selective'),
            ('selfish'),
            ('semantic'),
            ('senior'),
            ('sensible'),
            ('sensitive'),
            ('separate'),
            ('serious'),
            ('severe'),
            ('sexual'),
            ('shaggy'),
            ('shaky'),
            ('shallow'),
            ('shared'),
            ('sharp'),
            ('sheer'),
            ('shiny'),
            ('shivering'),
            ('shocked'),
            ('short'),
            ('short-term'),
            ('shrill'),
            ('shy'),
            ('sick'),
            ('significant'),
            ('silent'),
            ('silky'),
            ('silly'),
            ('similar'),
            ('simple'),
            ('single'),
            ('skilled'),
            ('skinny'),
            ('sleepy'),
            ('slight'),
            ('slim'),
            ('slimy'),
            ('slippery'),
            ('slow'),
            ('small'),
            ('smart'),
            ('smiling'),
            ('smoggy'),
            ('smooth'),
            ('so-called'),
            ('social'),
            ('socialist'),
            ('soft'),
            ('solar'),
            ('sole'),
            ('solid'),
            ('sophisticated'),
            ('sore'),
            ('sorry'),
            ('sound'),
            ('sour'),
            ('southern'),
            ('soviet'),
            ('spanish'),
            ('spare'),
            ('sparkling'),
            ('spatial'),
            ('special'),
            ('specific'),
            ('specified'),
            ('spectacular'),
            ('spicy'),
            ('spiritual'),
            ('splendid'),
            ('spontaneous'),
            ('sporting'),
            ('spotless'),
            ('spotty'),
            ('square'),
            ('squealing'),
            ('stable'),
            ('stale'),
            ('standard'),
            ('static'),
            ('statistical'),
            ('statutory'),
            ('steady'),
            ('steep'),
            ('sticky'),
            ('stiff'),
            ('still'),
            ('stingy'),
            ('stormy'),
            ('straight'),
            ('straightforward'),
            ('strange'),
            ('strategic'),
            ('strict'),
            ('striking'),
            ('striped'),
            ('strong'),
            ('structural'),
            ('stuck'),
            ('stupid'),
            ('subjective'),
            ('subsequent'),
            ('substantial'),
            ('subtle'),
            ('successful'),
            ('successive'),
            ('sudden'),
            ('sufficient'),
            ('suitable'),
            ('sunny'),
            ('super'),
            ('superb'),
            ('superior'),
            ('supporting'),
            ('supposed'),
            ('supreme'),
            ('sure'),
            ('surprised'),
            ('surprising'),
            ('surrounding'),
            ('surviving'),
            ('suspicious'),
            ('sweet'),
            ('swift'),
            ('swiss'),
            ('symbolic'),
            ('sympathetic'),
            ('systematic'),
            ('tall'),
            ('tame'),
            ('tan'),
            ('tart'),
            ('tasteless'),
            ('tasty'),
            ('technical'),
            ('technological'),
            ('teenage'),
            ('temporary'),
            ('tender'),
            ('tense'),
            ('terrible'),
            ('territorial'),
            ('testy'),
            ('then'),
            ('theoretical'),
            ('thick'),
            ('thin'),
            ('thirsty'),
            ('thorough'),
            ('thoughtful'),
            ('thoughtless'),
            ('thundering'),
            ('tight'),
            ('tiny'),
            ('tired'),
            ('top'),
            ('tory'),
            ('total'),
            ('tough'),
            ('toxic'),
            ('traditional'),
            ('tragic'),
            ('tremendous'),
            ('tricky'),
            ('tropical'),
            ('troubled'),
            ('turkish'),
            ('typical'),
            ('ugliest'),
            ('ugly'),
            ('ultimate'),
            ('unable'),
            ('unacceptable'),
            ('unaware'),
            ('uncertain'),
            ('unchanged'),
            ('uncomfortable'),
            ('unconscious'),
            ('underground'),
            ('underlying'),
            ('unemployed'),
            ('uneven'),
            ('unexpected'),
            ('unfair'),
            ('unfortunate'),
            ('unhappy'),
            ('uniform'),
            ('uninterested'),
            ('unique'),
            ('united'),
            ('universal'),
            ('unknown'),
            ('unlikely'),
            ('unnecessary'),
            ('unpleasant'),
            ('unsightly'),
            ('unusual'),
            ('unwilling'),
            ('upper'),
            ('upset'),
            ('uptight'),
            ('urban'),
            ('urgent'),
            ('used'),
            ('useful'),
            ('useless'),
            ('usual'),
            ('vague'),
            ('valid'),
            ('valuable'),
            ('variable'),
            ('varied'),
            ('various'),
            ('varying'),
            ('vast'),
            ('verbal'),
            ('vertical'),
            ('very'),
            ('victorian'),
            ('victorious'),
            ('video-taped'),
            ('violent'),
            ('visible'),
            ('visiting'),
            ('visual'),
            ('vital'),
            ('vivacious'),
            ('vivid'),
            ('vocational'),
            ('voiceless'),
            ('voluntary'),
            ('vulnerable'),
            ('wandering'),
            ('warm'),
            ('wasteful'),
            ('watery'),
            ('weak'),
            ('wealthy'),
            ('weary'),
            ('wee'),
            ('weekly'),
            ('weird'),
            ('welcome'),
            ('well'),
            ('well-known'),
            ('welsh'),
            ('western'),
            ('wet'),
            ('whispering'),
            ('white'),
            ('whole'),
            ('wicked'),
            ('wide'),
            ('wide-eyed'),
            ('widespread'),
            ('wild'),
            ('willing'),
            ('wise'),
            ('witty'),
            ('wonderful'),
            ('wooden'),
            ('working'),
            ('working-class'),
            ('worldwide'),
            ('worried'),
            ('worrying'),
            ('worthwhile'),
            ('worthy'),
            ('written'),
            ('wrong'),
            ('yellow'),
            ('young'),
            ('yummy'),
            ('zany'),
            ('zealous'),
            ('aardvark'),
            ('albatross'),
            ('alligator'),
            ('alpaca'),
            ('american bison'),
            ('ant'),
            ('anteater'),
            ('antelope'),
            ('ape'),
            ('armadillo'),
            ('baboon'),
            ('badger'),
            ('barracuda'),
            ('bat'),
            ('bear'),
            ('beaver'),
            ('bee'),
            ('boar'),
            ('buffalo'),
            ('butterfly'),
            ('camel'),
            ('caribou'),
            ('cat'),
            ('caterpillar'),
            ('cattle'),
            ('chamois'),
            ('cheetah'),
            ('chicken'),
            ('chimpanzee'),
            ('chinchilla'),
            ('chough'),
            ('clam'),
            ('cobra'),
            ('cockroach'),
            ('cod'),
            ('cormorant'),
            ('coyote'),
            ('crab'),
            ('crane'),
            ('crocodile'),
            ('crow'),
            ('curlew'),
            ('deer'),
            ('dinosaur'),
            ('dog'),
            ('dogfish'),
            ('dolphin'),
            ('donkey'),
            ('dotterel'),
            ('dove'),
            ('dragonfly'),
            ('duck'),
            ('dugong'),
            ('dunlin'),
            ('eagle'),
            ('echidna'),
            ('eel'),
            ('eland'),
            ('elephant'),
            ('elephant seal'),
            ('elk'),
            ('emu'),
            ('falcon'),
            ('ferret'),
            ('finch'),
            ('fish'),
            ('flamingo'),
            ('fly'),
            ('fox'),
            ('frog'),
            ('gaur'),
            ('gazelle'),
            ('gerbil'),
            ('giant panda'),
            ('giraffe'),
            ('gnat'),
            ('gnu'),
            ('goat'),
            ('goldfinch'),
            ('goldfish'),
            ('goose'),
            ('gorilla'),
            ('goshawk'),
            ('grasshopper'),
            ('grouse'),
            ('guanaco'),
            ('guinea fowl'),
            ('guinea pig'),
            ('gull'),
            ('hamster'),
            ('hare'),
            ('hawk'),
            ('hedgehog'),
            ('heron'),
            ('herring'),
            ('hippopotamus'),
            ('hornet'),
            ('horse'),
            ('hummingbird'),
            ('hyena'),
            ('jackal'),
            ('jaguar'),
            ('jay'),
            ('jellyfish'),
            ('kangaroo'),
            ('koala'),
            ('komodo dragon'),
            ('kouprey'),
            ('kudu'),
            ('lapwing'),
            ('lark'),
            ('lemur'),
            ('leopard'),
            ('lion'),
            ('llama'),
            ('lobster'),
            ('locust'),
            ('loris'),
            ('louse'),
            ('lyrebird'),
            ('magpie'),
            ('mallard'),
            ('manatee'),
            ('marten'),
            ('meerkat'),
            ('mink'),
            ('mole'),
            ('monkey'),
            ('moose'),
            ('mosquito'),
            ('mouse'),
            ('mule'),
            ('narwhal'),
            ('newt'),
            ('nightingale'),
            ('octopus'),
            ('okapi'),
            ('opossum'),
            ('oryx'),
            ('ostrich'),
            ('otter'),
            ('owl'),
            ('ox'),
            ('oyster'),
            ('panther'),
            ('parrot'),
            ('partridge'),
            ('peafowl'),
            ('pelican'),
            ('penguin'),
            ('pheasant'),
            ('pig'),
            ('pigeon'),
            ('pony'),
            ('porcupine'),
            ('porpoise'),
            ('prairie dog'),
            ('quail'),
            ('quelea'),
            ('rabbit'),
            ('raccoon'),
            ('rail'),
            ('ram'),
            ('rat'),
            ('raven'),
            ('red deer'),
            ('red panda'),
            ('reindeer'),
            ('rhinoceros'),
            ('rook'),
            ('ruff'),
            ('salamander'),
            ('salmon'),
            ('sand dollar'),
            ('sandpiper'),
            ('sardine'),
            ('scorpion'),
            ('sea lion'),
            ('sea urchin'),
            ('seahorse'),
            ('seal'),
            ('shark'),
            ('sheep'),
            ('shrew'),
            ('skunk'),
            ('snail'),
            ('snake'),
            ('spider'),
            ('squid'),
            ('squirrel'),
            ('starling'),
            ('stingray'),
            ('stinkbug'),
            ('stork'),
            ('swallow'),
            ('swan'),
            ('tapir'),
            ('tarsier'),
            ('termite'),
            ('tiger'),
            ('toad'),
            ('trout'),
            ('turkey'),
            ('turtle'),
            ('viper'),
            ('vulture'),
            ('wallaby'),
            ('walrus'),
            ('wasp'),
            ('weasel'),
            ('whale'),
            ('wolf'),
            ('wolverine'),
            ('wombat'),
            ('woodpecker'),
            ('worm'),
            ('wren'),
            ('yak'),
            ('zebra'),
            ('baby grow'),
            ('ball gown'),
            ('belt'),
            ('bikini'),
            ('blazer'),
            ('blouse'),
            ('boots'),
            ('bow tie'),
            ('boxers'),
            ('bra'),
            ('bra & knicker set'),
            ('briefs'),
            ('camisole'),
            ('cap'),
            ('cardigan'),
            ('cargos'),
            ('catsuit'),
            ('chemise'),
            ('coat'),
            ('corset'),
            ('cravat'),
            ('cufflinks'),
            ('cummerbund'),
            ('dinner jacket'),
            ('dress'),
            ('dressing gown'),
            ('dungarees'),
            ('fleece'),
            ('gloves'),
            ('hat'),
            ('hoody'),
            ('jacket'),
            ('jeans'),
            ('jogging suit'),
            ('jumper'),
            ('kaftan'),
            ('kilt'),
            ('knickers'),
            ('kurta'),
            ('lingerie'),
            ('nightgown'),
            ('nightwear'),
            ('pants'),
            ('pashmina'),
            ('polo shirt'),
            ('poncho'),
            ('pyjamas'),
            ('raincoat'),
            ('robe'),
            ('romper'),
            ('sandals'),
            ('sarong'),
            ('scarf'),
            ('shawl'),
            ('shellsuit'),
            ('shirt'),
            ('shoes'),
            ('shorts'),
            ('skirt'),
            ('slacks'),
            ('slippers'),
            ('socks'),
            ('stockings'),
            ('suit'),
            ('sunglasses'),
            ('sweater'),
            ('sweatshirt'),
            ('swimming costume'),
            ('swimming shorts'),
            ('swimming trunks'),
            ('swimwear'),
            ('t-shirt'),
            ('tailcoat'),
            ('tankini'),
            ('thong'),
            ('tie'),
            ('tights'),
            ('tracksuit'),
            ('trainers'),
            ('trousers'),
            ('underclothes'),
            ('underpants'),
            ('undershirt'),
            ('underwear'),
            ('vest'),
            ('vest underwear'),
            ('waistcoat'),
            ('waterproof'),
            ('zip'),
            ('arrangement'),
            ('bag'),
            ('balloon'),
            ('barrel'),
            ('beaker'),
            ('bottle'),
            ('bowl'),
            ('box'),
            ('briefcase'),
            ('bucket'),
            ('cabinet'),
            ('can'),
            ('case'),
            ('chest'),
            ('clutch'),
            ('cup'),
            ('display'),
            ('drawer'),
            ('flask'),
            ('glass'),
            ('globe'),
            ('heap'),
            ('jar'),
            ('mug'),
            ('pail'),
            ('pile'),
            ('pit'),
            ('pouch'),
            ('purse'),
            ('roll'),
            ('tray'),
            ('trunk'),
            ('tube'),
            ('valise'),
            ('vase'),
            ('wallet'),
            ('wrapper'),
            ('wrapping'),
            ('acorn'),
            ('apple'),
            ('bag of cotton balls'),
            ('bag of popcorn'),
            ('bag of rubber bands'),
            ('ball of yarn'),
            ('banana'),
            ('bananas'),
            ('bandana'),
            ('bangle bracelet'),
            ('bar of soap'),
            ('baseball'),
            ('baseball bat'),
            ('baseball hat'),
            ('basketball'),
            ('beaded bracelet'),
            ('beaded necklace'),
            ('bed'),
            ('beef'),
            ('bell'),
            ('blowdryer'),
            ('bonesaw'),
            ('book'),
            ('book of jokes'),
            ('book of matches'),
            ('bookmark'),
            ('boom box'),
            ('bottle cap'),
            ('bottle of glue'),
            ('bottle of honey'),
            ('bottle of ink'),
            ('bottle of lotion'),
            ('bottle of nail polish'),
            ('bottle of oil'),
            ('bottle of paint'),
            ('bottle of perfume'),
            ('bottle of pills'),
            ('bottle of soda'),
            ('bottle of sunscreen'),
            ('bottle of syrup'),
            ('bottle of water'),
            ('bouquet of flowers'),
            ('bow'),
            ('box of baking soda'),
            ('box of chalk'),
            ('box of chocolates'),
            ('box of crayons'),
            ('box of markers'),
            ('box of q-tips'),
            ('box of tissues'),
            ('bracelet'),
            ('bread'),
            ('broccoli'),
            ('brush'),
            ('buckle'),
            ('butter knife'),
            ('button'),
            ('camera'),
            ('can of beans'),
            ('can of chili'),
            ('can of peas'),
            ('can of whipped cream'),
            ('candle'),
            ('candlestick'),
            ('candy bar'),
            ('candy cane'),
            ('candy wrapper'),
            ('canteen'),
            ('canvas'),
            ('car'),
            ('card'),
            ('carrot'),
            ('carrots'),
            ('cars'),
            ('carton of ice cream'),
            ('catalogue'),
            ('cd'),
            ('cell phone'),
            ('cellphone'),
            ('cement stone'),
            ('chain'),
            ('chair'),
            ('chalk'),
            ('chapter book'),
            ('check book'),
            ('chenille stick'),
            ('children''s book'),
            ('chocolate'),
            ('christmas ornament'),
            ('class ring'),
            ('clay pot'),
            ('clock'),
            ('clothes'),
            ('clothes pin'),
            ('coffee mug'),
            ('coffee pot'),
            ('comb'),
            ('comic book'),
            ('computer'),
            ('conditioner'),
            ('container of pudding'),
            ('cookie jar'),
            ('cookie tin'),
            ('cork'),
            ('couch'),
            ('cow'),
            ('cowboy hat'),
            ('craft book'),
            ('credit card'),
            ('crowbar'),
            ('cucumber'),
            ('dagger'),
            ('deodorant'),
            ('desk'),
            ('dictionary'),
            ('domino set'),
            ('door'),
            ('drill press'),
            ('egg'),
            ('egg beater'),
            ('egg timer'),
            ('empty bottle'),
            ('empty jar'),
            ('empty tin can'),
            ('eraser'),
            ('extension cord'),
            ('eye liner'),
            ('face wash'),
            ('fake flowers'),
            ('feather'),
            ('feather duster'),
            ('few batteries'),
            ('fishing hook'),
            ('flag'),
            ('flashlight'),
            ('floor'),
            ('flowers'),
            ('flyswatter'),
            ('food'),
            ('football'),
            ('fork'),
            ('fridge'),
            ('frying pan'),
            ('game cartridge'),
            ('game cd'),
            ('garden spade'),
            ('glasses'),
            ('glow stick'),
            ('grid paper'),
            ('grocery list'),
            ('hair brush'),
            ('hair clip'),
            ('hair pin'),
            ('hair ribbon'),
            ('hair tie'),
            ('hammer'),
            ('hand bag'),
            ('hand fan'),
            ('hand mirror'),
            ('handbasket'),
            ('handful of change'),
            ('handheld game system'),
            ('hanger'),
            ('harmonica'),
            ('helmet'),
            ('house'),
            ('ice cream stick'),
            ('ice cube'),
            ('ice pick'),
            ('incense holder'),
            ('ipod'),
            ('ipod charger'),
            ('jar of jam'),
            ('jar of peanut butter'),
            ('jar of pickles'),
            ('jigsaw puzzle'),
            ('key chain'),
            ('keyboard'),
            ('keychain'),
            ('keys'),
            ('kitchen knife'),
            ('knife'),
            ('lace'),
            ('ladle'),
            ('lamp'),
            ('lamp shade'),
            ('laser pointer'),
            ('leg warmers'),
            ('lemon'),
            ('letter opener'),
            ('light bulb'),
            ('lighter'),
            ('lime'),
            ('lip gloss'),
            ('locket'),
            ('lotion'),
            ('magazine'),
            ('magnet'),
            ('magnifying glass'),
            ('map'),
            ('marble'),
            ('martini glass'),
            ('matchbook'),
            ('microphone'),
            ('milk'),
            ('miniature portrait'),
            ('mirror'),
            ('mobile phone'),
            ('model car'),
            ('money'),
            ('monitor'),
            ('mop'),
            ('mouse pad'),
            ('mp3 player'),
            ('multitool'),
            ('music cd'),
            ('nail'),
            ('nail clippers'),
            ('nail filer'),
            ('necktie'),
            ('needle'),
            ('notebook'),
            ('notepad'),
            ('ocarina'),
            ('outlet'),
            ('pack of cards'),
            ('package of crisp and crunchy edibles'),
            ('package of glitter'),
            ('packet of seeds'),
            ('paint brush'),
            ('paintbrush'),
            ('pair of binoculars'),
            ('pair of dice'),
            ('pair of earrings'),
            ('pair of glasses'),
            ('pair of handcuffs'),
            ('pair of knitting needles'),
            ('pair of rubber gloves'),
            ('pair of safety goggles'),
            ('pair of scissors'),
            ('pair of socks'),
            ('pair of sunglasses'),
            ('pair of tongs'),
            ('pair of water goggles'),
            ('panda'),
            ('paper'),
            ('paperclip'),
            ('pasta strainer'),
            ('pearl necklace'),
            ('pen'),
            ('pencil'),
            ('pencil holder'),
            ('pepper shaker'),
            ('perfume'),
            ('phone'),
            ('photo album'),
            ('picture frame'),
            ('piece of gum'),
            ('pillow'),
            ('pinecone'),
            ('plastic fork'),
            ('plate'),
            ('plush bear'),
            ('plush cat'),
            ('plush dinosaur'),
            ('plush dog'),
            ('plush frog'),
            ('plush octopus'),
            ('plush pony'),
            ('plush rabbit'),
            ('plush unicorn'),
            ('pocketknife'),
            ('pocketwatch'),
            ('pool stick'),
            ('pop can'),
            ('postage stamp'),
            ('puddle'),
            ('purse/bag'),
            ('quartz crystal'),
            ('quilt'),
            ('radio'),
            ('rhino'),
            ('ring'),
            ('rock'),
            ('roll of duct tape'),
            ('roll of gauze'),
            ('roll of masking tape'),
            ('roll of stickers'),
            ('roll of toilet paper'),
            ('rolling pin'),
            ('rope'),
            ('rubber band'),
            ('rubber duck'),
            ('rubber stamp'),
            ('rug'),
            ('rusty nail'),
            ('safety pin'),
            ('sailboat'),
            ('salt shaker'),
            ('sand paper'),
            ('sandal'),
            ('sandglass'),
            ('scallop shell'),
            ('scotch tape'),
            ('screw'),
            ('screwdriver'),
            ('seat belt'),
            ('shampoo'),
            ('sharpie'),
            ('sheet of paper'),
            ('shirt button'),
            ('shoe lace'),
            ('shopping bag'),
            ('shovel'),
            ('sidewalk'),
            ('sketch pad'),
            ('slipper'),
            ('small pouch'),
            ('snail shell'),
            ('snowglobe'),
            ('soap'),
            ('soccer ball'),
            ('sofa'),
            ('spatula'),
            ('speakers'),
            ('spectacles'),
            ('spice bottle'),
            ('sponge'),
            ('spool of ribbon'),
            ('spool of string'),
            ('spool of thread'),
            ('spool of wire'),
            ('spoon'),
            ('spring'),
            ('squirt gun'),
            ('statuette'),
            ('steak knife'),
            ('stick'),
            ('stick of incense'),
            ('sticker book'),
            ('sticky note'),
            ('stop sign'),
            ('straw'),
            ('street lights'),
            ('sun glasses'),
            ('sword'),
            ('table'),
            ('tea cup'),
            ('tea pot'),
            ('teddies'),
            ('television'),
            ('tennis ball'),
            ('tennis racket'),
            ('thermometer'),
            ('thimble'),
            ('thread'),
            ('tire swing'),
            ('tissue box'),
            ('toe ring'),
            ('toilet'),
            ('toilet paper tube'),
            ('tomato'),
            ('tooth pick'),
            ('toothbrush'),
            ('toothpaste'),
            ('toothpick'),
            ('towel'),
            ('toy boat'),
            ('toy car'),
            ('toy plane'),
            ('toy robot'),
            ('toy soldier'),
            ('toy top'),
            ('trash bag'),
            ('tree'),
            ('trucks'),
            ('tube of lip balm'),
            ('tube of lipstick'),
            ('tv'),
            ('tweezers'),
            ('twister'),
            ('umbrella'),
            ('video games'),
            ('washcloth'),
            ('washing machine'),
            ('watch'),
            ('water'),
            ('water bottle'),
            ('wedding ring'),
            ('whip'),
            ('whistle'),
            ('white out'),
            ('window'),
            ('wine glass'),
            ('wireless control'),
            ('wishbone'),
            ('wooden spoon'),
            ('word search'),
            ('wrench'),
            ('wristwatch'),
            ('zipper'),
            ('agent'),
            ('agt'),
            ('apprentice'),
            ('baker'),
            ('banker'),
            ('barber'),
            ('blacksmith'),
            ('boarding-house keeper'),
            ('book binder'),
            ('book keeper'),
            ('bookbinder'),
            ('brewer'),
            ('broker'),
            ('butcher'),
            ('cabinet maker'),
            ('carpenter'),
            ('carriage builder'),
            ('carriage maker'),
            ('cigar maker'),
            ('city'),
            ('clergy'),
            ('clergyman'),
            ('clerk'),
            ('clothing cutter'),
            ('coachman'),
            ('conductor'),
            ('cook'),
            ('cooper'),
            ('currier'),
            ('dealer'),
            ('dentist'),
            ('domestic servant'),
            ('dress maker'),
            ('dressmaker'),
            ('engineer'),
            ('express driver'),
            ('express man'),
            ('farmer'),
            ('fireman'),
            ('fisherman'),
            ('foreman'),
            ('gardener'),
            ('gas fitter'),
            ('grocer'),
            ('hairdresser'),
            ('harness maker'),
            ('home'),
            ('hostler'),
            ('hotel keeper'),
            ('huckster'),
            ('iron moulder'),
            ('jeweler'),
            ('journalist'),
            ('laborer'),
            ('laundress'),
            ('laundry'),
            ('lawyer'),
            ('leisure'),
            ('livery'),
            ('lodging house keeper'),
            ('machinist'),
            ('manufacturer'),
            ('marble cutter'),
            ('mason'),
            ('merchant'),
            ('milkman'),
            ('milliner'),
            ('music teacher'),
            ('musician'),
            ('painter'),
            ('peddler'),
            ('physician'),
            ('piano maker'),
            ('plumber'),
            ('police'),
            ('policeman'),
            ('printer'),
            ('restaurant keeper'),
            ('sailor'),
            ('salesman'),
            ('saloon keeper'),
            ('school'),
            ('seamstress'),
            ('servant'),
            ('shoe maker'),
            ('shoemaker'),
            ('stable keeper'),
            ('stone cutter'),
            ('tailor'),
            ('tailoress'),
            ('teacher'),
            ('teamster'),
            ('telegraph'),
            ('trader'),
            ('upholsterer'),
            ('varnisher'),
            ('waiter'),
            ('wheelwrights'),
            ('works')
        ) AS src(tag)
ON t.tag = src.tag
WHEN NOT MATCHED THEN
    INSERT (tag)
    VALUES (src.tag);