CREATE TABLE person
(
    id             BIGSERIAL PRIMARY KEY,
    name           VARCHAR(256), -- user-assigned; NULL until named
    cover_face_id  BIGINT,       -- FK to face(id), nullable
    date_of_birth  DATE,
    notes          TEXT,
    created_at     TIMESTAMP NOT NULL,
    updated_at     TIMESTAMP,
    merged_into_id BIGINT    NULL REFERENCES person (id)
);

CREATE TABLE cluster
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id          BIGINT    NOT NULL REFERENCES person (id),
    centroid_embedding BYTEA     NOT NULL, -- same encoding as face_embedding.embedding (raw float32 LE bytes)
    member_count       INT       NOT NULL DEFAULT 0,
    created_at         TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP NULL
);

CREATE INDEX idx_cluster_person_id ON cluster (person_id);

CREATE TABLE face
(
    id                      BIGSERIAL PRIMARY KEY,
    cluster_id              BIGINT    NULL REFERENCES cluster (id),
    media_id                BIGINT    NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    frame_offset_ms         BIGINT,             -- NULL for photos; sampled-frame timestamp for videos
    bbox_x                  FLOAT     NOT NULL, -- normalised [0,1] relative to image width
    bbox_y                  FLOAT     NOT NULL,
    bbox_w                  FLOAT     NOT NULL,
    bbox_h                  FLOAT     NOT NULL,
    confidence              FLOAT     NOT NULL,
    landmark_left_eye_x     FLOAT,
    landmark_left_eye_y     FLOAT,
    landmark_right_eye_x    FLOAT,
    landmark_right_eye_y    FLOAT,
    landmark_nose_x         FLOAT,
    landmark_nose_y         FLOAT,
    landmark_left_mouth_x   FLOAT,
    landmark_left_mouth_y   FLOAT,
    landmark_right_mouth_x  FLOAT,
    landmark_right_mouth_y  FLOAT,
    created_at              TIMESTAMP NOT NULL,
    thumbnail_absolute_path VARCHAR(2048),
    assignment_locked       BOOLEAN   NOT NULL DEFAULT FALSE,
    excluded                BOOLEAN   NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_face_media ON face (media_id);
CREATE INDEX idx_face_cluster_id ON face (cluster_id);


-- ArcFace 512-dim float32 embedding, stored as raw bytes (512 * 4 = 2048 bytes).
-- Kept separate from FACE to avoid widening the row used in queries that don't need it.
CREATE TABLE face_embedding
(
    face_id   BIGINT PRIMARY KEY REFERENCES face (id) ON DELETE CASCADE,
    embedding BINARY(2048) NOT NULL, -- float32[512], L2-normalised
    model_ver VARCHAR(32)  NOT NULL  -- e.g. "arcface_r50"
);

