-- Design notes (see face-person-correction-requirements.md for the full rationale):
--   * A face's owning person is no longer stored directly (no more face.person_id).
--     Instead, face.cluster_id points at a `cluster` row (one row per clustering group,
--     i.e. what the requirements doc calls a "prototype"), and cluster.person_id points at
--     the owning person. This makes FR4 (merge) a single UPDATE on `cluster`, with no need to
--     touch individual face rows or chase redirects when resolving "who is this face".
--   * face.cluster_id = NULL means "not yet clustered" (the old "Unknown" bucket). There is no
--     longer a shared placeholder Person for this — an unclustered face is identified purely by
--     having no cluster, so PersonRepository.findOrCreateUnknown() and friends go away.
--   * person.merged_into_id is kept as a lightweight redirect for the rare case where something
--     is still holding a stale person id from before a merge (e.g. a cached UI selection or a
--     deep link) — it is NOT needed to resolve a face's current owner, since `cluster.person_id`
--     is updated directly at merge time.

-- 1. New `cluster` table: one row per clustering group ("prototype" in the requirements doc).
--    A person can own multiple clusters — initially one (FR6), more after merges (FR4/FR8).
CREATE TABLE cluster
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id          BIGINT    NOT NULL REFERENCES person (id),
    centroid_embedding BYTEA     NOT NULL, -- same encoding as face_embedding.embedding (raw float32 LE bytes)
    member_count       INT       NOT NULL DEFAULT 0,
    created_at         TIMESTAMP NOT NULL,
    updated_at         TIMESTAMP NULL
);

CREATE INDEX idx_cluster_person_id ON cluster (person_id);

-- 2. Person: redirect target once a person has been merged into another (FR4).
ALTER TABLE person
    ADD COLUMN merged_into_id BIGINT NULL REFERENCES person (id);

-- 3. Face: replace the direct person_id link with cluster_id, and add the two correction flags.
--    - assignment_locked: true once a human explicitly assigns/confirms/moves this face
--      (FR1/FR2/FR3). Locked faces are never reassigned by automatic clustering, but they still
--      contribute to their cluster's centroid recompute (NFR1) — locking only protects the
--      assignment, not centroid participation.
--    - excluded: true for faces flagged "not a person" (FR5). Excluded faces are dropped from
--      clustering entirely and must not appear as a candidate in any person, including the
--      unclustered/"Unknown" view.
ALTER TABLE face
    ADD COLUMN assignment_locked BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE face
    ADD COLUMN excluded BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE face
    ADD COLUMN cluster_id BIGINT NULL REFERENCES cluster (id);

ALTER TABLE face
    DROP COLUMN person_id;

CREATE INDEX idx_face_cluster_id ON face (cluster_id);
